
=== Hootenanny API Documentation

Run `make archive` to generate the documentation. The generated file is: 
`$HOOT_HOME/hootenanny-$(HOOT_VERSION).tar.gz`. Alternatively, you can configure your Jenkins pull 
request job to archive the documentation by selecting: "Build with Parameters" and checking the 
"Archive_docs" checkbox. The documentation can be downloaded from the Jenkins job page as 
`docs.tar.gz`.

==== Core C++

When running `make archive`, see `docs/developer/CoreAPI/html/index.html` in 
`hootenanny-core-API-$(HOOT_VERSION).tar.gz` in the `docs` directory of 
`$HOOT_HOME/hootenanny-$(HOOT_VERSION).tar.gz`.

When generating the documentation from a pull request job look for 
`docs/developer/CoreAPI/html/index.html` in the `docs` directory of 
`$HOOT_HOME/hootenanny-$(HOOT_VERSION).tar.gz`.

==== Core JavaScript

See the "JavaScript API" and JavaScript Conflation Reference" sections in 
`docs/Hootenanny - User Guide.pdf` in the `docs` directory of 
`$HOOT_HOME/hootenanny-$(HOOT_VERSION).tar.gz`.

==== Services Java

See `hoot-services/target/site/apidocs/index.html` in `hootenanny-services-API-$(HOOT_VERSION).tar.gz` in the `docs` directory of `$HOOT_HOME/hootenanny-$(HOOT_VERSION).tar.gz`.

