
== Hootenanny Debugging

=== Core

==== Debug Logging

While there is no substitute for debugging with breakpoints added to an IDE, sometimes using debug 
logging can allow you to diagnose and fix a conflation bug more quickly. Hootenanny allows for log 
statements to be generated at various levels of granularity. The available log levels may be shown 
by executing `hoot help` from the command line. Hootenanny also allows for filtering which classes 
are allowed to write log statements to allow for tailoring the debugging experience. To filter logs 
by class, the `log.class.include.filter` and `log.class.exclude.filter` configuration options may be 
utilized. Filtering by wildcard with '*' is supported. See the documentation on those configuration 
options as well as the class documentation for `Log` and `LogGeneric` for additional information.

==== Debug Map Writing

At times, it can be difficult to determine where in the conflate process a particular map
data change is made. To assist with debugging, map files may be output at various places in
the chain. To turn on debug map writing, enable the `debug.maps.write` configuration option. To 
control where the map files are written to, edit the `debug.maps.filename` configuration option.
Additionally, debug maps be written at a more granular frequency by enabling the 
`debug.maps.write.detailed` configuration option. Enable the option with care, as it may result in
many files being written and slow down the debugging process considerably. Also, debug map writing
may be filtered by class in the same manner that debug logging is filtered. Modify the
`debug.maps.class.include.filter` and `debug.maps.class.exclude.filter` configuration options to do 
so. See the documentation on those configuration options as well as the class documentation for `OsmMapWriterFactory::writeDebugMap` for additional information.

Additional helpful debugging options:

* `uuid.helper.repeatable=true`
* `writer.include.debug.tags=true`
* `writer.include.conflate.score.tags=true`

=== Services

https://github.com/ngageoint/hootenanny/blob/master/hoot-services/DEBUG.md[See this]

