
== Faster Compile

As of 10/28/2015 my compile on circa 2012 hardware takes 4 minutes without ccache or other optimizations.

=== distcc

This is most useful when running hoot on VirtualBox.

1. Install distcc and ccache
+
--------
apt-get install distcc ccache
--------
2. Create a hosts file
+
--------
mkdir -p ~/.distcc
vi ~/.distcc/hosts
--------
3. Add a relevant list of hosts (e.g. `localhost/4 @@selma/8`) - The `@@` means it is a ssh host. The /# is the number of process to spawn on that machine.
4. If it doesn't already exist, add to each of the slaves:
+
--------
echo 'DISTCC_TCP_CORK=0' >> /etc/environment
--------
5. Modify your `LocalConfig.pri` to include this at the bottom.
+
--------
QMAKE_CXX=ccache distcc g++
--------
6. When you build now use `make -j#` where # is the number of processes * 2. In the example above it would be (4 + 8) * 2 or `make -j24`.
7. You'll want to update the make arguments in Qt Creator as well if you use Creator. 
** Click on _Projects_
** Click _Build & Run_
** Click _Details_ in the _Make_ section
** Add `-j24` (or similar) in the _Make arguments_ section

