
== Hootenanny Development Environment Setup Instructions

You have two options.

Option #1:

Use a Vagrant VM to setup the Hootenanny application without any development tools, and either install your custom development tools on the VM or use development tools already installed on your local machine to interact with the VM.  See the Vagrant VM setup instructions provided at: https://github.com/ngageoint/hootenanny/blob/master/VAGRANT.md for details.

Option #2:

If you want to build a development environment completely on bare metal for the highest possible performance:

* Download https://github.com/ngageoint/hootenanny/blob/master/scripts/InstallHootDevelopmentEnvironment.sh to your home directory.
* Edit your home path in the script and run it.  Hoot will be cloned and an (almost) complete development environment will be set up from scratch.  
* If you use the installed Eclipse IDE for services Java development, there are some additional configuration steps you will need to complete as described here: https://127.0.0.1:9443/redmine/projects/hootenany/wiki/Developer_-_Install_IDEs

The choice of development tools is personal, so you may want to tweak the script a bit.  In addition to development tools, the script also adds Hadoop support.  This script isn't guaranteed to always be up to date with the latest and greatest hoot, so you may want to look at Option #2.


