
== Using Validation Checks to Improve Conflated Maps

It is quite easy to produce conflated map output that initially seems accurate but upon further 
examination has quality issues. https://josm.openstreetmap.de/[JOSM] has an extensive collection of 
validation tools that can be used to detect such issues. Hootenanny is integrated with 
https://josm.openstreetmap.de/[JOSM] via the 
https://en.wikipedia.org/wiki/Java_Native_Interface[Java Native Interface (JNI)]. This allows 
Hootenanny C++ core code to invoke JOSM validators by making calls into its Java code. The 
integration code resides in the `hoot-josm` library and is used by the `validate` command, which 
uses the `JosmMapValidator` class, and the `JosmMapCleaner` class. 

Hootenanny has validation integration with some unit tests. See the "Test Output Validation" section 
under the "Hootenanny Tests" section in the Hootenanny Developer Guide for more information.

Notes:

* Not all validation failures are critical and some may be unavoidable in conflated output under 
certain circumstances.
* Validation failures across multiple validators are sometimes contradictory with each other.
* If conflation job is passed inputs that have validation errors, the output will almost undoubtedly
have some of the same validation errors. The input should be cleaned beforehand when possible.
* "Total failing validators" in the validation reports refer to the number of validators which 
exited program execution abnormally due to not being able to properly validate the input data 
provided (crashed). It does not refer to the number of validators which had validation errors. That 
total can be inferred from the total number of unique validation error types that occurred.

=== Generating Validation Reports

The Hootenanny/JOSM integration is a useful tool to detect undesirable changes to conflated output 
caused by code changes before they make it to the production environment. The `validate` command 
provides the capability for running validation checks on selected conflated output after it has been 
generated. Here is an example using one of the script tests:
-----
# Generate some conflated output.
HootTest --slow '--include=.*AreaConflateStandaloneTest.*'
# Now, generate the validation report for the same test using the test output previously generated 
# in the test-output directory, and write validation errors to a separate file.
hoot validate test-output/cmd/slow/AreaConflateStandaloneTest/Output.osm \
  --report-output test-output/cmd/slow/AreaConflateStandaloneTest/MyValidationReport \
  --output test-output/cmd/slow/AreaConflateStandaloneTest/ValidatedOutput.osm
-----

=== JOSM Configuration

The https://josm.openstreetmap.de/[JOSM] library used in Hootenanny validation and, optionally, 
cleaning may be configured within `hoot-josm/pom.xml`. Under the `<properties>` XML tag, configure 
`josm.artifactId` and `josm.version` for the JOSM JAR you wish to use. By default, this jar will be 
copied to `hoot-josm/target/dependency-jars/josm.jar`, and the path is referenced by the 
`jni.class.path` configuration option. If you need to reference a local jar (one not available in a 
public Maven repository), you must manually install it with `mvn install:install-file`. See 
`scripts/core/make-hoot-josm-java.sh` for an example.

Hootenanny produces its own JAR file to interact with the JOSM jar. By default, this jar will be 
built by Hootenanny and copied to `hoot-josm/target/hoot-josm.jar`.

See the jni.* and josm.* configuration options in `conf/core/ConfigOptions.asciidoc` for more detail 
on configuring Hootenanny to use JOSM.

