
== Regenerating Random Forest Models For Unifying Conflation

As of 12/19/18, generated Random Forest models (.rf) are used in Unifying Conflation for Road and Building conflation only.  If changes are 
made to code that affects the extracted features that help create them, the models must be regenerated and replaced in the hoot repository.
POI Generic Conflation makes use of the Attribute Relation File (.arff) only and does not actually use the generated Random Forest model.

To regenerate them:

* Under hoot-tests/unifying-tests.child/model-training.child:
  * Regenerate the buildings model:
    * Run the jakarta-buildings.child regression test
    * Remove the existing buildings model: 'rm -f HOOT_HOME/conf/models/BuildingModel*'
    * Compress the arff file: 'bzip2 jakarta-buildings.child/tmp/JakartaBuildingModel.arff'
    * Copy the compressed model to the hoot dir: 'cp jakarta-buildings.child/tmp/JakartaBuildingModel.arff.bz2 conf/models'
  * Regenerate the roads model:
    * Follow similar steps as done with the buildings model, but using the train-highways.child/tmp/HighwayModelAll.arff file.
  * Regenerate the POI model:
    * TODO
* Build hoot; the Random Forest files (.rf) and SHA1 hashes will be regenerated.
* Check all the file changes into the hoot repository
