
== Troubleshooting

This is similar, but not identical to, the troubleshooting section in the Hootenanny Installation Instructions, which is tailored to a CentOS/RHEL 6.x.

=== Core

* *Don't think the correct version of Hootenanny core is installed?* --> You can check the version of the core by clicking on the "Hootenanny | Innovision| logo from within the UI.  Or as a sanity check, type 'hoot --version' from the command line.  The version displayed should match the version you installed.  Finally, the core version used by the services can be found by navigating to the following URLs:
	** +http://localhost/hoot-services/info/about/coreVersionInfo+
	** +http://localhost/hoot-services/info/about/coreVersionDetail+

* *Not sure if hoot is using the correct version of a dependency library?* --> run: +ldd /usr/local/bin/hoot.bin+ to see a list of the libraries its using.  You can use +dpkg -l | grep <library name>+ to see the libraries installed on your system.

* *Problems reading/writing from the database when using hoot?* --> Verify the database credentials in:
	**  +/usr/local/hootenanny-X.Y.Z/conf/database/DatabaseConfigLocal.sh+
	**  +/usr/local/hootenanny-X.Y.Z/conf/database/DatabaseConfigDefault.sh+

* *"PostgreSQL" and "FileGDB" formats do not show when running ogrinfo --formats* --> Possibly you have compiled GDAL incorrectly. Re-compile with the steps listed in scripts/InstallHoot-CentOS-RHEL.sh that were run during the hoot core installation.

* *Problems with the GDAL Python module?* --> Make sure you compiled GDAL with the +--with-python+ switch.

* *Problems with gdal2tiles.py?* --> You may be able to solve this problem by modifying the GDAL2TILES property in +$HOOT_HOME/scripts/makerastertotiles+ by providing it with the full path to gdal2tiles.py (usually in +/usr/local/bin+ or +/usr/local/gdal<version>/swig/python/scripts+ ).

* *Getting a compiler failure when compiling Hoot core?* --> g++ fails with a non-descript error? Its not known what causes this yet, but its very bad and has happened a few times now. First, be sure you've done a make uninstall on the previous version of Hoot and go ahead and do a make uninstall on the version you're trying to compile. Its also possible you have a bad release, in which case a new one should be built.

* *Receiving Qt related errors at compile time?* --> Possibly, you are pointing to the incorrect version of Qt.  Hootenanny uses Qt 4.x and will not currently run on Qt 5.x, the default for Ubuntu 14.04.  Try running 'sudo apt-get remove qt5-default'.  Also use ldd to see if any other Qt 5 libraries are on Hootenanny's path and remove them as well.

=== Database

* *Unable to use PSQL?* --> Is the PSQL executable on your path?

* *Problems updating the hoot database schema?* --> Verify that the owner listed in the script is "hoot" throughout for all the hoot database tables. If not replace the text "OWNER TO <other-owner> with "OWNER TO hoot".

* *Unable to delete one of the databases?* --> try (from link:$$http://stackoverflow.com/questions/11388786/how-does-one-drop-a-template-database-from-postgresql$$[here]):

--------------------------------------
psql -U hoot
postgres=# UPDATE pg_database SET datistemplate='false' WHERE datname='database name';
UPDATE 1
postgres=# DROP DATABASE database name;
DROP DATABASE
--------------------------------------

OR

--------------------------------------
# check and see if anything is holding onto the database
SELECT * FROM pg_stat_activity WHERE datname='database name';
dropdb 'database name'
--------------------------------------

* *Want to clear data out of the hoot database?* -->

--------------------------------------
export HOOT_HOME=/usr/local/hoot
$HOOT_HOME/scripts/database/DeleteAllTables.sh
--------------------------------------

To re-create the hoot database, recompile Hootenanny using the --with-services option.

* *When using PSQL, asked for a password for a database (rather than for a user) and don't have it?* --> Possibly, you have authentication still set to MD5 in the pg_hba.conf file. Temporarily set unset if from MD5 (see Postgres install steps) to use PSQL. Set it back to MD5 when you've finished using PSQL.

* *Not sure if the Postgis extension has been installed properly?*-->
	** Check to see if following table exists in +wfsstoredb:spatial_ref_sys+

* *Getting a change log lock error?* -->

Delete all change log locks:
--------------------------------------
psql -U hoot
delete from databasechangeloglock *;
--------------------------------------

* *The liquibase dropAll command fails when running 'make clean-all' with a message that it cannot connect to Postgres.* -->  Postgres may not be running.  If +sudo service postgresql restart+ results in an error related to memory settings, you may need to revisit the tweaking of memory in the Postgres tuning section of the Hootenanny Installation Guide.  Sometimes these setting can be lost when upgrading Ubuntu.

=== Services

* *Need to monitor the Tomcat log for errors?* -->
--------------------------------------
tail -f /var/log/tomcat8/catalina.out | grep -i -e ERROR -e SEVERE
--------------------------------------
In some cases, you may need to execute the following instead:
--------------------------------------
tail -f /usr/share/tomcat8/logs/catalina.out | grep -i -e ERROR -e SEVERE
--------------------------------------

* *Not sure the correct version of Hootenanny services are deployed?* --> You can check the version of the core by clicking on the "Hootenanny | Innovision| logo from within the UI.  Or as a sanity check, verify the services version by navigating to the following URLs:
	** +http://localhost/hoot-services/info/about/servicesVersionInfo+
	** +http://localhost/hoot-services/info/about/servicesVersionDetail+

* *Do you want to see more granular services log output or redirect it to a file?* --> Edit +$HOOT_HOME/hoot-services/src/main/webapps/hoot-services/WEB-INF/class/log4j.xml+ . See the log4j documentation for details on how to edit the file. Restart Tomcat after any changes made to the file.

* *Problems reading/writing from the database when using hoot?* --> Verify the database credentials in:
	**  +$HOOT_HOME/conf/database/DatabaseConfigLocal.sh+
	**  +$HOOT_HOME/conf/database/DatabaseConfigDefault.sh+
	**  +$HOOT_HOME/hoot-services/src/main/webapps/hoot-services/WEB-INF/classes/db/spring-database.xml+ 
	**  +$HOOT_HOME/hoot-services/src/main/webapps/hoot-services/WEB-INF/classes/conf/hoot-services.conf+ 
	**  +$HOOT_HOME/hoot-services/src/main/webapps/hoot-services/WEB-INF/workspace/jdbc/WFS_Connection.xml+ 
	** Also, verify +$HOOT_HOME/hoot-services/src/main/webapps/hoot-services/WEB-INF/classes/db/spring-database.xml+ 
		. maxActive=90
		. maxIdle=30
	** Also, verify +$HOOT_HOME/hoot-services/src/main/webapps/hoot-services/WEB-INF/workspace+ has read and write permission so it can create WFS store config xml files.

* *Having problems with the WFS?* -->
	** Verify wfsstoredb has been properly set up (see database troubleshooting section).
	** Check +$HOOT_HOME/hoot-services/src/main/webapps/hoot-services/WEB-INF/workspace/jdbc/WFS_Connection.xml+ 
	** Verify +$HOOT_HOME/hoot-services/src/main/webapps/hoot-services/WEB-INF/workspace+ has had its permissions set correctly.

* *Seeing this WFS error?* -->

--------------------------------------
2014-09-11 10:26:27 ERROR AbstractResourceManager:268 - Could not create resource web services: Error initializing WFS/FeatureStores: Cannot add feature store 'ex_601e0eb1bb994c3c949ddbed78424c6b': no such feature store has been configured.
2014-09-11 10:26:27 ERROR AbstractResourceManager:270 - Cause was: Cannot add feature store 'ex_601e0eb1bb994c3c949ddbed78424c6b': no such feature store has been configured.
--------------------------------------

You're seeing expired WFS links. To remove them:

--------------------------------------
cd $HOOT_HOME/hoot-services/src/main/webapps/hoot-services/WEB-INF/workspace
sudo rm -f datasources/feature/ex_*.xml 
sudo rm -f datasources/feature/*.properties
sudo rm -f services/ex_*.xml
--------------------------------------

* *Seeing this error: "--ogr2osm Unable to open /path/to/file.shp"* --> Possibly you do not have the Postgres extension installed for GDAL. See related troubleshooting tip in the "Core" section.

* *Errors when building Java in Eclipse and have no idea reason why?* --> Try running +make eclipse+ from the command line, refreshing the project in Eclipse, and recompiling.

[[HootUITroubleshoot]]
=== UI

* *Not sure the correct version of the user interface is installed?* --> You can check the version of the user interface by clicking on the "Hootenanny | Innovision| logo from within the UI.

* *Trouble seeing your base map?* -->
	** In +$HOOT_HOME/hoot-services/src/main/webapps/hootenanny-id/data/imagery.json+ , verify that the base map URLs for all your layers are correct.
	** You may also need to tweak the "source.url" variable in +$HOOT_HOME/hoot-services/src/main/webapps/hootenanny-id/js/id/renderer/background_source.js+ depending on how the base maps are to be parsed. Make sure the URL produced by iD.BackgroundSource. <your layer> function is correct by cut and pasting the URL on browser and see if that returns image.
	** If changes are made to the imagery.json file, always then clear the browser history, close the browser, and open a new browser pointed to the Hootenanny UI application.

