
[[HootInstallTroubleshooting]]
=== Troubleshooting

NOTE: Some of this information is specific to the formerly supported Ubuntu installation.

==== Core

* *Don't think the correct version of Hootenanny core is installed?* -> You can check the version of the core by clicking on the "Hootenanny" logo from within the UI. Or as a sanity check, type 'hoot version' from the command line.  The version displayed should match the version you installed. Finally, the core version used by the services can be found by navigating to the following URLs:
	** `http://localhost/hoot-services/info/about/coreVersionInfo`
	** `http://localhost/hoot-services/info/about/coreVersionDetail`

* *Not sure if hoot is using the correct version of a dependency library?* -> run: `ldd /usr/local/bin/hoot.bin` to see a list of the libraries its using. You can use `yum list installed | grep <library name>` to see the libraries installed on your system.

* *Problems reading/writing from the database when using hoot?* -> Verify the database credentials in:
	**  `/usr/local/hootenanny-X.Y.Z/conf/database/DatabaseConfigLocal.sh`
	**  `/usr/local/hootenanny-X.Y.Z/conf/database/DatabaseConfigDefault.sh`

==== Database

* *Want to clear data out of the hoot database?* ->
--------------------------------------
make clean-db
--------------------------------------

* *Unable to delete one of the databases?* -> try (from link:$$http://stackoverflow.com/questions/11388786/how-does-one-drop-a-template-database-from-postgresql$$[here]):

--------------------------------------
psql -U hoot
postgres=# UPDATE pg_database SET datistemplate='false' WHERE datname='database name';
UPDATE 1
postgres=# DROP DATABASE database name;
DROP DATABASE
--------------------------------------

OR

--------------------------------------
# check and see if anything is holding onto the database
SELECT * FROM pg_stat_activity WHERE datname='database name';
dropdb 'database name'
--------------------------------------

To re-create the hoot database, run `make`.

* *When using PSQL, asked for a password for a database (rather than for a user) and don't have it?* -> Possibly, you have authentication still set to MD5 in the pg_hba.conf file. Temporarily set unset if from MD5 (see Postgres install steps) to use PSQL. Set it back to MD5 when you've finished using PSQL.

* *Getting a change log lock error?* ->

Delete all change log locks:

--------------------------------------
psql -U hoot
delete from databasechangeloglock *;
--------------------------------------

==== Firewall

*Trouble accessing Tomcat?* -> Compare your `/etc/sysconfig/iptables` with this working version. Sometimes I have to move the `-A INPUT -j REJECT --reject-with icmp-host-prohibited` line below the `--dport 8080` line. I haven't spent the time to figure out how to fix this on the command line.

--------------------------------------
# Generated by iptables-save v1.4.7 on Tue Apr 29 10:42:18 2014
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080
-A OUTPUT -d 127.0.0.0/8 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080
COMMIT
# Completed on Tue Apr 29 10:42:18 2014
# Generated by iptables-save v1.4.7 on Tue Apr 29 10:42:18 2014
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [12:2304]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
# Completed on Tue Apr 29 10:42:18 2014
--------------------------------------

==== Services

* *Need to monitor the Tomcat log?* ->

--------------------------------------
sudo journalctl -eu tomcat8
--------------------------------------

* *Not sure the correct version of Hootenanny services are deployed?* -> You can check the version of the core by clicking on the "Hootenanny | Innovision| logo from within the UI.  Or as a sanity check, verify the services version by navigating to the following URLs:
	** `http://localhost/hoot-services/info/about/servicesVersionInfo`
	** `http://localhost/hoot-services/info/about/servicesVersionDetail`

* *Do you want to see more granular services log output or redirect it to a file?* -> Edit `/var/lib/tomcat8/webapps/hoot-services/WEB-INF/classes/log4j2.xml` . See the log4j2 documentation for details on how to edit the file. Restart Tomcat after any changes made to the file.

[[HootUITroubleshoot]]
==== UI

* *Authentication issues?* See `docs/developer/OAUTH.md`

