
=== Code Documentation

==== Core

Class documentation is used to build displayable documentation with 
(https://www.doxygen.nl/index.html)[doxygen]. Details on how to obtain the documentation are 
specified (https://github.com/ngageoint/hootenanny/blob/master/docs/developer/HootenannyAPI.asciidoc)[here].

At a minimum, all public and protected class members that are not simple getters or setters should 
be documented. Private members may be documented on an as needed basis but their documentation will 
not be displayed in the API documentation generated by doxygen. Qt Creator will autocreate 
documentation templates for classes and method when you type `/**` and press enter. Use complete 
sentences in documentation where possible.

===== Classes

Class documentation should look something like this:

-----
@brief The WaySublineRemover class removes a sublines from ways.

Optional other info a couple lines down...
-----

It will also work without @brief:

-----
Removes a sublines from ways.

Optional other info a couple lines down...
-----

===== Methods

Public/Protected method documentation should look something like this:

-----
/**
  * @brief removeSubline removes a subline from a way.
   
    Optional other info a couple lines down...
  * @param way the way to modify
  * @param subline the subline in the way to remove
  * @param map the map owning the way
  * @return IDs of the ways created and added back to the map as a result of the subline removal
  */
  static std::vector<ElementId> removeSubline(
    const WayPtr& way, const WaySubline& subline, OsmMapPtr& map);
-----

It will also work without @brief:

-----
/**
  * Removes a subline from a way.
   
    Optional other info a couple lines down...
  * @param way the way to modify
  * @param subline the subline in the way to remove
  * @param map the map owning the way
  * @return IDs of the ways created and added back to the map as a result of the subline removal
  */
  static std::vector<ElementId> removeSubline(
    const WayPtr& way, const WaySubline& subline, OsmMapPtr& map);
-----

===== Variables

Public/Protected variable documentation should look something like this:

-----
/** This integer variable is documented. */
static int MY_INT;

/// This integer variable is documented.
static int MY_INT;
---- 

