
== Hootenanny OSM API Database Conflation Testing Notes

Testing Hootenanny conflation with OSM API database (MapEdit) data without access to a complete, production OSM API database is a little 
cumbersome, but possible.  First, read the "Conflating OSM API Database Data" in the web user interface document for details on the workflow and 
limitations involved with conflating this type of data.

=== Testing the Changeset Conflict Detection for OSM API Database Export

As described in the web user interface guide, when exporting a conflated dataset into an OSM API database, Hootenanny will detect any conflicts
due to data written to the OSM API database after the conflation occurred and raise an exception.  Since there is no way to upload a conflicting
changeset into an OSM API database from within Hooteannny's iD Editor, this situation can be simulated with the following steps (as used in 
the OSM API database conflation user interface test, test-files/ui/features/conflate_export_osm_api_db.feature):

* Write a dummy changeset with a unique ID, a timestamp some time arbitrarily far in the future, and a bounds overlapping with some data that 
you will later conflate.  See test-files/ui/conflict_changeset.sql for the example SQL to do this.
* Then conflate a Hootenanny dataset, having a bounds overlapping that of the dummy changeset, with data from the same OSM API database you 
wrote the dummy changeset to.

You should receive a "conflict" error message from Hootenanny inside of iD Editor when doing this.



