
####
# 
####

SHELL=/bin/bash

# If the silent flag is passed to make then make Maven quiet too.
ifneq (,$(findstring s,$(MAKEFLAGS)))
    MVN_QUIET="-q"
    SCRIPT_QUIET=> /dev/null 2>&1
endif

default: build

build:


clean: 


test: 
