Feature: Manually resolve reviews feature

  Scenario: I can conflate the AllDataTypes data, manually resolve some reviews, and merge some POIs during the review process
    Given I am on Hootenanny
    And I resize the window
    And I click Get Started
    And I press "Add Reference Dataset"
    And I click the "AllDataTypesACucumber" Dataset
    And I press "Add Layer"
    Then I wait 30 "seconds" to see "AllDataTypesACucumber"
    And I press "Add Secondary Dataset"
    And I click the "AllDataTypesBCucumber" Dataset
    And I press "Add Layer"
    Then I wait 30 "seconds" to see "AllDataTypesBCucumber"
    Then I should see "Conflate"
    And I press "Conflate"
    And I append "saveAs" input with "_Cucumber"
    And I scroll element into view and press "conflate2"
    Then I wait 30 "seconds" to see "Conflating …"
    Then I wait 3 "minutes" to see "Merged_AllDataTypes"
    Then I should see "Complete Review"
    Then I wait 30 "seconds" to see "Reviews remaining: 8 (Resolved: 0)"
    Then I should see "Hide Table"
    Then I should see "name"
    Then I should see "Previous"
    Then I should see "Next"
    Then I should see "Resolved"
    #Then I should see "Merge"
    #And I press "Merge"
    #Then I wait 30 "seconds" to see "Resolved"
    #And I hover over ".layer-data"
    #And I click the "map" at "100","100"
    And I press "Resolved"
    #This should work too
    #And I click the "r" key
    Then I wait 30 "seconds" to see "Reviews remaining: 7 (Resolved: 1)"
    And I press "Resolved"
    Then I wait 30 "seconds" to see "Reviews remaining: 6 (Resolved: 2)"
    And I press "Resolved"
    Then I wait 30 "seconds" to see "Reviews remaining: 5 (Resolved: 3)"
    And I press "Resolved"
    Then I wait 30 "seconds" to see "Reviews remaining: 4 (Resolved: 4)"
    And I press "Resolved"
    Then I wait 30 "seconds" to see "Reviews remaining: 3 (Resolved: 5)"
    And I press "Resolved"
    Then I wait 30 "seconds" to see "Reviews remaining: 2 (Resolved: 6)"
    And I press "Resolved"
    Then I wait 30 "seconds" to see "Reviews remaining: 1 (Resolved: 7)"
    And I press "Merge"
    Then I wait 30 "seconds" to see "Resolved"
    And I press "Next"
    Then I wait 5 "seconds" to see "Please resolve or undo the current feature changes before proceeding to the next review."
    And I press "Previous"
    Then I wait 5 "seconds" to see "Please resolve or undo the current feature changes before proceeding to the next review."
    And I press "Resolved"
    Then I wait 10 "seconds" to see "There are no more available features to review.  Exiting the review session."
    Then I should not see "Reviews remaining:"
    Then I should not see "Hide Table"
    Then I should not see "name"
    Then I should not see "Previous"
    Then I should not see "Next"
    Then I should not see "Resolved"
