#!/bin/bash

# resets the getopts in case used prior
OPTIND=1

# help usage function
function show_help {
  echo "rebuild {-eh?}"
  echo "-h,-? : help"
  echo "-e    : run eclipse setup"
}

# init vars
eclipse=no

# process args
while getopts "h?e" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    e)  eclipse=yes
        ;;
    esac
done

set -e 
scripts/mvn-build clean $@
scripts/mvn-build build $@
if [ "$eclipse" = "yes" ]
then
  echo "setting up eclipse"
  scripts/mvn-build eclipse $@
fi
