
== Overview

NOTE: that the some of the hyperlinks in this document only are navigable when the document is in PDF form.

Mapping data is a commodity with a demand that continues to increase with the
growth of geographically-enabled applications.  Mapping data is generated by
commercial, government, and more recently by crowd-sourced methods such as
<<OpenStreetMap,OpenStreetMap>> and WikiMapia footnote:[ WikiMapia or Wikimapia
is an open-content collaborative mapping project that aims to mark and
describe all geographical objects in the world. http://wikimapia.org ]. The
challenge is that no one source has it all, but collectively multiple resources
provide the best picture.   "Conflation of maps refers to a combining
of two digital map files to produce a third map file which is 'better' than each
of the component source maps." (<<saalfeld1987,Saalfeld 1985>>) A conflated
dataset is critical to making a better map and is also the foundation to more
effective geospatial analytics (i.e., geocoding, routing).

The task of selecting which dataset(s) to use and merge becomes a daunting process
often requiring a case-by-case evaluation where analysts are forced to resort to
multiple ad-hoc conflation techniques (automated and manual) which quickly becomes
labor intensive and stove-piped. As such, multiple conflation efforts occur in
isolated projects by numerous users for specific purposes with varying workflows,
rules, schemas, formats, and data quality. This type of approach creates inefficiencies
and lacks the standardization that is required for large scale organizational use,
maintenance, and development activities.

To this end, Hootenanny was developed to provide an open source standards based
approach to geospatial vector-data conflation. Hootenanny is designed to facilitate
automated and semi-automated conflation of critical Foundation GEOINT features in
the topographic domain, namely roads (polylines), buildings (polygons), and
points-of-interest (POIs) (points). Conflation happens at the dataset level,
where the user’s workflow determines the best reference dataset and source content,
geometry and attributes, to transfer to the output map. The input data must be
normalized to allow processing and matching of features and attributes from different
schemas. Hootenanny internal processing leverages the key value pair structure of
OpenStreetMap (OSM) for improved utility and applicability to broader user groups,
e.g. normalized attributes can be used to aid in feature matching and OSM’s free
tagging system allows the map to include an unlimited number of attributes describing
each feature (OpenStreetMap/Map Features, 2015).

Historically, conflation applications have been specialized desktop tools which
required a niche expertise with reoccurring licensing requirements and difficult
to customize or add functionality. However, open source software provides an
attractive business model where the user community can contribute, customize,
share, and help maintain the software in an interactive environment. For this
reason, Hootenanny is being developed under the open source General Public License
(GPL) and will be hosted on the National Geospatial-Intelligence Agency’s (NGA)
https://github.com/ngageoint/hootenanny[GitHub website] (NGA GitHub, 2015).

