
== Conflation Statistics Report 

Hootenanny offers the capability to generate a report describing statistics associated with the conflate command. The report provides graph and text summaries for a collection of different statistics associated with the data being used and command parameters applied in the conflation process.  

=== How to Generate Reports

The Hootenanny Conflation Statistics Report, which will be referred to as Report from now on, is generated currently from the command line.  The command line usage is:

------
hoot conflate {hoot_args} {report_args} {input1} {input2} {output} --stats

where
{hoot_args} generally contains the following options:
  
but may contain other Hootenanny configuration options also.

{report_args} =
  -D writer.include.debug 
  -D stats.class="hoot::ScriptStatsComposer"
  -D stats.script={$HOOT_HOME/report/csr-default.js|other_script}
  -D stats.format={pdf|asciidoc|html}
  -D stats.output={report_pathname_prefix}

The default stats.script value is $HOOT_HOME/report/csr-default.js, but other scripts can be designed and provide either a different arangement of the Report and/or different statistical metrics.  

The stats.format can be set to output either PDF, Html, or Asciidoc formats.

The stats.output argument is the file system path prefix for the output Report.  This excludes the suffix. E.g. /tmp/Report and not /tmp/Report.pdf.

{input1} the first input OSM file (e.g., $HOOT_HOME/test-files/ToyTestA.osm)
{input2} the second input OSM file (e.g., $HOOT_HOME/test-files/ToyTestB.osm)
{output} the output conflated OSM file (e.g., /tmp/ToyTestAandB.osm)
------

An example to generate the Report in PDF called 'BigReport.pdf' using the default format template acting upon inputs 'input1.osm' and 'input2.osm' and output file 'output.osm' is provided here:

------
hoot conflate -D writer.include.debug=true -D stats.class="hoot::ScriptStatsComposer" -D stats.script=$HOOT_HOME/report/csr-default.js -D stats.format=pdf -D stats.output=BigReport $HOOT_HOME/test-files/ToyTestA.osm $HOOT_HOME/test-files/ToyTestB.osm /tmp/ToyTestAandB.osm --stats
------

=== Details about the contents of the report

Coming Soon
