
== Hootenanny API Database 

It is possible within Hootenanny to leverage the HootAPI database in postgres as a datastore for common operations such as data ingest, file conversion, generating statistics, and conflation, etc.  The following section provides basic examples of hoot commands using a postgres instance running on your local hootenanny server.  In all of the provided examples the postgres URL will appear as shown below.

Example Usage:

------
hootapidb://(dbuser):(dbpw)@(db_url):(port)/(dbname)/(name_of_dataset)
e.g. hootapidb://hoot:hoottest@localhost:5432/hoot/DcGISRoads
------

* hootapidb:// - the URL prefix to access postgres data stored in the HootAPI database
* dbuser - hoot database user ('hoot' is default value)
* dbpw - database password ('hoottest' is default value)
* db_url - domain of postgres instance running on hoot server e.g. localhost
* port - postgres database port (5432 is default value)
* dbname - name of the database ('hoot' is default value)
* name_of_dataset - name of the dataset stored in MAPS table.

=== Hootenanny API Database Ingest

Ingest a *.osm.pbf dataset into a HootAPI database.

Example Usage:

------
hoot convert -D hootapi.db.writer.create.user=true -D api.db.email='test@test.com' test-files/DcGisRoads.osm  hootapidb://hoot:hoottest@localhost:5432/hoot/DcGISRoads2
------

* +-D hootapi.db.writer.create.user+ - a required parameter when using instantiating a new user from the hoot.json file.
* +-D api.db.email+ - a required email notification parameter for the hoot.json file.  The value should appear in +hoot.json+ with a placeholder email address.
* input - a path to any input data (e.g. .osm, .shp, etc..)
* output - output dataset name (name of the layer to appear in the Hootenanny database)


=== Conflating Data sources

Conflate two layers from a HootAPI database.

Example Usage:

------
hoot conflate -D api.db.email='test@test.com' hootapidb://hoot:hoottest@localhost:5432/hoot/DcGisRoads hootapidb://hoot:hoottest@localhost:5432/hoot/DcTigerRoads  hootapidb://hoot:hoottest@localhost:5432/hoot/Merged_Roads_test
------

* +-D api.db.email+ - required email notification parameters for the hoot.json file.  The value should appear in +hoot.json+ with a placeholder email address.
* +-D api.db.email+ - required email notification parameters for the hoot.json file.  The value should appear in +hoot.json+ with a placeholder email address.
* input 1 - Input 1 (e.g. postgres map name in MAPS table)
* input 2 - Input 2 (e.g. postgres map name in MAPS table)
* output - Output name (name to appear in PostGIS)

=== File Translation

Exporting data from a HootAPI database using an OSM translation schema.

Shapefile export:

------
hoot convert -D api.db.email='test@test.com' hootapidb://hoot:hoottest@localhost:5432/hoot/DcGisRoads tmp/DGRoads.shp --trans translations/OSM_Ingest.js
------

* translation file - a translation file used to translate source data attribution
* input - input postgres dataset name
* output - output dataset (e.g. .shp, .fgdb, .csv, etc..)

File Geodatabase export:

------
hoot convert -D api.db.email='test@test.com' hootapidb://hoot:hoottest@localhost:5432/hoot/DcGisRoads tmp/DGRoads.gdb --trans translations/MGCP_TRD4.js
------

* translations/MGCP_TRD4.js - the MGCP_TRD4 translation used to translate the data.

=== Other HootAPI Database Examples

==== Crop-map

Crops the input map to the given bounds. Individual features on the border are modified to make sure nothing is outside the given bounds.  For additional details see the +crop+ command line section.

Example Usage:

------
crop (input.osm) (output.osm) (bounds)
e.g. hoot crop hootapidb://hoot:hoottest@localhost:5432/hoot/DcGisRoads "-77.0551,38.8845,-77.0281,38.9031"
------

==== Generate Stats

The stats command reads input and write out hootenanny map statistics such as node and way count. For more details refer to the +stats+ command line section.

Example Usage:

------
hoot stats -D api.db.email='test@test.com' hootapidb://hoot:hoottest@localhost:5432/hoot/DcGisRoads
------

Sample Output:

------
Stat Name       hootapidb://hoot:hoottest@localhost:5432/hoot/DcGisRoads
Node Count      4324
Way Count       374
Relation Count  0
Total Feature Tags      748
Total Feature Information Tags  748
Total Feature Metadata Tags     0
Unique Names    66
Meters of Linear Features       56298.4
Meters Squared of Area Features 0
POI Count       0
Highway Count   374
Meters of Highway       56298.4
Highway Unique Name Count       66
Building Count  0
Meters Squared of Buildings     0
Building Unique Name Count      0
Conflated Feature Count 0
Conflated Feature Percentage    0
Unconflated Feature Count       4698
Unconflated Feature Percentage  100
Conflated POI Count     0
Conflated Highway Count 0
Meters of Conflated Highway     0
Conflated Buildings Count       0
Meters Squared of Conflated Buildings   0
Number of Features Marked for Review    0
Percentage of Features Marked for Review        0
Longest Tag     28
Translated Populated Tag Percent        0.106895
Translated Populated Tag Count  1879
Translated Default Tag Count    15699
Translated Null Tag Count       0
Building Translated Populated Tag Percent       nan
Highway Translated Populated Tag Percent        0.106895
POI Translated Populated Tag Percent    nan
------
