
[[ImplicitTagging]]
== Implicit Tagging Based On Name

Hootenanny has the capability to derive type tag information automatically for elements based soley on the contents of their name tags.  Currently, 
implicit tagging is only supported for POI data.  This feature can be used simply to add better tags to poorly typed data or to add tags with 
the goal of improving conflated output between datasets.  

This feature should not be used unless the addition of some false type tags to the input data is acceptable.  There are no metrics yet for how many false
tags this technique will generate on average, although the number is typically small and will become smaller over time as the feature is refined.

To use the feature from the command line with your POI data:

--------------------------
hoot convert -D convert.ops=hoot::ImplicitPoiTagger input.osm output.osm
--------------------------

To use the feature from the command line during conflation:

------------------------
hoot conflate -D conflate.pre.ops=hoot::ImplicitPoiTagger input1.osm input2.osm output.osm
------------------------

Features modified by the implicit POI tagger are marked with the tag "hoot:implicitTags:tagsAdded" to let you know what tags were added to the data and which name tags triggered the additions.  If you have suggestions on how to improve the quality of the implicit tagging, please contact the Hootenanny Development Team.
