
[[SnapUnconnectedWays]]
== Snap Unconnected Ways

If you want to snap unconnected linear features (e.g. roads) within a single dataset or in two
different datasets back to neighboring linear features without running full conflation, Hootenanny
allows for that. You can control the types of features snapped, which direction they snap in (to
reference or to secondary), and whether they snap to existing way nodes or generate new ones.

See examples in the "Command Line Examples" section of the User Documentation.

=== Reviewing

The +snap.unconnected.ways.review.snapped.ways+ option can be enabled to flag any snapped way for
review. This allows you to manually correct any poorly snapped ways.

The +snap.unconnected.ways.mark.only+ option bypasses way snapping completely, and when used in
conjunction with the +snap.unconnected.ways.review.snapped.ways+ option, marks any ways that would
have been snapped withthe current configuration as needing review. This allows you to have complete
manual control over way snapping.

=== Configuration

See the snap.unconnected.ways.* configuration options for more information on customization.


