SHELL=/bin/bash

clean:
	cd ..; scripts/HootEnv.sh $(MAKE) -f Makefile.old clean
check:
	cd ..; scripts/HootEnv.sh $(MAKE) -f Makefile.old check

install:
uninstall:

all:
	cd ..; scripts/HootEnv.sh $(MAKE) -f Makefile.old all

default:
	cd ..; scripts/HootEnv.sh $(MAKE) -f Makefile.old
