SHELL=/bin/bash

clean:
	cd ..; scripts/HootEnv.sh $(MAKE) -f Makefile.hoot clean
check:
	cd ..; scripts/HootEnv.sh $(MAKE) -f Makefile.hoot check

install:
uninstall:

all:
	cd ..; scripts/HootEnv.sh $(MAKE) -f Makefile.hoot all

default:
	cd ..; scripts/HootEnv.sh $(MAKE) -f Makefile.hoot
