/*
 * This file is part of Hootenanny.
 *
 * Hootenanny is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * --------------------------------------------------------------------
 *
 * The following copyright notices are generated automatically. If you
 * have a new notice to add, please use the format:
 * " * @copyright Copyright ..."
 * This will properly maintain the copyright information. DigitalGlobe
 * copyrights will be updated automatically.
 *
 * @copyright Copyright (C) 2012, 2013 DigitalGlobe (http://www.digitalglobe.com/)
 */

////
// This file is automatically generated. Please do not modify the file
// directly.
////

  // Hootenanny Javascript configuration options
module.exports = {

  /**
   * Debugging: Add the FCODE as the OSM source:fcode tag during translation.
   */
  OgrDebugAddfcode : false,

  /**
   * Debugging: Print out Attributes and OSM Tag values during translation. For each feature,
   * this will
   * show what keys and values go into the translation and what the translated output is.
   */
  OgrDebugDumptags : false,

  /**
   * Debugging: Print out which attributes are dropped during export validation.
   */
  OgrDebugDumpvalidate : false,

  /**
   * Debugging: When building internal lookup tables, print values that clash.
   */
  OgrDebugLookupclash : false,

  /**
   * Debugging: Print the columns that are not matched during one2one translation. This will show
   * all
   * Attribute columns and values that do not match a one2one rule.
   */
  OgrDebugLookupcolumn : false,

  /**
   * When exporting to MGCP:
   * - "file" Save the unused tags in a new layer (extra_[PLA]).
   * - "note" Add unused tags to the "TXT" field.
   * - "none" Don't save the unused tags, just drop them.
   *
   * NOTE: According to the MGCP and Shapefile specifications, the "TXT" field has a maximum
   * length of 255 characters. Extra text will be truncated.
   */
  OgrMgcpExtra : false,

  /**
   * Write partial translations instead of o2s_[PAL] features.
   */
  OgrPartialTranslate : false,

  /**
   * If the list of o2s tags is > 255 char, split it into into 254 char long pieces. If this is
   * false,
   * it will be exported as one big string.
   */
  OgrSplitO2s : false,

  /**
   * When exporting to TDSv40 and TDSv61:
   * - "note" Add unused tags to the "ZI006_MEM" field.
   * - "file" Save the unused tags in a new layer (extra_[PLA]).
   * - "none" Don't save the unused tags, just drop them.
   *
   * NOTE: If exporting to Shapefile, this field will be truncated to 255 characters.
   */
  OgrTdsExtra : false,

  /**
   * For the schema switcher, throw errors instead of returning a partial translation/o2s_X
   * feature from a translation.
   */
  OgrThrowError : false

};
