#!/bin/bash

export TOMCAT_PORT=`cat $TOMCAT6_HOME/conf/server.xml | grep -e "<Connector.*HTTP\/1.1\"\w*" | grep -v SSL | sed -e "s/\s*<Connector.*port=\"\([0-9]*\)\" protocol=.*/\1/g"`

SERVICES_LOCAL_CONF=$HOOT_HOME/hoot-services/src/main/resources/conf/local.conf
if [ ! -f $SERVICES_LOCAL_CONF ]; then
  echo "# This file is automatically generated by Config.sh" >> $SERVICES_LOCAL_CONF
  echo ErrorLogPath=$TOMCAT6_HOME/logs/catalina.out >> $SERVICES_LOCAL_CONF
  echo coreJobServerUrl=http://localhost:$TOMCAT_PORT >> $SERVICES_LOCAL_CONF
fi

# set the mapnik server to its port default
NODE_MAPNIK_SERVER_PORT=8000
# p2p port is configured by the services, so parse it out of hoot-services.conf
P2P_PORT=`sed '/^\#/d' $SERVICES_LOCAL_CONF | grep 'P2PServerPort'  | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'`
if [[ -z "${P2P_PORT// }" ]]; then
  P2P_PORT=`sed '/^\#/d' $HOOT_HOME/hoot-services/src/main/resources/conf/hoot-services.conf | grep 'P2PServerPort'  | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'`
  if [[ -z "${P2P_PORT// }" ]]; then
    # really shouldn't be empty at this point...
    P2P_PORT=8096
  fi
fi
# skipping translation server port, since clients query the service for its port (unlike the other services)

