FROM rockylinux:9

ARG hoot_user
ARG hoot_uid
ARG hoot_gid
ARG hoot_group
ARG hoot_shell=/bin/bash
ARG hoot_home
ARG glpk_version
ARG liboauthcpp_version
ARG libphonenumber_version
ARG libpostal_version
ARG protobuf_version=3.17.3
ARG node_version
ARG npm_version
ARG v8_version
ARG stxxl_version
ARG armadillo_version
ARG gdal_version
ARG geos_version
ARG libgeotiff_version
ARG proj_version
ARG devtoolset_version
ARG stxxl_version
ARG postgresql_version
ARG jdk_version
ARG google_chrome_version


ENV HOOT_HOME=$hoot_home

COPY scripts/yum/geoint-repo.sh scripts/yum/hoot-repo.sh scripts/yum/pgdg-repo.sh /tmp/

RUN dnf -y install dnf-plugins-core epel-release && \
    dnf config-manager --set-enabled crb && \
    GEOINT_DEPS_BASEURL=https://geoint-deps.s3.amazonaws.com/el9/stable \
        GEOINT_DEPS_REPO_GPGCHECK=0 \
        /tmp/geoint-repo.sh && \
    HOOT_DEPS_REPO_GPGCHECK=0 /tmp/hoot-repo.sh && \
    /tmp/pgdg-repo.sh $postgresql_version && \
    dnf -y module enable nodejs:${node_version%%.*} && \
    dnf -y makecache

RUN dnf -y --disablerepo=pgdg* install \
        armadillo-$armadillo_version \
        geos-$geos_version \
        geos-devel-$geos_version \
        glpk-$glpk_version \
        glpk-devel-$glpk_version \
        google-chrome-stable-$google_chrome_version \
        libgeotiff-$libgeotiff_version \
        libgeotiff-devel-$libgeotiff_version \
        liboauthcpp-$liboauthcpp_version \
        liboauthcpp-devel-$liboauthcpp_version \
        libpostal-$libpostal_version \
        libpostal-data-$libpostal_version \
        libpostal-devel-$libpostal_version \
        npm-$npm_version \
        nodejs-$node_version \
        nodejs-devel-$node_version \
        nodejs-docs-$node_version \
        nodejs-libs-$node_version \
        proj-$proj_version \
        proj-devel-$proj_version

RUN dnf -y --disablerepo=pgdg* install \
        gdal-$gdal_version \
        gdal-devel-$gdal_version \
        gdal-python-tools-$gdal_version && \
    rpm -q gdal gdal-devel gdal-python-tools && \
    GDAL_CONFIG_PATH="$(find /usr -path '*/bin/gdal-config' -type f 2>/dev/null | head -n1)" && \
    test -n "$GDAL_CONFIG_PATH" && \
    ln -sf "$GDAL_CONFIG_PATH" /usr/local/bin/gdal-config

RUN dnf -y --disablerepo=pgdg* \
        --exclude=armadillo* \
        --exclude=gdal* \
        --exclude=geos* \
        --exclude=glpk* \
        --exclude=libgeotiff* \
        --exclude=nodejs* \
        --exclude=npm \
        --exclude=proj* \
        --exclude=python3-gdal \
        install \
        asciidoc \
        autoconf \
        autoconf-archive \
        automake \
        bison \
        boost-devel \
        bzip2 \
        ccache \
        cmake \
        cppunit-devel \
        dblatex \
        doxygen \
        gcc-c++ \
        git \
        git-core \
        gnuplot \
        gtest-devel \
        lcov \
        libffi-devel \
        libicu-devel \
        libpng-devel \
        libtool \
        maven \
        m4 \
        mlocate \
        opencv \
        opencv-core \
        opencv-devel \
        osmosis \
        java-$jdk_version-openjdk-devel \
        perl-XML-LibXML \
        parallel \
        make \
        python-unversioned-command \
        python3 \
        python3-devel \
        python3-matplotlib \
        python3-opencv \
        python3-pip \
        python3-setuptools \
        qt5-qtbase \
        qt5-qtbase-devel \
        qt5-qtbase-postgresql \
        qt5-qtwebkit \
        qt5-qtwebkit-devel \
        readline-devel \
        lsb_release \
        sqlite-devel \
        swig \
        tex-fonts-hebrew \
        texlive \
        texlive-collection-fontsrecommended \
        tomcat8 \
        unzip \
        vim-enhanced \
        wamerican-insane \
        w3m \
        wget \
        words \
        xorg-x11-server-Xvfb \
        zip

@TODO: move these packages into hoot-repo so that they don't have to be built here.
RUN curl -fsSL -o /tmp/protobuf.tar.gz \
        https://github.com/protocolbuffers/protobuf/releases/download/v$protobuf_version/protobuf-cpp-$protobuf_version.tar.gz && \
    mkdir -p /tmp/protobuf-src /tmp/protobuf-build && \
    tar -xzf /tmp/protobuf.tar.gz -C /tmp/protobuf-src --strip-components=1 && \
    cmake -S /tmp/protobuf-src/cmake -B /tmp/protobuf-build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib64 \
        -Dprotobuf_BUILD_TESTS=OFF \
        -Dprotobuf_BUILD_SHARED_LIBS=ON && \
    cmake --build /tmp/protobuf-build -j$(nproc) && \
    cmake --install /tmp/protobuf-build && \
    ldconfig && \
    protoc --version && \
    rm -rf /tmp/protobuf.tar.gz /tmp/protobuf-src /tmp/protobuf-build

RUN curl -fsSL -o /tmp/stxxl.tar.gz \
        https://github.com/stxxl/stxxl/archive/refs/tags/$stxxl_version.tar.gz && \
    mkdir -p /tmp/stxxl-src /tmp/stxxl-build && \
    tar -xzf /tmp/stxxl.tar.gz -C /tmp/stxxl-src --strip-components=1 && \
    cmake -S /tmp/stxxl-src -B /tmp/stxxl-build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DINSTALL_LIB_DIR=/usr/lib64 \
        -DINSTALL_PKGCONFIG_DIR=/usr/lib64/pkgconfig \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_STATIC_LIBS=OFF \
        -DBUILD_TESTS=OFF \
        -DBUILD_EXAMPLES=OFF \
        -DBUILD_EXTRAS=OFF && \
    cmake --build /tmp/stxxl-build -j$(nproc) && \
    cmake --install /tmp/stxxl-build && \
    ldconfig && \
    rm -rf /tmp/stxxl.tar.gz /tmp/stxxl-src /tmp/stxxl-build

RUN curl -fsSL -o /tmp/libphonenumber.tar.gz \
        https://github.com/google/libphonenumber/archive/refs/tags/v$libphonenumber_version.tar.gz && \
    mkdir -p /tmp/libphonenumber-src /tmp/libphonenumber-build && \
    tar -xzf /tmp/libphonenumber.tar.gz -C /tmp/libphonenumber-src --strip-components=1 && \
    cmake -S /tmp/libphonenumber-src/cpp -B /tmp/libphonenumber-build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib64 \
        -DUSE_BOOST=OFF \
        -DUSE_STDMUTEX=ON \
        -DREGENERATE_METADATA=OFF && \
    cmake --build /tmp/libphonenumber-build -j$(nproc) && \
    cmake --install /tmp/libphonenumber-build && \
    ldconfig && \
    rm -rf /tmp/libphonenumber.tar.gz /tmp/libphonenumber-src /tmp/libphonenumber-build

RUN dnf -y remove postgresql || true && \
    dnf install -y --nogpgcheck \
        postgresql$postgresql_version \
        postgresql$postgresql_version-contrib \
        postgresql$postgresql_version-server \
        postgresql$postgresql_version-devel && \
    echo "/usr/pgsql-$postgresql_version/lib" > /etc/ld.so.conf.d/pgsql-$postgresql_version.conf && \
    ldconfig && \
    alternatives --install /usr/bin/createdb pgsql-createdb /usr/pgsql-$postgresql_version/bin/createdb 500 && \
    alternatives --install /usr/bin/createuser pgsql-createuser /usr/pgsql-$postgresql_version/bin/createuser 500 && \
    alternatives --install /usr/bin/pg_config pgsql-pg_config /usr/pgsql-$postgresql_version/bin/pg_config 500 && \
    alternatives --install /usr/bin/pg_isready pgsql-pg_isready /usr/pgsql-$postgresql_version/bin/pg_isready 500 && \
    alternatives --install /usr/bin/psql pgsql-psql /usr/pgsql-$postgresql_version/bin/psql 500 && \
    ln -sf /usr/pgsql-$postgresql_version/bin/createdb /usr/local/bin/createdb && \
    ln -sf /usr/pgsql-$postgresql_version/bin/createuser /usr/local/bin/createuser && \
    ln -sf /usr/pgsql-$postgresql_version/bin/pg_config /usr/local/bin/pg_config && \
    ln -sf /usr/pgsql-$postgresql_version/bin/pg_isready /usr/local/bin/pg_isready && \
    ln -sf /usr/pgsql-$postgresql_version/bin/psql /usr/local/bin/psql && \
    rpm -q gdal gdal-devel gdal-python-tools && \
    gdal-config --version

RUN groupadd --non-unique -g ${hoot_gid} ${hoot_group} && \
    useradd --no-log-init -d ${hoot_home} -m -s ${hoot_shell} -u ${hoot_uid} -g ${hoot_gid} ${hoot_user} && \
    chmod 0755 ${hoot_home}

ARG tomcat_config=/etc/tomcat8
ARG tomcat_logs=/var/log/tomcat8

# vars needed for core entrypoint
ENV DEVTOOLSET_VERSION=$devtoolset_version
ENV HOOT_USER=$hoot_user
ENV JDK_VERSION=$jdk_version
ENV PG_MAJOR_VERSION=$postgresql_version
ENV PATH=$PATH:/usr/pgsql-$postgresql_version/bin
ENV LD_LIBRARY_PATH=/usr/pgsql-$postgresql_version/lib:$LD_LIBRARY_PATH
ENV MANPATH=/opt/rh/devtoolset-$DEVTOOLSET_VERSION/root/usr/share/
ENV TOMCAT_CONFIG=$tomcat_config
ENV TOMCAT8_HOME=/var/lib/tomcat8
ENV TOMCAT_SERVER=$tomcat_config/server.xml

# services configuration files.
RUN echo -e '\
export GDAL_DATA=$GDAL_DATA\n\
export HOOT_HOME=$HOOT_HOME\n\
export HOOT_WORKING_NAME=hootenanny\n\
export JAVA_HOME=$JRE_HOME\n\
export LD_LIBRARY_PATH=/usr/pgsql-$postgresql_version/lib:$LD_LIBRARY_PATH:/usr/local/lib:$JAVA_HOME/lib/amd64/server:$HOOT_HOME/lib\n\
export PATH=$HOOT_HOME/bin:$PATH\n\
export JAVA_OPTS="${JAVA_OPTS} -Xdebug -Xrunjdwp:transport=dt_socket,address=8585,server=y,suspend=n"\n'\
>> $tomcat_config/conf.d/hoot.conf

RUN install -d -m 0775 $tomcat_logs
RUN echo '\n\
Please login to the host to view the logs:\n\
   sudo journalctl -u tomcat8\n\
EOF\n'\ >> $tomcat_logs/catalina.out

RUN chown $hoot_user:$hoot_user $tomcat_logs/catalina.out

COPY docker/scripts/tomcat_configure.sh /tmp
RUN /tmp/tomcat_configure.sh && rm -f /tmp/tomcat_configure.sh

# let hoot user execute tomcat8 commands
RUN usermod -a -G tomcat $hoot_user

COPY docker/scripts/core-services-entrypoint.sh /docker-entrypoint.sh
COPY docker/scripts/core-services-healthcheck.sh /docker-healthcheck.sh

WORKDIR ${hoot_home}
USER ${hoot_user}
ENTRYPOINT /docker-entrypoint.sh
HEALTHCHECK --interval=15s --start-period=1m CMD ["/docker-healthcheck.sh"]
