FROM rockylinux:9

ARG hoot_user
ARG hoot_uid
ARG hoot_gid
ARG hoot_group
ARG hoot_shell=/bin/bash
ARG hoot_home
ARG node_version
ARG npm_version

ENV HOOT_HOME=$hoot_home

RUN dnf -y module enable nodejs:${node_version%%.*} && \
    dnf -y makecache

RUN dnf -y install \
        bzip2 \
        git \
        git-core \
        nodejs-$node_version \
        nodejs-devel-$node_version \
        npm-$npm_version && \
    dnf -y install \
        https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm && \
    dnf -y clean all && \
    rm -rf /var/cache/dnf

RUN groupadd --non-unique -g ${hoot_gid} ${hoot_group} && \
    useradd --no-log-init -d ${hoot_home} -m -s ${hoot_shell} -u ${hoot_uid} -g ${hoot_gid} ${hoot_user} && \
    chmod 0755 ${hoot_home}

COPY docker/scripts/frontend-entrypoint.sh /docker-entrypoint.sh
COPY docker/scripts/frontend-healthcheck.sh /docker-healthcheck.sh

USER ${hoot_user}
WORKDIR ${hoot_home}/hoot-ui-2x
ENTRYPOINT /docker-entrypoint.sh
HEALTHCHECK --interval=15s --start-period=1m CMD ["/docker-healthcheck.sh"]
