ARG postgres_server_version=16
FROM postgres:${postgres_server_version}-bookworm

ARG pgdata=/var/lib/postgresql/data

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PGDATA=${pgdata}

COPY docker/scripts/postgres-initdb.sh /docker-entrypoint-initdb.d/10-postgres-initdb.sh
COPY docker/scripts/postgres-entrypoint.sh /docker-entrypoint.sh
COPY docker/scripts/postgres-healthcheck.sh /docker-healthcheck.sh

RUN chmod 0755 /docker-entrypoint-initdb.d/10-postgres-initdb.sh \
               /docker-entrypoint.sh \
               /docker-healthcheck.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 5432/tcp
HEALTHCHECK --interval=15s CMD ["/docker-healthcheck.sh"]
CMD ["postgres"]
VOLUME ${pgdata}
