# Use Rocky Linux 9 as the base image (EL9 compatible)
FROM rockylinux:9

ARG hoot_user
ARG hoot_uid
ARG hoot_gid
ARG hoot_group
ARG hoot_shell=/bin/bash
ARG hoot_home
ARG glpk_version
ARG liboauthcpp_version
ARG libphonenumber_version
ARG libpostal_version
ARG node_version
ARG npm_version
ARG v8_version
ARG stxxl_version
ARG armadillo_version
ARG gdal_version
ARG geos_version
ARG libgeotiff_version
ARG proj_version
ARG stxxl_version
ARG postgresql_version
ARG jdk_version
ARG google_chrome_version


ENV HOOT_HOME=$hoot_home

# Install glibc-langpack-en for locale support and dnf-plugins-core
RUN dnf install -y glibc-langpack-en dnf-plugins-core && dnf clean all

COPY scripts/yum/geoint-repo.sh scripts/yum/pgdg-repo.sh /tmp/

# Configure repositories for EL9
# NOTE: hoot-repo.sh is temporarily disabled because EL9 packages are not yet available in S3
# TODO: Re-enable once https://hoot-repo.s3.amazonaws.com/el9/deps/stable/ is populated
RUN /tmp/geoint-repo.sh && \
    /tmp/pgdg-repo.sh $postgresql_version && \
    dnf config-manager --save \
        --setopt=baseos.repo_gpgcheck=1 \
        --setopt=appstream.repo_gpgcheck=1 &> /dev/null

# Install EPEL repository (no centos-release-scl needed on EL9)
RUN dnf -y install epel-release

# Install versioned dependencies (no devtoolset needed on EL9 - GCC 11 is default)
RUN dnf install -y \
        armadillo-$armadillo_version \
        geos-$geos_version \
        geos-devel-$geos_version \
        glpk-$glpk_version \
        glpk-devel-$glpk_version \
        gdal-$gdal_version \
        gdal-devel-$gdal_version \
        gdal-python-tools-$gdal_version \
        google-chrome-stable-$google_chrome_version \
        libgeotiff-$libgeotiff_version \
        libgeotiff-devel-$libgeotiff_version \
        liboauthcpp-$liboauthcpp_version \
        liboauthcpp-devel-$liboauthcpp_version \
        libphonenumber-$libphonenumber_version \
        libphonenumber-devel-$libphonenumber_version \
        libpostal-$libpostal_version \
        libpostal-data-$libpostal_version \
        libpostal-devel-$libpostal_version \
        npm-$npm_version \
        nodejs-$node_version \
        nodejs-devel-$node_version \
        nodejs-docs-$node_version \
        nodejs-libs-$node_version \
        postgresql$postgresql_version \
        postgresql$postgresql_version-contrib \
        postgresql$postgresql_version-server \
        proj-$proj_version \
        proj-devel-$proj_version \
        stxxl-$stxxl_version \
        stxxl-devel-$stxxl_version \
        v8-devel-$v8_version

# Install general dependencies (EL9 changes: no python/python-devel, tomcat9 instead of tomcat8)
RUN dnf -y install \
        asciidoc \
        autoconf \
        autoconf-archive \
        automake \
        bison \
        boost-devel \
        bzip2 \
        ccache \
        cmake \
        cppunit-devel \
        dblatex \
        doxygen \
        gcc-c++ \
        git \
        git-core \
        gnuplot \
        lcov \
        libffi-devel \
        libicu-devel \
        libpng-devel \
        libtool \
        liquibase \
        maven \
        m4 \
        mlocate \
        opencv \
        opencv-core \
        opencv-devel \
        osmosis \
        java-$jdk_version-openjdk \
        java-$jdk_version-openjdk-devel \
        perl-XML-LibXML \
        parallel \
        make \
        protobuf \
        protobuf-compiler \
        protobuf-devel \
        python3 \
        python3-devel \
        python3-matplotlib \
        python3-pip \
        python3-setuptools \
        qt5-qtbase \
        qt5-qtbase-devel \
        qt5-qtbase-postgresql \
        qt5-qtwebkit \
        qt5-qtwebkit-devel \
        readline-devel \
        sqlite-devel \
        swig \
        texlive \
        texlive-collection-fontsrecommended \
        texlive-collection-langcyrillic \
        tomcat9 \
        unzip \
        vim \
        w3m \
        wget \
        words \
        xorg-x11-server-Xvfb \
        zip

RUN dnf install -y postgresql$postgresql_version-devel && \
    alternatives --install /usr/bin/pg_config pgsql-pg_config /usr/pgsql-$postgresql_version/bin/pg_config 500

RUN groupadd --non-unique -g ${hoot_gid} ${hoot_group} && \
    useradd -d ${hoot_home} -m -s ${hoot_shell} -u ${hoot_uid} -g ${hoot_gid} ${hoot_user} && \
    chmod 0755 ${hoot_home}

# EL9 uses Tomcat 9 instead of Tomcat 8
ARG tomcat_config=/etc/tomcat9
ARG tomcat_logs=/var/log/tomcat9

# vars needed for core entrypoint (no DEVTOOLSET_VERSION needed on EL9)
ENV HOOT_USER=$hoot_user
ENV PG_MAJOR_VERSION=$postgresql_version
ENV PATH=$PATH:/usr/pgsql-$postgresql_version/bin
ENV TOMCAT_CONFIG=$tomcat_config
ENV TOMCAT9_HOME=/var/lib/tomcat9
ENV TOMCAT_SERVER=$tomcat_config/server.xml

# services configuration files.
# EL9 Java 11 uses lib/server instead of lib/amd64/server
RUN echo -e '\
export GDAL_DATA=$GDAL_DATA\n\
export HOOT_HOME=$HOOT_HOME\n\
export HOOT_WORKING_NAME=hootenanny\n\
export JAVA_HOME=$JRE_HOME\n\
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:$JAVA_HOME/lib/server:$HOOT_HOME/lib\n\
export PATH=$HOOT_HOME/bin:$PATH\n\
export JAVA_OPTS="${JAVA_OPTS} -Xdebug -Xrunjdwp:transport=dt_socket,address=8585,server=y,suspend=n"\n'\
>> $tomcat_config/conf.d/hoot.conf

RUN install -d -m 0775 $tomcat_logs
RUN echo '\n\
Please login to the host to view the logs:\n\
   sudo journalctl -u tomcat9\n\
EOF\n'\ >> $tomcat_logs/catalina.out

RUN chown $hoot_user:$hoot_user $tomcat_logs/catalina.out

COPY docker/scripts/tomcat_configure.sh /tmp
RUN /tmp/tomcat_configure.sh && rm -f /tmp/tomcat_configure.sh

# let hoot user execute tomcat9 commands
RUN usermod -a -G tomcat $hoot_user

COPY docker/scripts/core-services-entrypoint.sh /docker-entrypoint.sh
COPY docker/scripts/core-services-healthcheck.sh /docker-healthcheck.sh

WORKDIR ${hoot_home}
USER ${hoot_user}
ENTRYPOINT /docker-entrypoint.sh
HEALTHCHECK --interval=15s --start-period=1m CMD ["/docker-healthcheck.sh"]
