
[[AreaToAreaConflationAlgs]]
=== Area To Area Conflation

[[AreaToAreaDefinitions]]
==== Feature Definitions

Area Conflation defines an area as non-building linear or polygonal feature whose tags support the 
definitions of an area used by OpenStreetMap. Buildings are excluded in order to prevent match 
overlap with Building Conflation.

[[AreaToAreaMatching]]
==== Matching

Area matching uses a manually configured search radius when determining the maximum distance between 
features to search during matching.

Matching is based off both tag and geometric attributes. For geometry matching, angle histogram, 
edge distance, buffered overlap, and smaller overlap values are used for comparison. Their match 
thresholds were determined against test data using Weka. Tag matching looks at type tags on features 
only. Matching employs additional logic to help ensure a review is generated when a one to many 
match occurs.

[[AreaToAreaMerging]]
==== Merging

Area merging uses a simple merging process where a geometry from only one of the features is kept 
(conflation workflow dependent) and tags are merged based on the configured tag merging strategy.

[[AreaToAreaConfigurableOptions]]
==== Configurable Options

See the descriptions for configuration options named `area.*` for more information on how 
Area Conflation behavior may be modified.

[[AreaToAreaTestResults]]
==== Test Results

Match truth for several datasets was obtained by having a human manual match features
(see https://github.com/ngageoint/hootenanny/files/595245/Hootenanny.-.Manual.Matching.9-13-16.pptx 
for more details on the process involved). Then, Hootenanny conflated the same data and scored how 
many matches it correctly made.

TODO: finish

[[AreaToAreaFutureWork]]
==== Future Work

Area Conflation needs to be trained on additional datasets to improve its quality.

