
[[Building-to-POI-Conflation]]
== Building to POI Conflation
  

Building to POI conflation is in very early development and disabled by default. For information on configuring building to POI conflation please Hootenanny.Help@digitalglobe.com.


[[Matching]]
=== Matching
  

Building to POI conflation in Hootenanny is a rule based conflation based on the following rules:

* Find all candidate POI / building pairs. A candidate is any POI that is within the combined circular error of a building plus the user definable +poi.polygon.match.review.distance+ config option. (see below for the combined circular error calculation)
* Assign Match: If the POI is inside the building and the name is either non-existant or a close match
* Assign Review: If the POI is inside the building and the name is not a close match
* Assign Review: If the POI is close to the building and the name is a close match
* Assign Miss: Everything else

Unlike many of the matching routines intra-data set matches are allowed. This resolves issues that commonly occur in data sets where buildings are duplicated in a POI layer.

The circular error (CE) of the two input elements is assumed to be that we are 95% CE for each feature. To combine the two values together into a single value that represents the 95% confidence that they're within that distance is:

------
sigma1 = CE1 / 2
sigma2 = CE2 / 2
combined CE = sqrt(sigma1 * sigma1 + sigma2 * sigma2) * 2
------

[[Merging]]
=== Merging
  

Once a relationship has been established between elements a graph is created to determine any interdependencies. If a single element is involved in multiple matches then all the elements involved in that set of matches are marked as needing review. This avoids complex situations where there are multiple conflicting POI attributes.

However, if a review relationship is found and a match relationship is found, the review relationship is not included in the interdependence calculation. So, you may have a POI merged with one building, but marked as needing review with another building. Modifying this business logic will require some user input on the desired functionality as well as some not so insignificant internal changes.

If a merge is warranted, the geometry of the building is used and the tags are merged using the default tag merging mechanism ( +tag.merger.default+ configuration key).


[[Enabled-POI-to-Building]]
=== Enabled POI to Building
  

As mentioned above, please send an email to Hootenanny.Help@digitalglobe.com for any questions on including this functionality in the application. Once included it can be enabled with:

------
hoot --unify -D match.creators=hoot::PoiPolygonMatchCreator \
  -D merger.creators=hoot::PoiPolygonMergerCreator in1.osm in2.osm out.osm
------


[[Configurable-Options]]
=== Configurable Options
  

There are two configurable options to the Building to POI conflation:

*  +poi.polygon.match.review.distance+ - How far away from a polygon should name matches be considered reviews. This is a fixed value in meters that is added to the combined CE.
*  +poi.polygon.match.name.threshold+ - If the name similarity score is greater than this then the names are considered a match. Scores are 0 to 1 for similarity and -1 if there are no names present (null).

