
[[RailwayConflationAlgs]]
=== Railway Conflation

[[RailwayFeatureDefinitions]]
==== Feature Definitions

Railway Conflation defines a railway as a linear railway feature whose tags support the definitions 
used by OpenStreetMap.

[[RailwayMatching]]
==== Matching

Railway matching allows for a manually configured search radius when determining the maximum 
distance between features to search during matching.

Matching is based off both tag and geometric attributes. For geometry matching, distance score, 
Hausdorff Distance, and edge distance values are used for comparison. Their match thresholds were
determined against test data using Weka. Tag matching looks at type tags on features only.

===== One to Many Matching

Railway conflation has an alternate workflow that allows for transferring selected tags from single 
rail features in secondary data to multiple rail features in reference data when the single 
secondary rail identifies how many tracks it represents. The configuration option that determines
which attributes identify the track count is `railway.one.to.many.identifying.keys`. Any secondary
feature that has at least one tag key with the keys from that option will be eligible for one to 
many matching. Once such a feature is identified, a record is kept of how many matches it is 
involved in with other reference rail features. Once that match limit is reached, no more matching
will occur for the secondary feature.

[[RailwayMerging]]
==== Merging

Default railway merging uses the standard Hootenanny merging process that is used for merging most
linear features, including roads.

===== One to Many Merging

In the one to many workflow, selected tags are transferred from one secondary feature to potentially 
multiple reference features. No geometry merging is performed. The tags transferred are configurable
via the `railway.one.to.many.transfer.keys` configuration option where any tag in the secondary 
feature with key matching those in the option list value will be transferred to a matching reference 
feature. Optionally, the secondary feature may be deleted from conflated output by specifying `railway.one.to.many.delete.secondary=true`.

[[RailwayConfigurableOptions]]
==== Configurable Options

See the descriptions for configuration options named `railway.*` for more information on how Railway 
Conflation behavior may be modified.

[[RailwayTestResults]]
==== Test Results

Match truth for several datasets was obtained by having a human manual match features
(see https://github.com/ngageoint/hootenanny/files/595245/Hootenanny.-.Manual.Matching.9-13-16.pptx 
for more details on the process involved). Then, Hootenanny conflated the same data and scored how 
many matches it correctly made.

TODO: finish

[[RailwayFutureWork]]
==== Future Work

Railway Conflation needs to be trained on additional datasets to improve its quality.

