
[[HootConfiguringOsmApiDatabaseConflation]]
== Configuring an OSM API Database Connection

By default, Hootenanny is configured with an empty test OSM API database.  To conflate against your own OSM API database:

* Create a custom OSM API database configuration file $HOOT_HOME/conf/DatabaseConfigLocal.sh by copying the file 
$HOOT_HOME/conf/DatabaseConfigDefault.sh
* Fill in the following settings with your production OSM API database information:
** database server name: DB_HOST_OSMAPI
** database name: DB_NAME_OSMAPI
** database port: DB_PORT_OSMAPI
** database username for conflating data: DB_USER_OSMAPI
** database password: DB_PASSWORD_OSMAPI

Alternatively, if you want to disable OSM API database conflation completely, add the following line to your services local.conf file:

osmApiDbEnabled=false

WARNING: If you are running Hootenanny inside Vagrant, there is a risk that your configured OSM API database can be deleted when re-installing Hootenanny.  A fix will be available in: https://github.com/ngageoint/hootenanny/issues/812.
