
[[fullinstall]]
== Full Install

This document describes the steps for installing Hootenanny on a CentOS/RHEL 6.x system, including all of 
its dependencies.  It has been tested on CentOS 6.5/6.6.  To install Hootenanny:

------------------------------
# HOOT_VERSION is of the form X.Y.Z and corresponds to a release available at 
# http://github.com/ngageoint/hootenanny.

HOOT_VERSION=X.Y.Z

wget https://github.com/ngageoint/hootenanny/releases/download/v$HOOT_VERSION/hootenanny-$HOOT_VERSION.tar.gz
tar -xzf hootenanny-$HOOT_VERSION.tar.gz

# Follow the instructions to configure the installation script at 
# hootenanny-$HOOT_VERSION/scripts/InstallHoot-CentOS-RHEL.sh.  You may configure the script to 
# install all Hootenanny dependencies, as well as the application or have it just install the 
# Hootenanny application.  The dependencies must be installed at least once to the target environment.

./InstallHoot-CentOS-RHEL.sh
------------------------------

For additional details on configuring the database connection pool, see <<HootDBConnectionPool>>.

== Test Bandwidth (optional)

If you're on a new server and want a rudimentary test for bandwidth then do the following:

--------------------------------------
cd /var/lib/tomcat6/webapps
sudo fallocate -l 100M dum.txt
sudo chmod 777 dum.txt
--------------------------------------

Then try downloading the file created e.g. http://myhost/dum.txt

. Completely clear your browser history.

. Browse to http://localhost/hootenanny-id (replace localhost with the Hootenanny server name) to verify the web application is available and the base map is visible.

. Click on the "Hootenanny | Innovision" logo.  You should see version information displayed for the Hootenanny core, services, and user interface.  The version numbers should all match each other and should also match the version you installed.

NOTE: If client-side debugging becomes necessary, the "Developer Tools" in Chrome can be used.  See <<HootUITroubleshoot,UI Troubleshooting>> for additional information.

. You may need to build up a tile cache for your AOI by zooming to the desired area and pausing for awhile to wait for the tiles to load before attempting to conflate with Hootenanny to avoid overtaxing your web browser with open tile requests.

== Ingest Data (optional)

If you have a small amount of data to ingest, you can easily do it from within the Hootenanny UI using the "Add Dataset" feature. If you have a large number of files you would like to script for ingest at one time, you may do it with repeated call something like the following:

--------------------------------------
#adjust email accordingly; setting not needed if already set in conf/hoot.json during build
hoot convert -D services.db.write.email='test@test.com' /myData.osm postgresql://hoot:hoottest@localhost:5432/hoot/myMap

--------------------------------------

== Configure the Base Map List

To manually configure the available base maps shown in the iD editor:

. Edit +$HOOT_HOME/hoot-ui/data/imagery.json+
. Add or remove JSON entries to edit the base maps.  At a minimum, you must:
.. specify a unique ID for the layer in the "id" attribute
.. specify a name for the base map in the "name" attribute
.. specify a min and max scale extent for the base map that defines at what zoom level range it will be visible in the "scaleExtent" attribute
.. specify whether the base map should be selected by default by setting the "default" attribute to "true" or "false

== Helpful Hints

. You can also add a custom base map quickly to the Hootenanny UI, without having to edit Javascript code if that is more convenient, but the base map will not be retained in the base maps list between browser refreshes (a bug). To add a custom basemap:

.. From the right hand menu in iD, click "Custom".
.. Add the URL for the basemap you wish to use.

. If you want to define a starting AOI for your maps, so you begin in the same location every time you open the browser, modify the "hoot.center" variable in +/var/lib/tomcat6/webapps/WEB-INF/hootenanny-id/hoot/js/custom/hoot.js+.

. You can quickly zoom to an AOI by modifying the end of the browser URL. The parts you modify are of the form /[zoom]/[longitude]/[latitude].
