== Overview

This document describes how to install Hootenanny.  Hootenanny is supported on CentOS 7.x.  Both an RPM package and a virtual machine
are provided.

== Environment

* Hardware specs may vary. Hootenanny has been successfully installed on VMs. Some suggested specifications:
	** At least 8GB of RAM, but you can certainly run small datasets on far less.	
	** Quad core or greater Intel x86 64bit compatible processor
* An installation of CentOS/RHEL 7 64bit with a working yum repository or access to downloadable installable RPM's.
* A client machine with the Chrome (or Chromium) browser installed. Hootenanny is only supported in Chrome.

== Virtual Machine Instructions

See VAGRANT.md

[[fullinstall]]
== CentOS/RHEL RPM Install Instructions

The recommended and easiest installation method is to install from RPMs.  This can be accomplished by performing the following steps:

. Create the following file: +/etc/yum.repos.d/hoot.repo+
. Add the following content to the file:
+
--------------------------------------
[hoot]
name=hoot
baseurl=https://s3.amazonaws.com/hoot-rpms/stable/el6/
gpgcheck=0
--------------------------------------
. Run the following:
+
--------------------------------------
sudo yum update
sudo yum install hootenanny-autostart
--------------------------------------

`scripts/InstallHoot-CentOS-RHEL.sh` may also be used to install.  This script requires custom 
configuration as described within it.  It may require updating if you have installed certain Hootenanny 
dependencies (Tomcat, Postgres, etc.) with non-standard methods.  It also may require that certain file 
and directory permissions be relaxed within your the target environment.

For additional details on configuring the database connection pool, see <<HootDBConnectionPool>>.

== Hootenanny Package Descriptions

The following instructions assumed you have used the Hootenanny build process to already have generated the following files:

* The Hootenanny core and UI source archive (hootenanny-X.Y.Z.tar.gz)
** The hoot core code is written in C++ and is to be packaged in a source archive (tar.gz) on a build machine during the release process. The source archive will be then compiled on the target installation machine.
** The hoot UI code is in Javascript and is packaged inside of the same source archive that the hoot core code is packaged in a directory named "hoot-id". The directory is to be manually copied to the web server on the target installation machine.
* The Hootenanny services web archive (hootenanny-services-X.Y.Z.war) files
** The hoot services code is in Java and is compiled on a build machine and packaged into a web archive (.war) file as a result of the release process. The war file is then deployed to the web server on the target installation machine.
* The FOUO translations archive (hootenanny-translations.tar.gz), which are only available through official channels.

== Helpful Hints

. You can also add a custom base map quickly to the Hootenanny UI, without having to edit Javascript code if that is more convenient, but the base map will not be retained in the base maps list between browser refreshes (a bug). To add a custom basemap:

.. From the right hand menu in iD, click "Custom".
.. Add the URL for the basemap you wish to use.

. If you want to define a starting AOI for your maps, so you begin in the same location every time you open the browser, modify the "hoot.center" variable in +/var/lib/tomcat8/webapps/WEB-INF/hootenanny-id/hoot/js/custom/hoot.js+.

. You can quickly zoom to an AOI by modifying the end of the browser URL. The parts you modify are of the form /[zoom]/[longitude]/[latitude].

== Advanced Tasks

=== Test Bandwidth (optional)

If you're on a new server and want a rudimentary test for bandwidth then do the following:

--------------------------------------
cd /var/lib/tomcat8/webapps
sudo fallocate -l 100M dum.txt
sudo chmod 777 dum.txt
--------------------------------------

Then try downloading the file created e.g. http://myhost/dum.txt

. Completely clear your browser history.

. Browse to http://localhost/hootenanny-id (replace localhost with the Hootenanny server name) to verify the web application is available and the base map is visible.

. Click on the "Hootenanny | Innovision" logo.  You should see version information displayed for the Hootenanny core, services, and user interface.  The version numbers should all match each other and should also match the version you installed.

NOTE: If client-side debugging becomes necessary, the "Developer Tools" in Chrome can be used.  See <<HootUITroubleshoot,UI Troubleshooting>> for additional information.

. You may need to build up a tile cache for your AOI by zooming to the desired area and pausing for awhile to wait for the tiles to load before attempting to conflate with Hootenanny to avoid overtaxing your web browser with open tile requests.

=== Ingest Data (optional)

If you have a small amount of data to ingest, you can easily do it from within the Hootenanny UI using the "Add Dataset" feature. If you have a large number of files you would like to script for ingest at one time, you may do it with repeated call something like the following:

--------------------------------------
#adjust email accordingly; setting not needed if already set in conf/hoot.json during build
hoot convert -D services.db.write.email='test@test.com' /myData.osm postgresql://hoot:hoottest@localhost:5432/hoot/myMap

--------------------------------------

=== Configure the Base Map List

To manually configure the available base maps shown in the iD editor:

. Edit +$HOOT_HOME/hoot-ui/data/imagery.json+
. Add or remove JSON entries to edit the base maps.  At a minimum, you must:
.. specify a unique ID for the layer in the "id" attribute
.. specify a name for the base map in the "name" attribute
.. specify a min and max scale extent for the base map that defines at what zoom level range it will be visible in the "scaleExtent" attribute
.. specify whether the base map should be selected by default by setting the "default" attribute to "true" or "false

