
[[HootInstallTroubleshooting]]
== Troubleshooting
=== Core

* *You cannot resolve any Hootenanny commands by typing 'hoot' at the command line?* --> Hootenanny Core has been installed incorrectly by the InstallHoot.sh script.  The script is designed to clear existing
Hootenanny installations from the install target path when run, but its possible this did not occur.  The following commands will completely clean Hootenanny core from the system (paths are dependent upon the
settings used in the UpdateHoot-CentOS6.sh script):
	** sudo rm -rf $HOOT_CORE_INSTALL_DIR/hootenanny-$NEW_VERSION
	** sudo rm -f $HOOT_CORE_INSTALL_DIR/hoot 
	** sudo rm -f $HOOT_CORE_INSTALL_DIR/bin/hoot

* *Don't think the correct version of Hootenanny core is installed?* --> You can check the version of the core by clicking on the "Hootenanny | Innovision" logo from within the UI.  Or as a sanity check, type 'hoot --version' from the command line.  The version displayed should match the version you installed.  Finally, the core version used by the services can be found by navigating to the following URLs:
	** +http://localhost/hoot-services/info/about/coreVersionInfo+
	** +http://localhost/hoot-services/info/about/coreVersionDetail+

* *qmake step fails during hoot compilation?* --> Do you have QT_HOME/bin on your path?

* *Not sure if hoot is using the correct version of a dependency library?* --> run: +ldd /usr/local/bin/hoot.bin+ to see a list of the libraries its using. You can use +yum list installed | grep <library name>+ to see the libraries installed on your system.

* *Problems reading/writing from the database when using hoot?* --> Verify the database credentials in:
	**  +/usr/local/hootenanny-X.Y.Z/conf/database/DatabaseConfigLocal.sh+
	**  +/usr/local/hootenanny-X.Y.Z/conf/database/DatabaseConfigDefault.sh+

* *"PostgreSQL" and "FileGDB" formats do not show when running ogrinfo --formats* --> Possibly you have compiled GDAL incorrectly. Re-compile with the steps listed in INSTALL-CentOS6.5-PG9.1.txt that were run during the hoot core installation.

* *Problems with the GDAL Python module?* --> Make sure you compiled GDAL with the +--with-python+ switch.

* *Problems with gdal2tiles.py?* --> You may be able to solve this problem by modifying the GDAL2TILES property in +$HOOT_HOME/scripts/makerastertotiles+ by providing it with the full path to gdal2tiles.py (usually in +/usr/local/bin+ or +/usr/local/gdal<version>/swig/python/scripts+ ).

* *Getting a compiler failure when compiling Hoot core?* --> g++ fails with a non-descript error? Its not known what causes this yet, but its very bad and has happened a few times now. First, be sure you've done a make uninstall on the previous version of Hoot and go ahead and do a make uninstall on the version you're trying to compile. Its also possible you have a bad release, in which case a new one should be built.

=== Database

* *Unable to use PSQL?* --> Is the PSQL executable on your path?

* *Problems updating the hoot database schema?* --> Verify that the owner listed in the script is "hoot" throughout for all the hoot database tables. If not replace the text "OWNER TO <other-owner> with "OWNER TO hoot".

* *Unable to delete one of the databases?* --> try (from link:$$http://stackoverflow.com/questions/11388786/how-does-one-drop-a-template-database-from-postgresql$$[here]):

--------------------------------------
psql -U hoot
postgres=# UPDATE pg_database SET datistemplate='false' WHERE datname='database name';
UPDATE 1
postgres=# DROP DATABASE database name;
DROP DATABASE
--------------------------------------

OR

--------------------------------------
# check and see if anything is holding onto the database
SELECT * FROM pg_stat_activity WHERE datname='database name';
dropdb 'database name'
--------------------------------------

* *Want to clear data out of the hoot database?* -->

--------------------------------------
export HOOT_HOME=/usr/local/hoot
$HOOT_HOME/scripts/database/DeleteAllTables.sh
--------------------------------------

To re-create the hoot database, run the UpdateHoot-CentOS6.sh script with only the +UPDATE_DATABASE+ variable set to "true".

* *When using PSQL, asked for a password for a database (rather than for a user) and don't have it?* --> Possibly, you have authentication still set to MD5 in the pg_hba.conf file. Temporarily set unset if from MD5 (see Postgres install steps) to use PSQL. Set it back to MD5 when you've finished using PSQL.

* *Not sure if the Postgis extension has been installed properly?*-->
	** Check to see if following table exists in +wfsstoredb:spatial_ref_sys+

* *liquibase update fails to run on the hoot database?*-->
	** The update will fail if you do not reference the path to the changelog files in exactly the same way the hoot database references them in the databasechangelog table. If they are referenced from a different path, then you will lose all your data. As a last resort if the liquibase update does not work, you can run the $HOOT_HOME/database/DeleteAllTables.sh script and then re-create the tables with $HOOT_HOME/DbSchema.sql. You will lose all existing data with this method.

* *Getting a change log lock error?* -->

Delete all change log locks:
--------------------------------------
psql -U hoot
delete from databasechangeloglock *;
--------------------------------------

=== Firewall

*Trouble accessing Tomcat?* --> Compare your +/etc/sysconfig/iptables+ with this working version. Sometimes I have to move the "-A INPUT -j REJECT --reject-with icmp-host-prohibited" line below the "--dport 8080" line. I haven't spent the time to figure out how to fix this on the command line.

--------------------------------------
# Generated by iptables-save v1.4.7 on Tue Apr 29 10:42:18 2014
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080
-A OUTPUT -d 127.0.0.0/8 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080
COMMIT
# Completed on Tue Apr 29 10:42:18 2014
# Generated by iptables-save v1.4.7 on Tue Apr 29 10:42:18 2014
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [12:2304]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
# Completed on Tue Apr 29 10:42:18 2014
--------------------------------------

=== Services

* *WAR files will not deploy?* --> If your Tomcat instance is not set up to automatically deploy WAR files for some reason, then you will need to restart Tomcat to extract the WAR contents to a folder before setting permissions on them.
* *Need to monitor the Tomcat log for errors?* -->
--------------------------------------
tail -f /var/log/tomcat8/catalina.out | grep -i -e ERROR -e SEVERE
--------------------------------------

* *Not sure the correct version of Hootenanny services are deployed?* --> You can check the version of the core by clicking on the "Hootenanny | Innovision| logo from within the UI.  Or as a sanity check, verify the services version by navigating to the following URLs:
	** +http://localhost/hoot-services/info/about/servicesVersionInfo+
	** +http://localhost/hoot-services/info/about/servicesVersionDetail+

* *Can't hit the service URL's above?* --> The install script should handle this installation correctly, but perhaps the Hootenanny web application was installed to the incorrect location.  It should exist at: /var/lib/tomcat8/webapps/hoot-services .  Although UpdateHoot-CentOS6.sh will clean out any previously existing Hootenanny web applications, as a manual alternative, the following commands will clean out any previously existing
installations:
	** sudo rm -f /var/lib/tomcat8/webapps/hoot*-services*.war
	** sudo rm -rf /var/lib/tomcat8/webapps/hoot*-services*

* *Do you want to see more granular services log output or redirect it to a file?* --> Edit +/var/lib/tomcat8/webapps/hoot-services/WEB-INF/class/log4j.xml+ . See the log4j documentation for details on how to edit the file. Restart Tomcat after any changes made to the file.

* *Problems reading/writing from the database when using hoot?* --> Verify the database credentials in:
	**  +$HOOT_HOME/conf/database/DatabaseConfigLocal.sh+
	**  +$HOOT_HOME/conf/database/DatabaseConfigDefault.sh+
	**  +/var/lib/tomcat8/webapps/hoot-services/WEB-INF/classes/db/spring-database.xml+
	**  +/var/lib/tomcat8/webapps/hoot-services/WEB-INF/classes/conf/hoot-services.conf+
	**  +/var/lib/tomcat8/webapps/hoot-services/WEB-INF/workspace/jdbc/WFS_Connection.xml+
	** Also, verify +/var/lib/tomcat8/webapps/hoot-services/WEB-INF/classes/db/spring-database.xml+
		. maxActive=90
		. maxIdle=30
	** Also, verify +/var/lib/tomcat8/webapps/hoot-services/WEB-INF/workspace+ has read and write permission so it can create WFS store config xml files.

* *Having problems with the WFS?* -->
	** Verify wfsstoredb has been properly set up (see database troubleshooting section).
	** Check +/var/lib/tomcat8/webapps/hoot-services/WEB-INF/workspace/jdbc/WFS_Connection.xml+
	** Verify +/var/lib/tomcat8/webapps/hoot-services/WEB-INF/workspace+ has had its permissions set correctly.

* *Seeing this WFS error?* -->

--------------------------------------
2014-09-11 10:26:27 ERROR AbstractResourceManager:268 - Could not create resource web services: Error initializing WFS/FeatureStores: Cannot add feature store 'ex_601e0eb1bb994c3c949ddbed78424c6b': no such feature store has been configured.
2014-09-11 10:26:27 ERROR AbstractResourceManager:270 - Cause was: Cannot add feature store 'ex_601e0eb1bb994c3c949ddbed78424c6b': no such feature store has been configured.
--------------------------------------

You're seeing expired WFS links. To remove them:

--------------------------------------
cd /var/lib/tomcat8/webapps/hoot-services/WEB-INF/workspace
sudo rm -f datasources/feature/ex_*.xml 
sudo rm -f datasources/feature/*.properties
sudo rm -f services/ex_*.xml
--------------------------------------

* *Seeing this error: "--ogr2osm Unable to open /path/to/file.shp"* --> Possibly you do not have the Postgres extension installed for GDAL. See related troubleshooting tip in the "Core" section.

[[HootUITroubleshoot]]
=== UI

* *Not sure the correct version of the user interface is installed?* --> You can check the version of the user interface by clicking on the "Hootenanny | Innovision| logo from within the UI.

* *Trouble seeing your base map?* -->
	** In +/var/lib/tomcat8/webapps/hootenanny-id/data/imagery.json+ , verify that the base map URLs for all your layers are correct.
	** You may also need to tweak the "source.url" variable in +/var/lib/tomcat8/webapps/hootenanny-id/js/id/renderer/background_source.js+ depending on how the base maps are to be parsed. Make sure the url produced by iD.BackgroundSource. <your layer> function is correct by cut and pasting the url on browser and see if that returns image.
	** If changes are made to the imagery.json file, always then clear the browser history, close the browser, and open a new browser pointed to the Hootenanny UI application.
