== Overview

TODO: I believe these instructions are obsolete.

This document describes how to install Hootenanny in a CentOS/RHEL Environment.

=== Environment

* Hardware specs may vary. Hootenanny has been successfully installed on VMs. Some suggested specifications:
	** At least 8GB of RAM
	** Quad core or greater Intel x86 64bit compatible processor
	** 50GB of free space.
* An installation of CentOS/RHEL 6.x 64bit with a working yum repository or access to downloadable installable RPM's.
* A client machine with the Chrome (or Chromium) browser installed. Hootenanny is only supported in Chrome.
* Preferred Environment: Amazon AWS
* Amazon AWS Security Groups is set up to allow communication between ports for the Hootenanny application to function.
    Security Group Setup Required for Hootenanny:
        ** Custom TCP Rule - Port Range: 8096 = P2P Server Port
        ** Custom TCP Rule - Port Range: 8080 = Tomcat Web Server Port
        ** Custom TCP Rule - Port Range: 8094 = Translation Server
        ** Port TCP Rule   - Port Range: 22 = SSH into the server

== CentOS/ RHEL Install Instructions

This section describes the steps for installing Hootenanny on a CentOS/RHEL 6.5 system.
 
Any modifications to the versions and package dependencies listed in the installation script 
are not recommended, as parts of Hootenanny are very sensitive to its software dependency versions.
If a package has already been installed but does not match the expected version, your install will 
likely be unsupported. In such situations, the behavior of Hootenanny may range from inability to 
compile code, to unexpected or severe runtime results that result in a failed install.

These instructions have been tested on CentOS and Red Hat 6.5 ONLY.

--------------------------------------
** IMPORTANT: script must be execute as "root" user. **
--------------------------------------

To install Hootenanny on CentOS/RHEL follow the instruction in
--------------------------------------
hootenanny-${HOOT_VERSION}/scripts/AWSProvision_CentOS_RHEL_6_5.sh
--------------------------------------

The script does not install Hadoop.

For additional details on configuring the database connection pool, see <<HootDBConnectionPool>>.

== Hootenanny Package Descriptions

The following instructions assumed you have used the Hootenanny build process to already have generated the following files:

* The Hootenanny core and UI source archive (hootenanny-X.Y.Z.tar.gz)
** The hoot core code is written in C++ and is to be packaged in a source archive (tar.gz) on a build machine during the release process. The source archive will be then compiled on the target installation machine.
** The hoot UI code is in Javascript and is packaged inside of the same source archive that the hoot core code is packaged in a directory named "hoot-id". The directory is to be manually copied to the web server on the target installation machine.
* The Hootenanny services web archive (hootenanny-services-X.Y.Z.war) files
** The hoot services code is in Java and is compiled on a build machine and packaged into a web archive (.war) file as a result of the release process. The war file is then deployed to the web server on the target installation machine.
* The FOUO translations archive (hootenanny-translations.tar.gz), which are only available through official channels.

== Helpful Hints

. You can also add a custom base map quickly to the Hootenanny UI, without having to edit Javascript code if that is more convenient, but the base map will not be retained in the base maps list between browser refreshes (a bug). To add a custom basemap:

.. From the right hand menu in iD, click "Custom".
.. Add the URL for the basemap you wish to use.

. If you want to define a starting AOI for your maps, so you begin in the same location every time you open the browser, modify the "hoot.center" variable in +/var/lib/tomcat8/webapps/WEB-INF/hootenanny-id/hoot/js/custom/hoot.js+.

. You can quickly zoom to an AOI by modifying the end of the browser URL. The parts you modify are of the form /[zoom]/[longitude]/[latitude].

== Advanced Tasks

=== Test Bandwidth (optional)

If you're on a new server and want a rudimentary test for bandwidth then do the following:

--------------------------------------
cd /var/lib/tomcat8/webapps
sudo fallocate -l 100M dum.txt
sudo chmod 777 dum.txt
--------------------------------------

Then try downloading the file created e.g. http://myhost/dum.txt

. Completely clear your browser history.

. Browse to http://localhost/hootenanny-id (replace localhost with the Hootenanny server name) to verify the web application is available and the base map is visible.

. Click on the "Hootenanny | Innovision" logo.  You should see version information displayed for the Hootenanny core, services, and user interface.  The version numbers should all match each other and should also match the version you installed.

NOTE: If client-side debugging becomes necessary, the "Developer Tools" in Chrome can be used.  See <<HootUITroubleshoot,UI Troubleshooting>> for additional information.

. You may need to build up a tile cache for your AOI by zooming to the desired area and pausing for awhile to wait for the tiles to load before attempting to conflate with Hootenanny to avoid overtaxing your web browser with open tile requests.

=== Ingest Data (optional)

If you have a small amount of data to ingest, you can easily do it from within the Hootenanny UI using the "Add Dataset" feature. If you have a large number of files you would like to script for ingest at one time, you may do it with repeated call something like the following:

--------------------------------------
#adjust email accordingly; setting not needed if already set in conf/hoot.json during build
hoot convert -D services.db.write.email='test@test.com' /myData.osm postgresql://hoot:hoottest@localhost:5432/hoot/myMap

--------------------------------------

=== Configure the Base Map List

To manually configure the available base maps shown in the iD editor:

. Edit +$HOOT_HOME/hoot-ui/data/imagery.json+
. Add or remove JSON entries to edit the base maps.  At a minimum, you must:
.. specify a unique ID for the layer in the "id" attribute
.. specify a name for the base map in the "name" attribute
.. specify a min and max scale extent for the base map that defines at what zoom level range it will be visible in the "scaleExtent" attribute
.. specify whether the base map should be selected by default by setting the "default" attribute to "true" or "false

