[[alpha-shape]]
== alpha-shape

=== Description

The +alpha-shape+ command provides a way to generate a concave hull for a set of points. This is most useful when seeding the
+cut+ command. The degree of the concaveness is determined by the alpha parameters.

* +input+    - The input data to use for deriving the alpha shape; may be any supported input format (e.g. OSM file). 
               The alpha shape algorithm is used to derive a polygon representing the bounds.
* +output+   - The output; may be any supported output format (e.g. OSM file). When output to a +.osm+ file the alpha 
               shape will always be a multi-polygon with one attribute +area=yes+. When output as a Shapefile it will be 
               a multipolygon shapefile with a single record.
* +--alpha+  - Optional size in meters used for alpha. A larger value makes a smoother shape closer to a convex hull, and 
               a smaller value will create a rough shape with more holes and concave sections. An alpha value equal to 
               the maximum distance between any two points in the data or larger will create a convex hull. If no alpha 
               value is given, Hootenanny will run an approximation algorithm to find a valid alpha value.
* +--buffer+ - Optional buffer to add to the alpha shape before cutting. A negative value will make the shape smaller. Value 
               in meters. Generally a buffer of zero will be used. If using the alpha shape command with cookie cutter it 
               is a good idea to use a larger negative value on complex data shapes. This will limit the number of holes 
               in the data. A negative value equal to the alpha value is a good rule of thumb. The default value of the buffer 
               is 0 meters.

=== Usage

--------------------------------------
alpha-shape (input) (output) [--alpha value] [--buffer value]
--------------------------------------

https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#create-a-shape-that-covers-a-set-of-features-with-a-buffer[Examples]

=== See Also

* https://github.com/ngageoint/hootenanny/files/595246/Hootenanny.-.Alpha.Shape.2013-03-07.pptx[Alpha Shape Presentation]
* https://github.com/ngageoint/hootenanny/blob/master/docs/algorithms/AlphaShape.asciidoc[Alpha Shape Documentation]
* https://github.com/ngageoint/hootenanny/wiki/files/2010-B-01-AlphaShapes.pdf[Alpha Shape Research Paper]
* _Horizontal Conflation_, <<hootalgo,Hootenanny - Algorithms>>
* _Cookie Cutter_ section of <<hootalgo, Hootenanny - Algorithms>>
* `cookie.cutter.*` configuration options
* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]

