== apply-changeset

=== Description

The +apply-changeset+ command writes an OSM changeset file that represents the difference
between two OSM files to an OSM API database.  Optional conflict parameters may be 
passed, so that if the target database contains any changesets created after the time
represented by a timestamp that intersect with a specified AOI, the command will return
an error.

* +sqlChangeset+ - input SQL changeset (e.g. .osc.sql file).
* +targetDatabaseUrl+ - database the changeset will be written to.
* +conflictAoi+ - bounding box string of the form: minx,miny,maxx,maxy used to prevent writing conflicted data (see description)
* +conflictTimestamp+ - timestamp of the form: "yyyy-MM-dd hh:mm:ss.zzz" used to prevent writing conflicted data (see description)

=== Usage

--------------------------------------
apply-changeset (sqlChangeset) (targetDatabaseUrl) [conflictAoi] [conflictTimestamp]
--------------------------------------

==== Examples

--------------------------------------
hoot apply-changeset changeset.osc.sql osmapidb://username:password@localhost:5432/databaseName

hoot apply-changeset changeset.osc.sql osmapidb://username:password@localhost:5432/databaseName -93.89258,40.96917,-93.60583,41.0425 "2016-05-04 10:15:37.000"-93.89258,40.96917,-93.60583,41.0425
--------------------------------------

