== calculate-tiles 

=== Description

Calculates a collection of bounding boxes that contain roughly equal distributions of node data from the specified input(s).

* +input+ - one or more OSM data inputs; specify multiple inputs by separating them with a semicolon
* +output+ - output file to write the tile boundaries to; valid formats are OSM (*.osm) and GeoJSON (*.geojson)
* +maxNodeCountPerTile+ The maximum number of nodes in any tile.  The default is 1000; optional (required if pixelSize is specified)
* +pixelSize+ The size of the pixels used in the calculation.  The default is 0.001; optional

If too low a value is specified for maxNodeCountPerTile or too high a value is specified for pixelSize, the algorithm used
may not be able to find a solution.  This command makes use of the optional 'convert.bounding.box' configuration option to determine a subset of the input data 
to calculate tiles for.

=== Usage

--------------------------------------
hoot calculate-tiles (input(s)) (output) [maxNodeCountPerTile] [pixelSize]
--------------------------------------

=== Examples

--------------------------------------
hoot calculate-tiles test-files/MyInputFile.osm MyOutputFile.osm
--------------------------------------

--------------------------------------
hoot calculate-tiles "test-files/MyInputFile1.osm;test-files/MyInputFile2.osm" MyOutputFile.osm 1000
--------------------------------------

--------------------------------------
hoot calculate-tiles "test-files/MyInputFile1.osm;test-files/MyInputFile2.osm" MyOutputFile.geojson 1000 0.001
--------------------------------------
