[[changeset-derive-replacement]]
== changeset-derive-replacement

=== Description

The +changeset-derive-replacement+ command creates an OSM changeset file that represents the difference between two input OSM datasets with a 
given bounds. The data from the second input dataset completely replaces data in the first dataset within the bounds. The output changeset 
file can later be applied to an OSM API database with the +changeset-apply+ command.

* +input1+             - OSM data input 1 (e.g. .osm file)
* +input2+             - OSM data input 2 (e.g. .osm file)
* +bounds+             - Comma delimited bounds: minx,miny,maxx,maxy; e.g. "38,-105,39,-104"
* +featureFilter+      - A single ConflatableElementCriterion class name used to determine which type of features are replaced in the reference 
                         dataset (currently only one criterion may be specified in a filter). e.g. "hoot::BuildingCriterion"
* +output+             - Output location (e.g. .osc or .osc.sql file)
* +osmApiDatabaseUrl+  - Target OSM API database the changeset is to be applied to.  Used to maintain
                         element ID continuity with a particular database instance when generating SQL
                         changesets only (.osc.sql).
* +--lenient-bounds--+ - By default, features will only replaced if they lie completely within the specified bounds. Activating this option
                         makes the bounds handling more lenient (has no effect on point datasets). See the "Bounds Handling" section below 
                         for more detail.
* +--stats+            - Stats flag, when turned on a table of create, modify, delete for each of the types node, way, relation (only valid for 
                         .osc output files only)
* +--write-bounds+     - If the `convert.bounding.box` configuration option is specified, optionally outputs a file containing the input bounds.
                         The location of the file is controlled via the `bounds.output.file` configuration option.

=== Usage

--------------------------------------
changeset-derive-replacement (input1) (input2) (bounds) (featureFilter) (output) [osmApiDatabaseUrl] [--stats] [--write-bounds]
--------------------------------------

=== Examples

--------------------------------------
hoot changeset-derive-replacement input1.osm input2.osm "38,-105,39,-104" hoot::BuildingCriterion outputChangeset.osc 

hoot changeset-derive-replacement -D convert.ops="op1;op2" input1.osm input2.osm "38,-105,39,-104" hoot::BuildingCriterion outputChangeset.osc --lenient-bounds

hoot changeset-derive-replacement input1.osm input2.osm "38,-105,39,-104" hoot::BuildingCriterion outputChangeset.osc --stats

hoot changeset-derive-replacement input1.osm input2.osm "38,-105,39,-104" hoot::BuildingCriterion outputChangeset.osc.sql osmapidb://username:password@localhost:5432/osmApiDatabaseName
--------------------------------------

=== Bounds Handling

==== Strict Bounds Handling

===== Points

- Only reference features completely inside the bounds will be replaced.
- No secondary feature on or outside the boundary will be included in the output.

===== Lines

* No reference feature crossing the bounds will be modified outside of the bounds. Reference features may be split.
* No parts of secondary features crossing the bounds will be included in the output

===== Polygons

* No reference features crossing the bounds will be modified
* No secondary features crossing the bounds will be included in the output

==== Lenient Bounds Handling

===== Points

N/A - Point bounds relationships are only handled in a strict fashion.

===== Lines

* Reference features crossing the bounds will be completely replaced by secondary features

===== Polygons

* Reference features crossing the bounds may be modified. They will not be split, and will only be conflated with secondary features.
* Secondary features crossing the bounds may be included unmodified in the output or conflated with reference features.

=== See Also

* `changeset-derive` command
* `changeset.*` configuration options
