== changeset-apply

=== Description

The +apply-changeset+ command writes an OSM changeset XML file(s), OSM XML file(s), or SQL file that represents the difference between two OSM datasets
to an OSM API database.  The OSM API database URL is   Optional conflict parameters may be passed for SQL files, so that if the target database contains any changesets
created after the time represented by a timestamp that intersect with a specified AOI, the command will return an error.

* +changeset.os*+     - one or more input OSM XML changeset (.osc file) or OSM XML file (.osm) with negative IDs.
* +targetOsmApiUrl+   - OSM API endpoint the changeset will be written to.
* +changeset.osc.sql+ - input SQL changeset (e.g. .osc.sql file).
* +targetDatabaseUrl+ - database the changeset will be written to.
* +conflictAoi+       - bounding box string of the form: minx,miny,maxx,maxy used to prevent writing conflicted
                        data (see description)
* +conflictTimestamp+ - timestamp of the form: "yyyy-MM-dd hh:mm:ss.zzz" used to prevent writing conflicted
                        data (see description)
* +--stats+           - output statistics (element, node, way, relation, failure, create, modify, and delete counts)
* +--progress+        - display progress as a percent complete while the upload is working

=== Usage

--------------------------------------
changeset-apply (changeset.os*) [changeset2.os* ...] (targetOsmApiUrl) [--stats] [--progress]
changeset-apply (changeset.osc.sql) (targetDatabaseUrl) [conflictAoi] [conflictTimestamp]
--------------------------------------

==== Examples

--------------------------------------
hoot changeset-apply changeset.osc http://username:password@localhost/

hoot changeset-apply changeset.osc changeset-001.osc changeset-002.osc https://username:password@localhost/

hoot changeset-apply sourcedata.osm http://username:password@localhost/ --stats --progress

hoot changeset-apply changeset.osc.sql osmapidb://username:password@localhost:5432/databaseName

hoot changeset-apply changeset.osc.sql osmapidb://username:password@localhost:5432/databaseName -93.89258,40.96917,-93.60583,41.0425 "2016-05-04 10:15:37.000"-93.89258,40.96917,-93.60583,41.0425
--------------------------------------

=== See Also

* `changeset.*` configuration options

