[[changeset-apply]]
== changeset-apply

=== Description

The +changeset-apply+ command writes a OSM changeset XML file(s) (.osc or .xml) or a SQL changeset file (.osc.sql) to an OSM API database.

Optional conflict parameters may be passed for SQL files, so that if the target database contains any changesets created after the time 
represented by a timestamp that intersect with a specified AOI, the command will return an error.

* +changeset.os*+     - One or more input OSM XML changeset (.osc file) or OSM XML file (.osm) with negative IDs when writing the changeset 
                        through the OSM API OR an input SQL changeset (.osc.sql) when writing the changeset directly to an OSM API database.
* +targetUrl+         - If writing the changeset through the OSM API, the OSM API endpoint the changeset will be written to; if writing the 
                        changeset directly to an OSM API database, the URL of the database being written to
* +conflictAoi+       - Bounding box string of the form: minx,miny,maxx,maxy used to prevent writing conflicted data (see description); valid 
                        only when writing the changeset directly to an OSM API database
* +conflictTimestamp+ - Timestamp of the form: "yyyy-MM-dd hh:mm:ss.zzz" used to prevent writing conflicted data (see description); valid only 
                        when writing the changeset directly to an OSM API database
* +--stats+           - Output statistics (element, node, way, relation, failure, create, modify, and delete counts)
* +--progress+        - Display progress as a percent complete while the upload is working

=== Usage

--------------------------------------
changeset-apply (changeset.os*) [changeset2.os* ...] (targetUrl) [--stats] [--progress]
changeset-apply (changeset.osc.sql) (targetUrl) [conflictAoi] [conflictTimestamp]
--------------------------------------

==== Examples

--------------------------------------
hoot changeset-apply changeset.osc http://username:password@localhost/

hoot changeset-apply changeset.osc changeset-001.osc changeset-002.osc https://username:password@localhost/

hoot changeset-apply sourcedata.osm http://username:password@localhost/ --stats --progress

hoot changeset-apply changeset.osc.sql osmapidb://username:password@localhost:5432/databaseName

hoot changeset-apply changeset.osc.sql osmapidb://username:password@localhost:5432/databaseName -93.89258,40.96917,-93.60583,41.0425 "2016-05-04 10:15:37.000"-93.89258,40.96917,-93.60583,41.0425
--------------------------------------

=== See Also

* `changeset.*` configuration options

