[[changeset-apply]]
== changeset-apply

=== Description

The +changeset-apply+ command writes changes from a changeset file to an OSM API database.

Optional conflict parameters may be passed for SQL files, so that if the target database contains any changesets created 
after the time represented by a timestamp that intersect with a specified AOI, the command will return an error.

* +changeset.os*+     - One or more input OSM XML changeset (.osc file) or OSM XML file (.osm) with negative element IDs when 
                        writing the changeset through the OSM API OR an input SQL changeset (.osc.sql) when writing 
                        the changeset directly to an OSM API database.
* +targetUrl+         - If writing the changeset through the OSM API, the OSM API endpoint the changeset will be written 
                        to; if writing the changeset directly to an OSM API database, the URL of the database being written to
* +conflictAoi+       - Bounding box string of the form: minx,miny,maxx,maxy used to prevent writing conflicted data 
                        (see description); valid only when writing the changeset directly to an OSM API database
* +conflictTimestamp+ - Timestamp of the form: "yyyy-MM-dd hh:mm:ss.zzz" used to prevent writing conflicted data 
                        (see description); valid only when writing the changeset directly to an OSM API database
* +--stats+           - Output statistics (element, node, way, relation, failure, create, modify, and delete counts)
* +--progress+        - Display progress as a percent complete while the upload is working

=== Usage

--------------------------------------
changeset-apply (changeset.os*) [changeset2.os* ...] (targetUrl) [--stats] [--progress]
changeset-apply (changeset.osc.sql) (targetUrl) [conflictAoi] [conflictTimestamp]
--------------------------------------

[Examples](https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#applying-changes)

=== See Also

* `changeset.*` configuration options

