[[changeset-derive-replacement]]
== changeset-derive-replacement

=== Description

The +changeset-derive-replacement+ command creates an OSM changeset file that represents the difference between two input OSM datasets
within a given bounds, where the data from the secondary input dataset completely replaces data in the reference dataset. 

The changeset derivation algorithm avoids unnecessary clipping of features (e.g. buildings crossing the specified bounds) and stitches up 
areas where features must be clipped (e.g. roads crossing the specified bounds). The output changeset file can be applied directly to an 
OSM API database or the Rails Port API with the  +changeset-apply+ command. Generally, the reference data is sourced from an authoritative 
data store, like an OSM API database, and the secondary can be any type of data. Element IDs for the first input dataset (reference data) are 
retained and treated as data resident in an authoritative data store. Element IDs for the second input dataset (secondary data) are not retained 
and treated as completely new data. 

* +input1+                  - Reference input with features to replace; may be any supported input format that supports bounded reading 
                              (e.g. OSM file). See the "Bounds Handling" section for more detail.
* +input2+                  - Secondary input with the features used for replacement; may be any supported input format that supports bounded 
                              reading (e.g. OSM file). See the "Bounds Handling" section for more detail.
* +bounds+                  - Comma delimited bounds: minx,miny,maxx,maxy; e.g. "38,-105,39,-104"
* +output+                  - Output location; must be an .osc or .osc.sql file.
* +osmApiDatabaseUrl+       - Target OSM API database the changeset is to be applied to.  Used to maintain element ID continuity with a 
                              particular database instance when generating SQL changesets only (.osc.sql).
* +--strict-bounds+         - Determines how strict the interpretation of the specified bounds is during feature replacement. See the  
                              "Bounds Handling" section for more detail.
* +--geometry-filters+      - Optional criteria used to determine the geometry type of the features that are replaced in the reference 
                              dataset. See the "Geometry Filtering" section for more detail.
* +--input1-filters+        - Optional filtering criteria beyond what is specified in --geometry-filters for determining which reference dataset 
                              features are replaced. See the "Additional Filtering" section for more detail.
* +--chain-input1-filters+  - Determines how the criteria specified in --input1-filters are applied. See the "Additional Filtering" section for 
                              more detail.
* +--input1-filter-options+ - Optional configuration options for the filters specified in --input1-filters. See the "Additional Filtering" 
                              section for more detail.
* +--input2-filters+        - Optional filtering criteria beyond what is specified in --geometry-filters for determining which secondary dataset 
                              features are used as replacement features. See the "Additional Filtering" section for more detail.
* +--chain-input2-filters+  - Determines how the criteria specified in --input2-filters are applied. See the "Additional Filtering" section for 
                              more detail.
* +--input2-filter-options+ - Optional configuration options for the filters specified in --input2-filters. See the "Additional Filtering" 
                              section for more detail.
* +--stats+                 - Stats flag, when turned on a table of create, modify, delete for each of the types node, way, relation (only 
                              valid for .osc output files)
* +--write-bounds+          - If the `convert.bounding.box` configuration option is specified, optionally outputs a file containing the 
                              input bounds. The location of the file is controlled via the `bounds.output.file` configuration option.

=== Usage

--------------------------------------
changeset-derive-replacement (input1) (input2) (bounds) (output) [osmApiDatabaseUrl] [--strict-bounds] [--geometry-filters] [--input1-filters] [--chain-input1-filters] [--input1-filter-options] [--input2-filters] [--chain-input2-filters] [--input2-filter-options] [--stats] [--write-bounds]
--------------------------------------

=== Examples

* "Basic":https://github.com/ngageoint/hootenanny/blob/3360/docs/user/CommandLineExamples.asciidoc#applying-changes
* "Advanced":https://github.com/ngageoint/hootenanny/blob/3360/docs/user/CommandLineExamples.asciidoc#applying-changes-1

=== Filtering

==== Geometry Filtering

The command option, --geometry-filters, controls feature geometry filtering. One or more criterion class names can be used to determine the 
geometry type of the features that are replaced in the reference dataset . The criteria specified must be geometry type criteria (e.g. 
"hoot::BuildingCriterion" or "hoot::PointCriteron"). A feature may pass the geometry filter by satisfying any one of the individual specified 
filters. From the command line, combine multiple criteria with a semicolon and surround the entire value string with quotes.  If no filter is 
specified, features of all geometry types within the bounds will be replaced. Geometry filters are handled separately from the filters 
specified in --additional-filters since Hootenanny executes a different replacement changeset generation workflow dependent upon the geometry 
type of the feature being replaced. 

To see a list of valid geometry type criteria for use as a feature filter:
-----
hoot info --geometry-type-criteria
-----

==== Additional Filtering

The command options, --input1-filters and --input2-filters, allow for feature filtering beyond geometry type. One or more criterion class 
names can added to --input1-filters for filtering beyond what is specified in --geometry-filters to determine the features that are replaced 
in the reference dataset. One or more criterion class names can added to --input2-filters for filtering beyond what is specified in 
--geometry-filters to determine the features that are used for replacement from the secondary dataset. The criteria specified may not be 
geometry type element criteria. From the command line, combine multiple criteria with a semicolon and surround the entire value string with 
quotes. 

The behavior of the filters is determined by the --chain-input1-filters and --chain-input2-filters options. If --chain-input1-filters is used, 
then a feature must pass all criteria in order to pass the filter specified in --input1-filters. If --chain-input2-filters is used, then a 
feature must pass all criteria in order to pass the filter specified in --input2-filters. Likewise, if the chain options are absent, then a 
feature must pass only a single specified criterion to pass the respective filters. 

Configuration options may be passed separately to each set of input filters via the --input1-filter-options and --input2-filter-options 
parameters. The options take the form "<option name 1>=<option value 1>;<option name 2>=<option value 2>..." Passing them separately to each
filter allows for the same criterion to be used with each filter but with a different configuration. Do not prepend these options with "-D" as
is normally done with configuration options passed in from the command line. Any identically named configuration options passed into the command
prepended by "-D" may override these filtering configuration options.

=== Bounds Handling

All inputs must support bounded reading. To list the Hootenanny input formats that support bounded reading:
-----
hoot info --formats --input-bounded
-----

Unless the reference data is being read from a direct connection to an OSM API database (osmapidb://), reference input datasets containing 
linear data should be slightly larger than the replacement AOI, so as not to drop linear features in the changeset output 
(osmapidb:// reference inputs handle this issue automatically).

==== Strict Bounds Handling

The following describes how the AOI is interpreted by the command when the +--strict-bounds+ option is present.

===== Points

- Only reference features completely inside the bounds will be replaced.
- No secondary feature on or outside the boundary will be included in the output.

===== Lines

* No reference feature crossing the bounds will be modified outside of the bounds. Reference features may be split.
* No parts of secondary features crossing the bounds will be included in the output.

===== Polygons

* No reference features crossing the bounds will be modified.
* No secondary features crossing the bounds will be included in the output.

==== Lenient Bounds Handling

The following describes how the AOI is interpreted by the command when the +--strict-bounds+ bounds option is absent.

===== Points

N/A - Point bounds relationships are only handled in a strict fashion.

===== Lines

* Reference features crossing the bounds will be completely replaced by secondary features.

===== Polygons

* Reference features crossing the bounds may be modified. They will not be split, and will only be conflated with secondary features.
* Secondary features crossing the bounds may be included unmodified in the output or conflated with reference features.

=== Versioning

If the target of the resulting changeset is an OSM API database, all input features from the reference dataset must 
be populated with the correct changeset versions or application of the resulting changeset will fail. 

For Overpass API queries, add "out meta" to the query retrieving the reference data.

=== Unsupported Formats

GeoJSON output from the Overpass API is not supported by this command, since it does not contain way nodes.

=== See Also

* `changeset-derive` command
* `changeset.*` configuration options
* `snap.unconnected.ways.*` configuration options
* "Supported Input Formats":https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc
