[[changeset-derive]]
== changeset-derive

=== Description

The +changeset-derive+ command creates an OSM changeset file that represents the difference between two input
OSM datasets.  Alternatively, when only one dataset is input it generates a changeset file representing all
the data in the input dataset. The output changeset file can later be applied to an OSM API database with
the +changeset-apply+ command.

If deriving a changeset between two inputs from different dates, the first input should be the older
dataset and the second should be the newer dataset.

* +input1+            - OSM data input 1; may be any supported input format (e.g. .osm file).
* +input2+            - OSM data input 2; may be any supported input format (e.g. .osm file or empty string ("") to derive changeset from one 
                        input only).
* +output+            - Output location; may be an .osc or .osc.sql file.
* +osmApiDatabaseUrl+ - Target OSM API database the changeset is to be applied to.  Used to maintain
                        element ID continuity with a particular database instance when generating SQL
                        changesets only.  Required only if the changeset output format is .osc.sql.
* +--stats+           - Stats flag, when turned on a table of create, modify, delete for each of the types
                        node, way, relation (only valid for .osc output files)
* +--write-bounds+    - If the `convert.bounding.box` configuration option is specified, optionally outputs a file containing the input bounds.
                        The location of the file is controlled via the `bounds.output.file` configuration option.

=== Usage

--------------------------------------
changeset-derive (input1) [input2] (output) [osmApiDatabaseUrl] [--stats] [--write-bounds]
--------------------------------------

=== Examples

--------------------------------------
hoot changeset-derive inputData1.osm inputData2.osm outputChangeset.osc

hoot changeset-derive -D convert.ops="op1;op2" inputData1.osm inputData2.osm outputChangeset.osc

hoot changeset-derive inputData1.osm inputData2.osm outputChangeset.osc --stats

hoot changeset-derive inputData.osm "" outputChangeset.osc

hoot changeset-derive inputData.osm "" outputChangeset.osc.sql osmapidb://username:password@localhost:5432/osmApiDatabaseName
--------------------------------------

=== Configuration Options

Changeset deriviation supports inline conversion operations with the `convert.ops` configuration option. See the https://github.com/ngageoint/hootenanny/blob/master/docs/commands/convert.asciidoc#conversion-operations[Conversion Operations] section of the `convert` command documentation for details.

=== Sorting

Element sorting, required by changeset derivation, is performed in memory by default. This may cause problems with larger datasets.  To perform sorting in a non-memory bound fashion (to external disk), set the configuration option element.sorter.element.buffer.size to a value greater than zero.

Also, if inline conversion operations are specified in `convert.ops` and any of them do not support streaming (either operations that are an OsmMapOperation or an OsmMapConsumer), in-memory sorting will always occur.

=== See Also

* `changeset.*` configuration options
* "Supported Input Formats":https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc
