[[changeset-apply]]
== changeset-apply

=== Description

The +changeset-apply+ command writes changes from a changeset file to an OSM API data store.

Optional conflict parameters may be passed for SQL files, so that if the target database contains any changesets created 
after the time represented by a timestamp that intersect with a specified AOI, the command will return an error.

* +changeset(s)+ - One or more input OSM XML changesets (.osc file) or OSM XML files (.osm) with negative element IDs when 
                   writing the changeset through the OSM API. If writing directly to an OSM API database, then the input must
                   be a single SQL changeset (.osc.sql) files.
* +targetUrl+    - If writing the changeset through the OSM API, the OSM API endpoint the changeset will be written to. If 
                   writing the changeset directly to an OSM API database, the URL of the database being written to.
* +--progress+   - Display progress as a percent complete while the upload is working; ignored when using SQL changesets
* +--stats+      - Output statistics (element, node, way, relation, failure, create, modify, and delete counts); ignored when
                   using SQL changesets

=== Usage

--------------------------------------
hoot changeset-apply (changeset1.os*) [changeset2.os* ...] (targetUrl) [--progress] [--stats] 
hoot changeset-apply (changeset.osc.sql) (targetUrl)
--------------------------------------

https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#applying-changes[Examples]

=== See Also

* `changeset.*` configuration options

