== changeset-apply

=== Description

The +apply-changeset+ command writes an OSM changeset XML file(s) or SQL file that represents the difference between two OSM datasets
to an OSM API database.  The OSM API database URL is   Optional conflict parameters may be passed for SQL files, so that if the target database contains any changesets
created after the time represented by a timestamp that intersect with a specified AOI, the command will return an error.

* +changeset.osc+     - one or more input XML changeset (e.g. .osc files).
* +targetOsmApiUrl+   - OSM API endpoint the changeset will be written to.
* +changeset.osc.sql+ - input SQL changeset (e.g. .osc.sql file).
* +targetDatabaseUrl+ - database the changeset will be written to.
* +conflictAoi+       - bounding box string of the form: minx,miny,maxx,maxy used to prevent writing conflicted
                        data (see description)
* +conflictTimestamp+ - timestamp of the form: "yyyy-MM-dd hh:mm:ss.zzz" used to prevent writing conflicted
                        data (see description)

=== Usage

--------------------------------------
changeset-apply (changeset.osc) [changeset2.osc ...] (targetOsmApiUrl)
changeset-apply (changeset.osc.sql) (targetDatabaseUrl) [conflictAoi] [conflictTimestamp]
--------------------------------------

==== Examples

--------------------------------------
hoot changeset-apply changeset.osc http://username:password@localhost/

hoot changeset-apply changeset.osc changeset-001.osc changeset-002.osc https://username:password@localhost/

hoot changeset-apply changeset.osc.sql osmapidb://username:password@localhost:5432/databaseName

hoot changeset-apply changeset.osc.sql osmapidb://username:password@localhost:5432/databaseName -93.89258,40.96917,-93.60583,41.0425 "2016-05-04 10:15:37.000"-93.89258,40.96917,-93.60583,41.0425
--------------------------------------

=== See Also

* `changeset.*` configuration options

