[[clean]]
== clean

=== Description

The +clean+ command corrects common erroneous data scenarios from input and writes to output by applying the 
operations specified in the `map.cleaner.transforms` configuration option. The operation is memory bound.

* +input(s)+    - One or more inputs(s); may be any supported input format (e.g. .osm file).
* +output+      - Output; may be any supported output format (e.g. .osm file).
* +--recursive+ - Allows for cleaning data recursively in a directory structure. This must be followed by either "*" 
                  to denote no filtering or one or more wildcard name filters. e.g. "*.osm;*.json" or "*myFile*". 
                  The recursion is only performed on file directories and this parameter is ignored for other input types.

To see a list of the default cleaning operation configuration:
-----
hoot info --cleaning-operations
-----

=== Usage

--------------------------------------
clean (input) [input2...] (output) [--recursive "*"|"filter1;filter2..."]
--------------------------------------

https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#cleaning[Examples]

==== See Also

* `map.cleaner.transforms` configuration option
* <<hootalgo, IngestAndClean>>
* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]
