[[compare]]
== compare

=== Description

The +compare+ command compares a map (uut, Unit Under Test) to one or two test maps (base1 & base2) and prints out three
score metrics. This operation is most commonly used to compare manually conflated data to automatically conflated data.
The scores provided give an idea of similarity between maps. A score of 1000 means they're exactly the same. A score of
0 means the maps are very different.

* +base1+                 - The first map file to compare; may be any supported input format.
* +base2+                 - (optional) The second base map file to compare; may be any supported input format.
* +uut+                   - The map file being evaluated; may be any supported input format.
* +criteria+              - (optional) Filtering criteria for the inputs; May be one or more class names inheriting 
                            from `ElementCriterion` delimited with a semicolon and surrounded by quotes. By default, multiple 
                            criteria are logically OR'd together. Set the `element.counter.chain.element.criteria` option 
                            to true to have the criteria logically AND'd together. The criteria can be negated with the 
                            option `element.criteria.negate`. Use the +info --operators+ command to obtain a list of 
                            available criteria.
* +--disable-<scoreType>+ - Allows for disabling any of the score types. e.g. `--disable-attribute`.

The following types of scores are provided in the score result:

* Attribute Score                            - A metric describing how similar the attributes are between the two maps
* Raster Score (AKA Location & Completeness) - A metric describing how complete the data is and how close the features 
                                               are together
* Graph Score (AKA Routing)                  - A metric describing how similar the maps would be if used to perform 
                                               routing analytics

=== Usage

--------------------------------------
hoot compare (base1) [base2] (uut) [criteria] (--disable-attribute | --disable-raster> | --disable-graph)
--------------------------------------

https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#comparison[Examples]

=== See Also

* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]

