[[compare]]
== compare

=== Description

The +compare+ command compares a map (uut, Unit Under Test) to one or two test maps (base1 & base2) and prints out three
score metrics. This operation is most commonly used to compare manually conflated data to the automatically conflated data.
The scores provided give an idea of similarity between maps. A score of 1000 means they're exactly the same. A score of
0 means the maps are very different.

* +base1+ - The first map file to compare; may be any supported input format.
* +base2+ - (optional) The second base map file to compare; may be any supported input format.
* +uut+   - The map file being evaluated; may be any supported input format.

The following variables are provided in the score result:

* Raster Score (AKA Location & Completeness) - A metric describing how complete the data is and how close the features 
                                               are together
* Graph Score (AKA Routing)                  - A metric describing how similar the maps would be if used to perform 
                                               routing analytics
* Attribute Score                            - A metric describing how similar the attributes are between the two maps

=== Usage

--------------------------------------
compare (base1) [base2] (uut)
--------------------------------------

https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#comparison[Examples]

=== See Also

* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]

