[[conflate]]
== conflate

=== Description

The +conflate+ command conflates two maps into a single map.

* +input1+            - First input; may be any supported input format (e.g. OSM file).
* +input2+            - Second input; may be any supported input format (e.g. OSM file).
* +output+            - The output path; may be any supported output format or a changeset format if the 
                        +--differential+ option is specified (.osc, .osc.sql)
* +osmApiDatabaseUrl+ - Target OSM API database the derived changeset is to be applied, used to maintain element 
                        ID continuity. Required only if the +--differential+ option is specified and the changeset 
                        output format is .osc.sql.
* +--changeset-stats+ - Displays changeset statistics and may be optionally followed by an output JSON file name. If a file 
                        is not specified, statistics are printed to the screen. Valid only if the +--differential+ option 
                        is specified and the output format is .osc. If the +--include-tags++ option is specified, tag
                        changeset statistics are also output.
* +--differential+    - Calculates the the differential between two conflation inputs.  The output will be all elements 
                        in input2 that do not conflict with any elements in input1.
* +--include-tags+    - Include a check for modified tags when doing differential conflation. The output will 
                        include unmodified geometries from Input1, with new/updated tags from Input2 applied, using 
                        an overwrite-merge. Valid only when the +--differential++ option is used.
* +--separate-output+ - Write separate output files for geometry and tag changes. Valid only when the +--differential++ 
                        and +--include-tags++ options are used.
* +--stats+           - Displays map statistics and may be optionally followed by an output JSON file name. If a file is 
                        not specified, statistics are printed to the screen.
* +--write-bounds+    - If the `bounds` configuration option is specified, optionally outputs a file containing the 
                        input bounds. The location of the file is controlled via the `bounds.output.file` configuration option.

=== Feature Tag Filtering

A subset of input features may be conflated by specifying the 'conflate.tag.filter' configuration 
option. The option allows for JSON feature tag filtering by specifying either inline JSON or the 
path to a JSON file.  For more information, see the "Feature Filtering" section of the Hootenanny 
User Guide.

=== Filtering Features Geographically

If the configuration option, `bounds`, is set to a valid geographic bounds (see the configuration 
option documentation for formats), conflation will conflate data only from within the specified 
bounds. The `bounds.*` configuration options allow for further customization of the bounds 
requirement. If you are generating a changeset with data generated by the `conflate` command that 
used the `bounds` option, it is possible you will want to use the `bounds` option when making the 
call to the `changeset-derive` command as well.

=== Usage

--------------------------------------
hoot conflate (input1) (input2) (output) [osmApiDatabaseUrl] [--changeset-stats geometry-stats-filename tags-stats-filename] \
  [--differential] [--include-tags] [--separate-output] [--stats filename] 
--------------------------------------

https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#conflation[Examples]

=== See Also

* _Unifying Conflation_, <<hootalgo,Hootenanny - Algorithms>>
* _Differential Conflation_, <<hootalgo,Hootenanny - Algorithms>>
* _Attribute Conflation_, <<hootalgo,Hootenanny - Algorithms>>
* _Horizontal Conflation_, <<hootalgo,Hootenanny - Algorithms>>
* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]

