[[conflate]]
== conflate

=== Description

The +conflate+ command conflates two maps into a single map.  If the specified output file name ends with the extension .osc, an OSM 
                     changeset will be written, instead of an OSM map.

* +input1+         - First input (e.g. OSM file).
* +input2+         - Second input (e.g. OSM file, XML changeset file (.osc)).
* +output+         - The output path.
* +--differential+ - Calculates the the differential between two conflation inputs.  The output will be all elements in input2 that do 
                     not conflict with any elements in input1.
* +--include-tags+ - Include a check for modified tags when doing differential conflation.  The output will include unmodified geometries
                     from Input1, with new/updated tags from Input2 applied, using an overwrite-merge.
* +--stats+        - Hootenanny map statistics such as node and way count; must be the last option entered and may be optionally followed
                     by an output file name

=== Feature Filtering

A subset of input features may be conflated by specifying the 'conflate.tag.filter' configuration option.  The option allows for JSON 
feature tag filtering.  For more information, see the "Feature Filtering" section of the Hootenanny User Guide.

=== Usage

--------------------------------------
conflate (input1) [input2] (output) [--differential] [--stats filename]
--------------------------------------

==== Examples

--------------------------------------
hoot conflate input1.osm input2.osm output.osm --stats
--------------------------------------

--------------------------------------
hoot conflate input1.osm input2.osm output.osm --stats stats-output
--------------------------------------

--------------------------------------
hoot conflate input1.osm input2.osm output.osm --differential
--------------------------------------

--------------------------------------
hoot conflate input1.osm input2.osm output.osc --differential
--------------------------------------

--------------------------------------
hoot conflate input1.osm input2.osm output.osc --differential --stats
--------------------------------------

==== See Also

* _Unifying Conflation_, <<hootalgo,Hootenanny - Algorithms>>
* _Differential Conflation_, <<hootalgo,Hootenanny - Algorithms>>

