== convert

=== Description

The +convert+ command converts map data from one input format to another. This does not perform any translation, only conversion.  
The process may be memory bound, depending upon the formats selected (see below). Please see convert-ogr2osm and convert-osm2shp 
for a description of conversions between tabular formats and OSM.  

* +input+  - Input (e.g. .osm file).
* +output+ - Output file (e.g. .osm file).

If the `convert.ops` configuration option is specified then all the specified
operations are applied to the map in order before writing the result to the
output.

=== Usage

--------------------------------------
convert (input) (output)
--------------------------------------

=== Supported Formats

See the README file for details.

=== Database URL Format

The format for database URLs is: protocol://<user name>:<password>@<host name>:<port>/<database name>

=== Notes

* Writing to OSM API databases (osmapidb://) is intended to be a bulk operation for new data only (no updates on existing data).

=== See Also

* `convert.ops` configuration option

