
[[cookie-cutter]]
== cookie-cutter

=== Description
When you have two data sets to conflate where one is clearly better than the other in every way (attributes and geometric accuracy), the cookie cutter can be a very useful tool. For instance, you may have country wide primary roads and very high quality city scale roads for a small region. In this case you'll want to remove a section of the country scale roads, then conflate the high quality roads back in. The +cookie-cutter+ command functions by reading in a OSM input file as the +cutter-shape+ and removes the cookie cutter shape from the contents of the 'dough' file. The resulting geometries are written to 'output'. The dough input is limited by the available RAM.

* +cutter-shape+ - The input Polygons to use as the cutter shape.
* +dough+ - The input OSM data to cut from.
* +output+ - The output OSM data path.
* +buffer+ - Optional buffer value, if the buffer value is provided then the shape is buffered by this many meters before cutting. The buffer may be positive or negative.
* +--crop+ - Optional crops based on the polygon rather than doing a cookie cut.

=== Usage
--------------------------------------
cookie-cutter (cutter-shape) (dough) (output) [buffer] [--crop]
--------------------------------------

==== Example

--------------------------------------
wget http://dcatlas.dcgis.dc.gov/catalog/download.asp?downloadID=88&downloadTYPE=ESRI
hoot ogr2osm DcRoads DcBig.osm StreetSegmentLn.shp
cp $HOOT_HOME/test-files/DcTigerRoads.osm DcSmall.osm
# It is a good idea to manually verify the alpha shape for correctness after it
# is generated. -15m works well for this square data, but will likely cause
# issues on more complex shapes.
hoot alpha-shape DcSmall.osm 1000 -15 DcSmallBounds.shp
hoot cookie-cutter DcSmallBounds.shp DcBig.osm DcBigCut.osm
hoot conflate DcSmall.osm DcBigCut.osm ConflatedDc.osm
--------------------------------------

