[[crop]]
== crop

=== Description

The +crop+ command crops a map to a specified bounds. 

The default cropping behavior is that individual features on the border are modified to make sure nothing is outside the 
given bounds. This behavior may be customized with the `crop.*` configuration options.

* +input(s)+       - Input(s); may be any supported input format (e.g. .osm file).
* +output+         - Output; may be any supported output format (e.g. .osm file).
* +bounds+         - The boundary to crop the data to of the format: minx,miny,maxx,maxy e.g.38,-105,39,-104
* +--recursive+    - Allows for processing the files contained in any directories specified in +input(s)+ recursively.
                     This parameter has no effect on the processing of non-directory inputs. This must be followed by either 
                     "*" to denote no filtering or one or more wildcard name filters. e.g. "*.osm;*.json" or "*myFile*".
* +--write-bounds+ - Optionally outputs a file containing the cropped bounds. The location of the file is controlled via the 
                     `bounds.output.file` configuration option.

=== Usage

--------------------------------------
hoot crop (input1) [input2...] (output) (bounds) [--recursive "*"|"filter1;filter2..."] [--write-bounds]
--------------------------------------

https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#crop-a-map-to-an-extent[Examples]

=== See Also

* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]
