[[crop-random]]
== crop-random

=== Description

The +crop-random+ command randomly crops a section of map data to an area with a specified maximum node count. This is useful if you have a 
very large file dataset and need a smaller subset of data to test conflation against.

* +input+        - The input data path; may be any supported input format (e.g. OSM file)
* +output+       - The output data path; may be any supported output format (e.g. OSM file)
* +maxNodeCount+ - The maximum number of nodes to include in the output. If the number of nodes in the entire dataset is less than the 
                   specified number, no cropping will occur.
* +randomSeed+   - Optionally seeds the random number generator for consistent output; useful during testing; use -1 for no seeding

=== Usage

--------------------------------------
crop-random (input.osm) (output.osm) (maxNodeCount) [randomSeed]
--------------------------------------

=== Configuration Options

The following cropping configuration options are not supported:
* +crop.bounds+ - This is unnecessary since the command calculates the crop bounds automatically based on maximum node count.
* +crop.invert+

See the [[crop]] command for details on the remaining supported cropping configuraiton options.

=== Examples

--------------------------------------

--------------------------------------

=== See Also

* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]
