[[cut]]
== cut

=== Description

The +cut+ command cuts a section out of a map.

When you have two data sets to conflate where one is clearly better than the other in every way (attributes and 
geometric accuracy), the cookie cutter can be a very useful tool. For instance, you may have country wide primary roads 
and very high quality city scale roads for a small region. In this case you'll want to remove a section of the country 
scale roads, then conflate the high quality roads back in.  The +cut+ command functions by reading in a OSM input file 
as the +cutter-shape+ and removes the cookie cutter shape from the contents of the 'dough' file. The resulting geometries 
are written to 'output'. The dough input is limited by the available RAM.

* +cutter-shape+ - The input Polygons to use as the cutter shape; may be any supported input format (e.g. .osm file).
* +dough+        - The input OSM data to cut from; may be any supported input format (e.g. .osm file).
* +output+       - The output OSM data path; may be any supported output format (e.g. .osm file).
* +buffer+       - Optional buffer value, if the buffer value is provided then the
                   shape is buffered by this many meters before cutting. The buffer may be
                   positive or negative.
* +--crop+       - Optionally crops based on the polygon rather than doing a cookie cut.

=== Usage

--------------------------------------
cut (cutter-shape) (dough) (output) [buffer] [--crop]
--------------------------------------

[Examples](https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#cut-a-section-out-of-a-map)

=== See Also

* `cookie.cutter.*` configuration options
* _Horizontal Conflation_, <<hootalgo,Hootenanny - Algorithms>>
* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]

