== derive-changeset

=== Description

The +derive-changeset+ command creates an OSM changeset file that represents the difference between two input 
OSM datasets.  Alternatively, when only one dataset is input it generates a changeset file representing all 
the data in the input dataset. The output changeset file can later be applied to an OSM API database with 
the +apply-changeset+ command.  

Currently, only the SQL output format only supports changeset application. 

If deriving a changeset between two inputs from different dates, the first input should be the older 
dataset and the second should be the newer dataset.  

* +input1+ - OSM data input 1 (e.g. .osm file).
* +input2+ - OSM data input 2 (e.g. .osm file or empty string ("") to derive changeset from one input only).
* +output+ - Output location(s) (e.g. .osc or .osc.sql file; separate multiple outputs with a semicolon).
* +osmApiDatabaseUrl+ - Target OSM API database the changeset is to be applied to.  Used to maintain 
                        element ID continuity with a particular database instance when generating SQL 
                        changesets only.  Required only if the changeset output format is .osc.sql.

=== Usage

--------------------------------------
derive-changeset (input1) [input2] (output) [osmApiDatabaseUrl]
--------------------------------------

==== Examples

--------------------------------------
hoot derive-changeset inputData1.osm inputData2.osm outputChangeset.osc

hoot derive-changeset inputData1.osm inputData2.osm outputChangeset.osc;outputChangeset.osc.sql osmapidb://username:password@localhost:5432/osmApiDatabaseName

hoot derive-changeset inputData.osm "" outputChangeset.osc

hoot derive-changeset inputData.osm "" outputChangeset.osc.sql osmapidb://username:password@localhost:5432/osmApiDatabaseName
--------------------------------------

