== derive-implicit-tag-rules

=== Description

Given an input data source, creates a set of rules which can be used to apply feature types implicitly from input 
feature names.  The implied types can then be used during conflation for better type matching.  Only POI's are 
currently supported.

* +inputs+                 - semicolon delimited list of input paths to supported Hootenanny OSM data formats
* +outputs+                - semicolon delimited list of output paths to supported tag rules output formats; supported
                             formats include Sqlite database (.db), JSON (.json), and comma delimited (.tsv); NOTE: 
                             Only the Sqlite database 
                             format can be used by conflation.
* +typeKeys+               - semicolon delimited list of tag keys to consider when deriving implicit types; specify 
                             "" to use all types
* +minOccurancesThreshold+ - the minimum number of occurances of a type tag in order for a rule to be derived for 
                             it; specify '1' to consider all type tag occurances

=== Usage

--------------------------------------
derive-implicit-tag-rules (inputs) (outputs) (typeKeys) (minOccurancesThreshold)
--------------------------------------

==== Examples

--------------------------------------

--------------------------------------
