== generate-raw-poi-implicit-tag-rules

=== Description

Given input features, creates a rules file which can be used to derive a POI implicit tag rules database using the 
'filter-poi-implicit-tag-rules' command.  The database can then be used to add tags implicitly to POIs, given their names.

* +inputs+                - semicolon delimited list of input paths to supported Hootenanny OSM data formats
* +translations+          - semicolon delimited list of translation scripts used to translate each input dataset
* +output+                - a *.implicitTagRules tab delimited rules file

The following additional configuration parameters apply to raw rule generation:

* poi.implicit.tag.rules.tokenize.names - If true, the POI implicit tags will be derived/added using tokenized names.

=== Usage

--------------------------------------
generate-raw-poi-implicit-tag-rules (inputs) (translations) (output)
--------------------------------------

==== Examples

--------------------------------------
hoot generate-raw-poi-implicit-tag-rules "myInput.osm.pbf;myInput.geonames" "translations/OSM_Ingest.js;translations/GeoNames.js" myRules.implicitTagRules
--------------------------------------

NOTE: If you will be repeatedly generating tag rules files as part of experimentation, you should pre-filter your input datasets to 
POIs to save processing time.

An example:

---------------------------
hoot convert -D convert.ops="hoot::PoiCriterion" myInput myOutput
----------------------------
