== implicit-tagging-derive-raw-rules

=== Description

Given input features, creates a rules file which can be used to derive an implicit tag rules database using the 
implicit-tagging-derive-rules-database command.  The database can then be used to add tags implicitly to elements, given their names.  
Currently, only POI rule generation is supported.  See the "Implicit Element Type Tagging Based On Name" section in the Hootenanny User Guide for
more information.

* +featureType+	 - currently the only type supported is "poi"
* +inputs+       - semicolon delimited list of input paths to supported Hootenanny input data formats
* +translations+ - semicolon delimited list of translation scripts used to translate each input dataset; specify 'none' to skip translation for an input (e.g. OSM data)
* +output+       - an *.implicitTagRules tab delimited implicit tag rules file

Relevant configuration options are those beginning with implicit.tagging.raw.rules.deriver.*, and in some cases those beginning with implicit.tagging.*, 
in conf/core/ConfigOptions.asciidoc.

=== Usage

--------------------------------------
implicit-tagging-derive-raw-rules (featureType) (inputs) (translations) (output)
--------------------------------------

==== Examples

--------------------------------------
hoot implicit-tagging-derive-raw-rules poi "myInput.osm.pbf;myInput.geonames" "translations/OSM_Ingest.js;translations/GeoNames.js" myRules.implicitTagRules
--------------------------------------
