== implicit-tagging-derive-raw-rules

=== Description

Given input features, creates a rules file which can be used to derive a POI implicit tag rules database using the 
'filter-poi-implicit-tag-rules' command.  The database can then be used to add tags implicitly to POIs, given their names.

* +type+	 - currently the only type supported is "POI"
* +inputs+       - semicolon delimited list of input paths to supported Hootenanny OSM data formats
* +translations+ - semicolon delimited list of translation scripts used to translate each input dataset
* +output+       - a *.implicitTagRules tab delimited rules file

Relevant configuration options are those beginning with implicit.tagging.raw.rules.deriver.* in conf/core/ConfigOptions.asciidoc.

=== Usage

--------------------------------------
implicit-tagging-derive-raw-rules (type) (inputs) (translations) (output)
--------------------------------------

==== Examples

--------------------------------------
hoot implicit-tagging-derive-raw-rules POI "myInput.osm.pbf;myInput.geonames" "translations/OSM_Ingest.js;translations/GeoNames.js" myRules.implicitTagRules
--------------------------------------

NOTE: If you will be repeatedly generating tag rules files as part of implicit tag rule tweaking, you should pre-filter your input datasets to 
POIs that are eligible to have implicit tags derived from them to save processing time.  The pre-filtered input datasets must be translated if
in a format other than OSM.

An example:

---------------------------
hoot convert -D convert.ops="hoot::TranslationVisitor;hoot::ImplicitTagEligiblePoiCriterion" -D translation.script="translations/GeoNames.js" myInput.geonames myOutput.geonames

hoot convert -D convert.ops="hoot::ImplicitTagEligiblePoiCriterion" myInput.osm.pbf myOutput.osm.pbf
----------------------------
