[[info]]
== info

The +info+ command displays information about Hootenanny capabilities.

For further detail on how to use this information see both the Hootenanny User and Developer Guides.

=== Option Overview

Only one of the following options can be passed to the command:

* +--cleaning-operations+      - Displays operations configured for cleaning map data
* +--config-options+           - Displays available configuration options
* +--conflatable-criteria+     - Displays criteria that identify conflatable elements
* +--conflate-post-operations+ - Displays operations configured by default to run after a conflation job (can be customized via the
                                 `conflate.post.ops` configuration option)
* +--conflate-pre-operations+  - Displays operations configured by default to run before a conflation job (can be customized via the
                                 `conflate.pre.ops` configuration option)
* +--criterion-consumers+      - Displays operations capable of taking in an ElementCriterion as input
* +--feature-extractors+       - Displays available feature extractors used in conflation model building
* +--filters+                  - Displays a list of all criteria that can be used for element filtering
* +--formats+                  - Displays supported data input/output formats
* +--geometry-type-criteria+   - Displays criteria that identify a feature geometry type
* +--josm-validators+          - Displays available JOSM validators available for use both in validation and cleaning
* +--languages+                - Displays information about translatable/detectable spoken languages
* +--matchers+                 - Displays available feature matchers used during conflation
* +--match-creators+           - Displays available feature match creators used during conflation
* +--mergers+                  - Displays available feature mergers used during conflation
* +--merger-creators+          - Displays available feature merger creators used during conflation
* +--operators+                - Displays available inline operators that can be applied to map datasets
* +--string-comparators+       - Displays available string comparators
* +--subline-matchers+         - Displays available subline matchers
* +--subline-string-matchers+  - Displays available subline string matchers
* +--tag-mergers+              - Displays available feature tag mergers used during conflation
* +--value-aggregators+        - Displays available feature tag value aggregators used in conflation model building
* +--way-joiners+              - Displays available way joiners

Each of the following sections describes an option that may be used with this command and its input parameters.

=== Cleaning Operations

The +--cleaning-operations+ option prints out the currently configured map cleaning operations that are applied during conflation or with the
'clean' command.  The configuration option 'map.cleaner.transforms' controls which operators are applied.

==== Usage

--------------------------------------
info --cleaning-operations
--------------------------------------

==== Example

--------------------------------------
hoot info --cleaning-operations
--------------------------------------

=== Configuration Options

The +--config-options+ option prints out available Hootenanny configuration options.

==== Input Parameters

One of the following input parameters must be specified:

* +name+             - name or partial name of a configuration option to list and/or print a description for
* +--option-names+   - if no name is specified, lists all configuration option names; if a name is specified, lists only
                       configuration option names that have a full or partial match with the input name
* +--option-details+ - if no name is specified, lists all configuration option names and descriptions; if a name is specified,
                       lists only configuration option names and descriptions that have a full or partial match with the input name

==== Usage

--------------------------------------
info --config-options [--option-names]
info --config-options [--option-details]
info --config-options (name) [--option-names]
info --config-options (name) [--option-details]
--------------------------------------

==== Example

--------------------------------------
# by default lists all config option names
hoot info --config-options

# list all config option names
hoot info --config-options --option-names

# list all config option names and their descriptions
hoot info --config-options --option-details

# list all config option names where the name contains the given string
hoot info --config-options poi.polygon --option-names

# list all config option names and their descriptions where the name contains the given string
hoot info --config-options poi.polygon --option-details
--------------------------------------

=== Conflatable Criteria

The +--conflatable-crieria++ option prints out all element criteria classes that can be used to identify conflatable elements.

==== Usage

--------------------------------------
info --conflatable-criteria
--------------------------------------

==== Example

--------------------------------------
hoot info --conflatable-criteria
--------------------------------------

=== Conflate Post Operations

The +--conflate-post-operations+ option prints out the currently configured operations to run immediately after a conflation job with the
'conflate' command.  The configuration option 'conflate.post.ops' controls which operators are applied.

==== Usage

--------------------------------------
info --conflate-post-operations
--------------------------------------

==== Example

--------------------------------------
hoot info --conflate-post-operations
--------------------------------------

=== Conflate Pre Operations

The +--conflate-pre-operations+ option prints out the currently configured operations to run immediately after a conflation job with the
'conflate' command.  The configuration option 'conflate.pre.ops' controls which operators are applied.

==== Usage

--------------------------------------
info --conflate-pre-operations
--------------------------------------

==== Example

--------------------------------------
hoot info --conflate-pre-operations
--------------------------------------

=== Element Criterion Consumers

The +--criterion-consumers++ option prints out all operations that are capable of taking an `ElementCriterion` as input. Passing in an
`ElementCriterion` to an operation can be useful when filtering elements before performing data transformations on them.

==== Usage

--------------------------------------
info --criterion-consumers
--------------------------------------

==== Example

--------------------------------------
hoot info --criterion-consumers
--------------------------------------

=== Feature Extractors

The +--feature-extractors+ option prints out available feature extractors that can be used when building a conflation model with
manually matched map training data.

==== Usage

--------------------------------------
info --feature-extractors
--------------------------------------

==== Example

--------------------------------------
hoot info --feature-extractors
--------------------------------------

=== Filters

The +--filters++ option prints out all the element criteria classes, which are a subset of what is displayed with the +--operators+ option. 
Element criteria can be used to filter elements during a conversion or conflation job.

==== Usage

--------------------------------------
info --filters
--------------------------------------

==== Example

--------------------------------------
hoot info --filters
--------------------------------------

=== Formats

The +--formats+ option prints out supported data formats. 

The --input-bounded sub-option prints out input formats that support bounded reads with the `convert.bounding.box` configuration option.

==== Usage

--------------------------------------
info --formats [--input] [--output] [--input-bounded] [--input-streamable] [--output-streamable] [--ogr]
--------------------------------------

==== Example

--------------------------------------
# prints all supported input and output formats
hoot info --formats

# prints supported input formats
hoot info --formats --input

# prints streamable supported input formats
hoot info --formats --input-streamable

# prints supported input formats that support bounded reading
hoot info --formats --input-bounded

# prints supported output formats
hoot info --formats --output

# prints streamable supported input formats
hoot info --formats --output-streamable

# prints input formats for which Hootenanny uses OGR to read
hoot info --formats --input --ogr

# prints input formats for which Hootenanny uses OGR to write
hoot info --formats --output --ogr
--------------------------------------

=== Geometry Type Criteria

The +--geometry-type-crieria++ option prints out all element criteria classes that can be used to identify an element's geometry.

==== Usage

--------------------------------------
info --geometry-type-crieria
--------------------------------------

==== Example

--------------------------------------
hoot info --geometry-type-crieria
--------------------------------------

=== JOSM Validators

The +--josm-validators++ option prints out all JOSM Java validator classes which can be used to validate map data (mark elements with 
validation errors only) or clean map data (attempt to fix elements with validation errors). This command is only available when Hootenanny is 
configured with JOSM (compiled --with-josm).

==== Usage

--------------------------------------
info --josm-validators
--------------------------------------

==== Example

--------------------------------------
hoot info --josm-validators
--------------------------------------

=== Languages

The +languages+ option displays information about Hootenanny language translation/detection capabilities.

All uses of the +languages+ command require the following configuration options to be populated:
* hoot.services.auth.user.name
* hoot.services.auth.access.token
* hoot.services.auth.access.token.secret

For more information on logging into the web services, see the 'login' command documentation.  Those options are omitted from the
following command examples.

Only one of the following options can be passed to the command:

* +--detectable+    - Prints all spoken languages that Hootenanny can detect and the detectors that can detect them
* +--detectors+     - Prints all available language detector implementations for the translation service
* +--translatable+  - Prints all spoken languages that Hootenanny translate from to English and the translators that can translate them
* +--translators+   - Prints all available language translator implementations for the translation service

The +--detectors+ option prints out all available language detectors that can be used with the Hootenanny web services.

==== Usage

--------------------------------------
info --languages --detectors
--------------------------------------

==== Example

--------------------------------------
hoot info --languages --detectors
--------------------------------------

The +--translators+ option prints out all available language translators that can be used with the Hootenanny web services.

==== Usage

--------------------------------------
info --languages --translators
--------------------------------------

==== Example

--------------------------------------
hoot info --languages --translators
--------------------------------------

The +--detectable+ option prints out spoken languages which Hootenanny can detect when using the Hootenanny web services.

==== Usage

--------------------------------------
info --languages --detectable
--------------------------------------

==== Example

--------------------------------------
hoot info --languages --detectable
--------------------------------------

The +--translatable+ option prints out spoken languages which Hootenanny can translate from to English when using the Hootenanny web
services.

==== Usage

--------------------------------------
info --languages --translatable
--------------------------------------

==== Example

--------------------------------------
hoot info --languages --translatable
--------------------------------------

=== Matchers

The +--matchers+ option prints out available conflate matchers that may be applied when conflating data.  Matchers contain the criteria to match
a specific pair of features

==== Usage

--------------------------------------
info --matchers
--------------------------------------

==== Example

--------------------------------------
hoot info --matchers
--------------------------------------

=== Match Creators

The +--match-creators+ option prints out available conflate match creators that may be applied when conflating data.  Match Creators are
responsible for spawning matchers.

==== Usage

--------------------------------------
info --match-creators
--------------------------------------

==== Example

--------------------------------------
hoot info --match-creators
--------------------------------------

=== Mergers

The +--mergers+ option prints out available conflate mergers that may be applied when conflating data.  Mergers are created to merge a feature
pair supported by a corresponding matcher.

==== Usage

--------------------------------------
info --mergers
--------------------------------------

==== Example

--------------------------------------
hoot info --mergers
--------------------------------------

=== Merger Creators

The +--merger-creators+ option prints out available conflate merger creators that may be applied when conflating data.  Merger Creators are
responsible for spawning mergers.

==== Usage

--------------------------------------
info --merger-creators
--------------------------------------

==== Example

--------------------------------------
hoot info --merger-creators
--------------------------------------

=== Operators

The +--operators+ option prints out available inline operators that can be applied to map data in a Hootenanny command.  Map operators
can be criterion, operations, or visitors.

* An example of an operation is DuplicateWayRemover, which removes all duplicate ways from a map.
* An example of a criterion is NodeCriterion, which acts as a filter to return all nodes in a map.
* An example of a visitor is RemoveTagsVisitor, which removes selected tags from features in a map.

==== Usage

--------------------------------------
info --operators
--------------------------------------

==== Example

--------------------------------------
# lists all available operators
hoot info --operators

# criterion example - filters only nodes from the map to the output
hoot convert -D convert.ops="hoot::RemoveElementsVisitor" -D remove.elements.visitor.element.criteria="hoot::NodeCriterion" \
input1.osm input2.osm output.osm

# operation example - writes a map based on the input data with all duplicate ways removed
hoot convert -D convert.ops="hoot::DuplicateWayRemover" input1.osm input2.osm output.osm

# visitor example - writes a map based on the input data with all of the specified tags removed from the nodes
hoot convert -D convert.ops="hoot::RemoveTagsVisitor" -D remove.tags.visitor.element.criterion="hoot::WayCriterion" -D tag.filter.keys="source;error:circular" input1.osm input2.osm output.osm
--------------------------------------

=== Subline Matchers

The +--subline-matchers+ option prints out available subline matchers that determine which method of line matching is used during conflation.

==== Usage

--------------------------------------
info --subline-matchers
--------------------------------------

==== Example

--------------------------------------
hoot info --subline-matchers
--------------------------------------

=== Subline String Matchers

The +--subline-string-matchers+ option prints out available subline string matchers that determine which method of multilinestring matching
is used during conflation.

==== Usage

--------------------------------------
info --subline-string-matchers
--------------------------------------

==== Example

--------------------------------------
hoot info --subline-string-matchers
--------------------------------------

=== String Comparators

The +--string-comparators+ option prints out available string comparators that can be used during conflation when comparing tag string values.

==== Usage

--------------------------------------
info --string-comparators
--------------------------------------

==== Example

--------------------------------------
hoot info --string-comparators
--------------------------------------

=== Tag Mergers

The +--tag-mergers+ option prints out available tag mergers that may be applied when conflating data.

==== Usage

--------------------------------------
info --tag-mergers
--------------------------------------

==== Example

--------------------------------------
hoot info --tag-mergers
--------------------------------------

==== Example

--------------------------------------
hoot info --tag-mergers
--------------------------------------

=== Value Aggregators

The +--value-aggregators+ option prints out available tag value aggregation methods that can be used when building a conflation model with
manually matched map training data.

==== Usage

--------------------------------------
info --value-aggregators
--------------------------------------

==== Example

--------------------------------------
hoot info --value-aggregators
--------------------------------------

=== Way Joiners

The +--way-joiners+ option prints out all way joiner class implementations that may either be used independently or in conjunction with
the OsmMapOperation, `hoot::WayJoinerOp`.

==== Usage

--------------------------------------
info --way-joiners
--------------------------------------

==== Example

--------------------------------------
hoot info --way-joiners
--------------------------------------

