== info

The +info+ command displays information about Hootenanny capabilities.  

For further detail on how to use this information see both the Hootenanny User and Developer Guides.

=== Option Overview

Only one of the following options can be passed to the command:

* +--cleaning-operations+     - Displays operations configured for cleaning map data
* +--config-options+          - Displays available configuration options
* +--feature-extractors+      - Displays available feature extractors used in conflation model building
* +--formats+                 - Displays supported data input/output formats
* +--languages+               - Displays information about translatable/detectable spoken languages
* +--matchers+                - Displays available feature matchers used during conflation
* +--mergers+                 - Displays available feature mergers used during conflation
* +--operators+               - Displays available inline operators that can be applied to map datasets
* +--string-comparators+      - Displays available string comparators
* +--subline-matchers+        - Displays available subline matchers
* +--subline-string-matchers+ - Displays available subline string matchers
* +--tag-mergers+             - Displays available feature tag mergers used during conflation
* +--value-aggregators+       - Displays available feature tag value aggregators used in conflation model building

Each of the following sections describes an option that may be used with this command and its input parameters.

=== Cleaning Operations

The +--cleaning-operations+ option prints out the currently configured map cleaning operations that are applied during conflation or with the
'clean' command.  The configuration option 'map.cleaner.transforms' controls which operators are applied

==== Usage

--------------------------------------
info --cleaning-operations
--------------------------------------

==== Example

--------------------------------------
hoot info --cleaning-operations
--------------------------------------

=== Configuration Options

The +--config-options+ option prints out available Hootenanny configuration options.

==== Input Parameters

One of the following input parameters must be specified:

* +name+             - name or partial name of a configuration option to list and/or print a description for
* +--option-names+   - if no name is specified, lists all configuration option names; if a name is specified, lists only 
                       configuration option names that have a full or partial match with the input name
* +--option-details+ - if no name is specified, lists all configuration option names and descriptions; if a name is specified, 
                       lists only configuration option names and descriptions that have a full or partial match with the input name

==== Usage

--------------------------------------
info --config-options [--option-names]
info --config-options [--option-details]
info --config-options (name) [--option-names]
info --config-options (name) [--option-details]
--------------------------------------

==== Example

--------------------------------------
# by default lists all config option names
hoot info --config-options

# list all config option names
hoot info --config-options --option-names

# list all config option names and their descriptions
hoot info --config-options --option-details

# list all config option names where the name contains the given string
hoot info --config-options poi.polygon --option-names

# list all config option names and their descriptions where the name contains the given string
hoot info --config-options poi.polygon --option-details
--------------------------------------

=== Feature Extractors

The +--feature-extractors+ option prints out available feature extractors that can be used when building a conflation model with 
manually matched map training data. 

==== Usage

--------------------------------------
info --feature-extractors
--------------------------------------

==== Example

--------------------------------------
hoot info --feature-extractors
--------------------------------------

=== Formats

The +--formats+ option prints out supported data formats.

==== Usage

--------------------------------------
info --formats [--input] [--output]
--------------------------------------

==== Example

--------------------------------------
# prints all
hoot info --formats

hoot info --format --input

hoot info --format --output
--------------------------------------

=== Languages

The +languages+ option displays information about Hootenanny language translation/detection capabilities.

All uses of the +languages+ command require the following configuration options to be populated: 
* hoot.services.auth.user.name
* hoot.services.auth.access.token
* hoot.services.auth.access.token.secret

For more information on logging into the web services, see the 'login' command documentation.  Those options are omitted from the 
following command examples.

Only one of the following options can be passed to the command:

* +--detectable+    - Prints all spoken languages that Hootenanny can detect and the detectors that can detect them
* +--detectors+     - Prints all available language detector implementations for the translation service
* +--translatable+  - Prints all spoken languages that Hootenanny translate from to English and the translators that can translate them
* +--translators+   - Prints all available language translator implementations for the translation service

The +--detectors+ option prints out all available language detectors that can be used with the Hootenanny web services.

==== Usage

--------------------------------------
info --languages --detectors
--------------------------------------

==== Example

--------------------------------------
hoot info --languages --detectors
--------------------------------------

The +--translators+ option prints out all available language translators that can be used with the Hootenanny web services.

==== Usage

--------------------------------------
info --languages --translators
--------------------------------------

==== Example

--------------------------------------
hoot info --languages --translators
--------------------------------------

The +--detectable+ option prints out spoken languages which Hootenanny can detect when using the Hootenanny web services.

==== Usage

--------------------------------------
info --languages --detectable
--------------------------------------

==== Example

--------------------------------------
hoot info --languages --detectable
--------------------------------------

The +--translatable+ option prints out spoken languages which Hootenanny can translate from to English when using the Hootenanny web 
services.

==== Usage

--------------------------------------
info --languages --translatable
--------------------------------------

==== Example

--------------------------------------
hoot info --languages --translatable
--------------------------------------

=== Matchers

The +--matchers+ option prints out available conflate matchers that may be applied when conflating data.

==== Usage

--------------------------------------
info --matchers
--------------------------------------

==== Example

--------------------------------------
hoot info --matchers
--------------------------------------

=== Mergers

The +--mergers+ option prints out available conflate mergers that may be applied when conflating data.

==== Usage

--------------------------------------
info --mergers
--------------------------------------

==== Example

--------------------------------------
hoot info --mergers
--------------------------------------

=== Operators

The +--operators+ option prints out available inline operators that can be applied to map data in a Hootenanny command.  Map operators
can be criterion, operations, or visitors.  

* An example of an operation is DuplicateWayRemover, which removes all duplicate ways from a map.  
* An example of a criterion is NodeCriterion, which acts as a filter to return all nodes in a map.  
* An example of a visitor is RemoveTagsVisitor, which removes selected tags from features in a map.

==== Usage

--------------------------------------
info --operators
--------------------------------------

==== Example

--------------------------------------
# lists all available operators
hoot info --operators

# criterion example - filters only nodes from the map to the output
hoot convert -D convert.ops="hoot::RemoveElementsVisitor" -D remove.elements.visitor.element.criterion="hoot::NodeCriterion" \ 
input1.osm input2.osm output.osm

# operation example - writes a map based on the input data with all duplicate ways removed
hoot convert -D convert.ops="hoot::DuplicateWayRemover" input1.osm input2.osm output.osm

# visitor example - writes a map based on the input data with all of the specified tags removed from the nodes
hoot convert -D convert.ops="hoot::RemoveTagsVisitor" -D remove.tags.visitor.element.criterion="hoot::WayCriterion" -D remove.tags.visitor.keys="source;error:circular" input1.osm input2.osm output.osm
--------------------------------------

=== Subline Matchers

The +--subline-matchers+ option prints out available subline matchers that determine which method of line matching is used during conflation. 

==== Usage

--------------------------------------
info --subline-matchers
--------------------------------------

==== Example

--------------------------------------
hoot info --subline-matchers
--------------------------------------

=== Subline String Matchers

The +--subline-string-matchers+ option prints out available subline string matchers that determine which method of multilinestring matching 
is used during conflation. 

==== Usage

--------------------------------------
info --subline-string-matchers
--------------------------------------

==== Example

--------------------------------------
hoot info --subline-string-matchers
--------------------------------------

=== String Comparators

The +--string-comparators+ option prints out available string comparators that can be used during conflation when comparing tag string values. 

==== Usage

--------------------------------------
info --string-comparators
--------------------------------------

==== Example

--------------------------------------
hoot info --string-comparators
--------------------------------------

=== Tag Mergers

The +--tag-mergers+ option prints out available tag mergers that may be applied when conflating data.

==== Usage

--------------------------------------
info --tag-mergers
--------------------------------------

==== Example

--------------------------------------
hoot info --tag-mergers
--------------------------------------

==== Example

--------------------------------------
hoot info --tag-mergers
--------------------------------------

=== Value Aggregators

The +--value-aggregators+ option prints out available tag value aggregation methods that can be used when building a conflation model with 
manually matched map training data. 

==== Usage

--------------------------------------
info --value-aggregators
--------------------------------------

==== Example

--------------------------------------
hoot info --value-aggregators
--------------------------------------

