== languages

The +languages+ command displays information about Hootenanny language translation/detection capabilities.  It makes use of the configuration
options named language.translation.* and requires that both the hoot-rnd and hoot-services libraries be loaded.  

Only one of the following options can be passed to the command:

* +--detectable+    - Prints all spoken languages that Hootenanny can detect and the detectors that can detect them
* +--detectors+     - Prints all available language detector implementations for the translation service
* +--translatable+  - Prints all spoken languages that Hootenanny translate from to English and the translators that can translate them
* +--translators+   - Prints all available language translator implementations for the translation service

=== Detectors

The +--detectors+ option prints out all available language detectors that can be used with the Hootenanny web services.

==== Usage

--------------------------------------
languages --detectors
--------------------------------------

==== Example

--------------------------------------
hoot languages --detectors
--------------------------------------

=== Translators

The +--translators+ option prints out all available language translators that can be used with the Hootenanny web services.

==== Usage

--------------------------------------
languages --translators
--------------------------------------

==== Example

--------------------------------------
hoot languages --translators
--------------------------------------

=== Detectable Languages

The +--detectable+ option prints out spoken languages which Hootenanny can detect when using the Hootenanny web services.

==== Usage

--------------------------------------
languages --detectable
--------------------------------------

==== Example

--------------------------------------
hoot languages --detectable
--------------------------------------

=== Translatable Languages

The +--translatable+ option prints out spoken languages which Hootenanny can translate from to English when using the Hootenanny web 
services.

==== Usage

--------------------------------------
languages --translatable
--------------------------------------

==== Example

--------------------------------------
hoot languages --translatable
--------------------------------------
