[[login]]
== login

The `login` command logs a user into the web services, and returns access tokens for use in command invocations. Some 
commands require web services authentication before use (e.g. `languages` command).

The access tokens retrieved after login, along with their associated user name, must be used as configuration options 
when using any Hootenanny commands requiring Hootenanny Web Services authentication:
* hoot.services.auth.user.name
* hoot.services.auth.access.token
* hoot.services.auth.access.token.secret

For the login command to work correctly, the oauthRedirectURL property for the web services in `hoot-services.conf` must 
be pointed to the page 'out-of-band.html' found in the web services application.  ee the Hootenanny OAuth documentation for 
more detail on the Hootenanny authentication process.

=== Usage

--------------------------------------
hoot login
--------------------------------------

=== Example

--------------------------------------
[vagrant@centos7-hoot hoot]$ hoot login

Authorization URL: https://www.openstreetmap.org/oauth/authorize?oauth_token=xSpqQk

1. Using the authorization URL shown above, authenticate through the 3rd party application.
2. Grant Hootenanny access to the application.
3. Copy and paste your verifier code from the browser here and press ENTER: E50JtUb

user name=icenine18
oauth_token=xIhWho
oauth_token_secret=GTSwRn

Use the above information with all Hootenanny commands that require use of the Hootenanny Web Services:
-D hoot.services.auth.user.name=icenine18
-D hoot.services.auth.access.token=xIhWho
-D hoot.services.auth.access.token.secret=GTSwRn
--------------------------------------
