== login

The +login+ command logs a user into the Hootenanny application, authenticating via the Hootenanny Web Services, and returns Hootenanny 
access tokens for use in command invocations.  Some commands require Hootenanny authentication before use (e.g. 'languages' command). 

The access tokens retrieved after login, along with their associted user name, must be used as configuration options when using any 
commands requiring Hootenanny authentication:
* hoot.services.auth.user.name
* hoot.services.auth.access.token
* hoot.services.auth.access.token.secret

For the login command to work correctly, the oauthRedirectURL property for the Hootenanny Web Services in hoot-services.conf must be pointed 
to the page 'out-of-band.html' found in Hootenanny's iD Editor application.  See the Hootenanny OAuth documentation for more detail on the 
Hootenanny authentication process.

=== Usage

--------------------------------------
login
--------------------------------------

=== Example

--------------------------------------
$ hoot login

Authorization URL: https://www.openstreetmap.org/oauth/authorize?oauth_token=sUGfkaRnEaFoOfsdAILgZWcUb4VhZkdonQMz67BT

Using the authorization URL shown above, authenticate through the 3rd party application, grant Hootenanny access to it, then enter your 
verifier code here and press ENTER: lHhO73e7NaPNZlmKop6j

oauth_token=pAJaKkZzsR8sE0cyfHc7oUgW5VOr32YEyYdT8OKN
oauth_token_secret=78djJKrgOGlfVPqsc0wGlMCpKVar1LUrBs3DunRM
--------------------------------------
