== multiary-ingest

=== Description

Ingests POI data for use by Multiary Conflation by calculating the difference between new and existing data

* +newInput+ - path to a supported Hootenanny data format; the format must be streamable (see README.md 
               "Supported Data Formats"); only POIs will be read and all will be translated to the OSM format
* +referenceOutput+ - path to reference data; must be a Hootenanny API database layer; if the layer does not exist, it will
                      be created 
* +changesetOutput+ - path where to write the resulting changeset changes; must be a Spark changeset
* +sortInput+ - If true, +newInput+ will be sorted by element ID; may disable this to increase performance if +newInput+
                has already been sorted by element ID.  If set to false and +newInput+ has not been sorted by element
                ID, the changeset derivation will fail.

=== Usage

--------------------------------------
multiary-ingest (newInput) (referenceOutput) (changesetOutput) (sortInput)
--------------------------------------

==== Example

--------------------------------------
hoot multiary-ingest newData.geonames hootapidb://hoot:hoottest@localhost:5432/hoot/ReferenceLayer changeset.spark.1 true
--------------------------------------

