[[node-density-tiles]]
== node-density-tiles

=== Description

The +node-density-tiles+ command calculates a collection of bounding boxes that contain roughly equal distributions of node data from
the specified input(s) and writes the output to a file.

* +input(s)+            - One or more inputs; may be any supported input format (e.g. OSM file). Specify multiple inputs by separating them 
                          with a semicolon.
* +output+              - Output file to write the tile boundaries to; must be GeoJSON (*.geojson) or OSM (*.osm).
* +maxNodeCountPerTile+ - The maximum number of nodes in any tile; optional only if pixelSize is not specified. The default is 1000. If the 
                          specified value is less than the number of nodes in the input data, then a single bounding box containing all of the 
                          data is output. If a solution cannot be found, this value may be automatically increased in order to find one.
* +pixelSize+           - The size of the pixel used in the calculation in degrees; optional only if maxNodeCountPerTile is not specified. The 
                          default is 0.001. If a solution cannot be found, this value may be automatically decreased in order to find one.
* +random-seed+         - Seeds the random number generator for consistent tile boundary selection; valid only if --random is specified;
                          use -1 for pseudo-random seeding; defaults to -1
* +--random+            - Selects a single random tile from those calculated

If too low a value is specified for maxNodeCountPerTile or too high a value is specified for pixelSize, the algorithm used may not be able
to find a solution.

This command makes use of the optional 'convert.bounding.box' configuration option to allow for calculating tiles against a subset of the 
input data. To make use of the option the reader for the specified input data must support bounded reading. To list the Hootenanny input 
formats that support bounded reading:
-----
hoot info --formats --input-bounded
-----

=== Usage

--------------------------------------
hoot node-density-tiles (input1.osm)[;input2.osm...] (output) [maxNodeCountPerTile] [pixelSize] [random-seed] [--random]
--------------------------------------

=== Examples

Calculate tiles based on node density:

--------------------------------------
hoot node-density-tiles test-files/MyInputFile.osm MyOutputFile.geojson
--------------------------------------

Calculate tiles based on node density, specifying the maximum allowed node count per tile and a pixel size:

--------------------------------------
hoot node-density-tiles "test-files/MyInputFile1.osm;test-files/MyInputFile2.osm" MyOutputFile.geojson 1000 0.001
--------------------------------------

Calculate tiles based on node density, narrowing down to a subset of the data specified by a bounding box:

--------------------------------------
hoot node-density-tiles -D convert.bounding.box="34.04,31.17,34.05,31.18" hootapidb://hoot:hoottest@localhost:5432/hoot/MyInputDb MyOutputFile.geojson
--------------------------------------

Select a random tile based on node density:

--------------------------------------
hoot node-density-tiles test-files/MyInputFile.osm MyOutputFile.geojson --random
--------------------------------------

Select a random tile based on node density specifying a particular seed for the random number generator:

--------------------------------------
hoot node-density-tiles test-files/MyInputFile.osm MyOutputFile.geojson 1000 0.001 2 --random
--------------------------------------

=== See Also

* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]
