== perty

=== Description

The +perty+ command permutes data.  It reads from input, permutes the data, and
writes to output files. The +perty+ command is based on the paper, "Evaluating
conflation methods using uncertainty modeling," P. Doucette, et. al, 2012. 

* +input+ - Input (e.g. .osm file).
* +output+ - Output file (e.g. .osm file).

=== Optional Defines

See the Configuration Options section for details on these configuration
parameters can be used with this command:

* +perty.algorithm+
* +perty.csm.beta+
* +perty.csm.D+
* +perty.grid.spacing+
* +perty.ops+
* +perty.random.error.x+
* +perty.random.error.y+
* +perty.remove.tag.visitor.exempt.tag.keys+
* +perty.remove.tag.visitor.substitution.keys+
* +perty.remove.tag.visitor.substitution.values+
* +perty.search.distance+
* +perty.seed+
* +perty.systematic.error.x+
* +perty.systematic.error.y+
* +perty.way.generalize.epsilon+
* +perty.way.generalize.probability+
* +perty.way.split.min.node.spacing+
* +perty.way.split.probability+

=== Usage

--------------------------------------
perty (input) (output)
--------------------------------------

=== Example

The following example perturbs the file "reference-in.osm", given the specified
PERTY options (overrides default settings for those options), and writes the
perturbed data to a file "perturbed-out.osm":

--------------------------------------
hoot perty -D perty.search.distance=20 -D perty.way.generalize.probability=0.7
  reference-in.osm perturbed-out.osm
--------------------------------------

