[[score-matches]]
== score-matches

=== Description

The +score-matches+ command scores how well conflation performs using manually matched data as a reference.  It validates 
manual matches, conflates using unify, and scores the matches created during conflation against the manual matches. The 
command will return an error if any manual match is invalid.

* +input1+            - Input that contains REF1 data (no manual matches); may be any supported input format (e.g. OSM file).
* +input2+            - Input that contains REF2 or REVIEW data (has manual mathces); may be any supported input format 
                        (e.g. OSM file).
* +output+            - Output file for debugging; may be any supported output format (e.g. OSM file). Only the first 
                        conflation will be output.
* +--confusion+       - print the confusion matrix
* +--optimize+        - optimizes the scoring function
* +--validation-off+  - Turns off manual match validation; recommended for debugging manual matches only

=== Usage

--------------------------------------
score-matches [--confusion] [--optimize] [--validation-off] (input1 input2) [input1 input2 ...] (output)
--------------------------------------

=== Examples

--------------------------------------
# Displays match scores
hoot score-matches --confusion --optimize input1.osm input2.osm output.osm

# Writes match scoring to a file
hoot score-matches --confusion input1.osm input2.osm output.osm
--------------------------------------

=== See Also

* <<hootDevGuide, HootenannyManualConflation>>
* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]

