== score-map

=== Description

The +score-map+ command compares a map (uut, Unit Under Test) to one or two test maps (base1 & base2) and prints out three 
score metrics. This operation is most commonly used to compare manually conflated data to the automatically conflated data. 
The scores provided give an idea of similarity between maps. A score of 1000 means they're exactly the same. A score of 
0 means the maps are very different.

* +base1+ - The first base file to compare against.
* +base2+ - (optional) The second base file to compare against.
* +uut+   - The file being evaluated.

The following variables are provided in the score result:

* Raster Score (AKA Location & Completeness) - A metric describing how complete the data is and how close the features are together
* Graph Score (AKA Routing)                  - A metric describing how close similar the maps would be if used to perform routing analytics
* Attribute Score                            - A metric describing how similar the attributes are between the two maps

=== Usage

--------------------------------------
score-map (base1) [base2] (uut)
--------------------------------------

==== Example

--------------------------------------
hoot score-map manual1.osm manual2.osm conflated.osm
Attribute Score 1: 981 +/-5
Attribute Score 2: 993 +/-3
Attribute Score: 987 +/-4 (983 to 991)
Raster Score 1: 982
Raster Score 2: 989
Raster Score: 986
Graph Score 1: 944 +/-19 (925 to 963)
Graph Score 2: 996 +/-0 (996 to 996)
Graph Score: 970 +/-10 (960 to 980)
Overall: 981 +/-4 (977 to 985)
--------------------------------------

