[[split]]
== split

=== Description

The `split` command splits a map into multiple parts. 

It reads in tile boundaries, uses them to process a map, and writes out multiple maps. One map is written for each tile in 
the tile boundary containing only the elements that reside within that boundary. For elements that span multiple boundaries, 
the geospatial envelope of the element is compared to all tiles it intersects and they are stored in the one that contains the 
highest percentage of overlap.

* `tiles`  - Tile map; may be any supported input format (e.g. .osm file). For use with tile maps generated by the
             https://github.com/ngageoint/hootenanny/blob/master/docs/commands/task-grid.asciidoc[task-grid] command.
* `input`  - Input; may be any supported input format (e.g. .osm file).
* `output` - Output; may be any suppported output format (e.g. .osm file). The output will consist of 'n' number 
             of output files where 'n' is the number of tiles in the `tiles` map. Each resulting map will contain only 
             the elements whose geospatial envelope is mostly contained by the tile.

=== Usage

--------------------------------------
hoot split (tiles) (input) (output)
--------------------------------------

https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#split-a-map-into-multiple-maps-using-tiles-from-a-file[Examples]

=== See Also

* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]
* https://github.com/ngageoint/hootenanny/blob/master/docs/commands/grid-node-density.asciidoc[grid-node-density Command]
