[[stat]]
== stat

=== Description

The +stat+ command displays a single statistic calculated from the features in a map.

* +input(s)+    - One or more inputs; may be any supported input format (e.g. .osm file). If statType is 'average', then 
                  only one input is supported.
* +visitor+     - The stat visitor must be the single class name of a Hootenanny visitor that inherits from 
                  +ElementVisitor+ and supports the +SingleStatistic+ or +NumericStatistic+ interfaces. Use the 
                  +info --operators+ command to obtain a list of available visitors.
* +statType+    - If +visitor+ supports `NumericStatistic`, this optional parameter allows for specifying the statistic type 
                  to collect. Supported types are 'total', 'min', 'max', and 'average'. If +visitor+ implements 
                  `SingleStatistic`, this parameter is ignored and 'total' is automatically used.
* +--recursive+ - Allows for calculating a statistic against elements recursively in a directory structure. This must 
                  be followed by either "*" to denote no filtering or one or more wildcard name filters. e.g. "*.osm;*.json" 
                  or "*myFile*". The recursion is only performed on file directories and this parameter is ignored 
                  for other input types.

=== Usage

--------------------------------------
hoot stat ("input1;input2...") (visitor) [statType] [--recursive]
--------------------------------------

https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#calculate-the-area-of-all-features-in-a-map[Examples]

=== See Also

* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]

