[[stat]]
== stat

=== Description

The +stat+ command displays a single statistic calculated from the features in a map.

* +input(s)+    - Input(s); may be any supported input format (e.g. .osm file).
* +visitor+     - The stat visitor must be the single class name of a Hootenanny visitor that inherits from 
                  +ConstElementVisitor+ and supports the +SingleStatistic+ or +NumericStatistic+ interfaces. Use the 
                  +info --operators+ command to obtain a list of available visitors.
* +--recursive+ - Allows for processing inputs recursively in a directory structure. This must be followed by either "*" 
                  to denote no filtering or one or more wildcard name filters. e.g. "*.osm;*.json" or "*myFile*".
* +--statType+  - If +visitor+ implements `NumericStatistic`, this optional parameter allows for specifying the statistic type 
                  to collect. Supported types are 'total', 'min', 'max', and 'average'. If +visitor+ implements 
                  `SingleStatistic`, this parameter is ignored and 'total' is automatically used.

=== Usage

--------------------------------------
hoot stat (input1) [input2...] (visitor) [--recursive "*"|"filter1;filter2..."] [--statType type]
--------------------------------------

https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#calculate-the-area-of-all-features-in-a-map[Examples]

=== See Also

* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]

