[[tag-info]]
== tag-info

=== Description

The +tag-info+ command prints out unique feature tag values grouped by tag key. This command works on streamable inputs only.

* +inputs+              - One or more inputs; may be any supported input format (e.g. OSM file).  If using an OGR layer within 
                          a data source, then delimit the data source and layer with a semicolon.
* +--tag-values-limit+  - Limits the number of unique tag values printed per tag key.  By default, there is no limit.  This 
                          option is ignored if --keys-only is specified.
* +--keys+              - Prints unique tag values for the specified keys only.  Delimit multiple keys with a semicolon 
                          (e.g. "key1;key2"). This option is ignored if --keys-only is specified.
* +--keys-only+         - Prints tag keys only and does not print any associated values.
* +--case-insensitive+  - If this option is specified, tag key comparisons are not case sensitive.  By default the comparisons 
                          are case sensitive.
* +--partial-key-match+ - If this option is specified, then any key in a feature which partially matches the given set of keys 
                          in --keys will have its tag value added to the output.  By default, keys must be an exact match 
                          with each other for the tag value to be written to output.
* +--delimited-text+    - By default, JSON output is generated. If this option is specified, a delimited list with the format
                          "key1;key2..." is returned. Value when the +--keys-only+ option is used only.

=== Usage

--------------------------------------
tag-info (input1[;layer]) [input2[;layer]] ... [--tag-values-limit] [--keys-only "key1;key2..."] [--keys-only] [--case-insensitive] [--delimited-text]
--------------------------------------

* [Examples](https://github.com/ngageoint/hootenanny/blob/master/docs/user/CommandLineExamples.asciidoc#display-tag-schema-information-for-a-map)

=== See Also

* https://github.com/ngageoint/hootenanny/blob/master/docs/user/SupportedDataFormats.asciidoc#applying-changes-1[Supported Input Formats]

