== type-tagger-create-rules-db

=== Description

The +type-tagger-create-rules-db+ command, given a raw implicit tag rules file created by the +type-tagger-create-rules+ command, 
allows for filtering the implicit tag rules and writing them to a database.  The database can then be used to add tags implicitly 
to elements, given their names.  See the "Implicit Element Type Tagging Based On Name" section in the Hootenanny User Guide for 
more information.

* +input+       - an .implicitTagRules tab delimited rules for input
* +output+      - a .sqlite database file for output
* +--stats+	- if specified, prints the statistics of an existing .sqlite database; the only other input parameter 
                  required with +--stats+ is +input+

Relevant configuration options are those beginning with implicit.tagging.database.deriver.* and in some cases those beginning with 
implicit.tagging.*, in conf/core/ConfigOptions.asciidoc.

=== Usage

--------------------------------------
type-tagger-create-rules-db (input) (output)

type-tagger-create-rules-db (input) (--stats)
--------------------------------------

==== Examples

--------------------------------------
hoot type-tagger-create-rules-db myInput.implicitTagRules implicitTagRules.sqlite

hoot type-tagger-create-rules-db implicitTagRules.sqlite --stats
--------------------------------------

