== big-cookie-cut

NOTE: This documents Hootenanny conflation using Hadoop, which is no longer supported (supported up to v0.2.38), and has been 
left here for references purposes only.

=== Description

The +big-cookie-cut+ command reads in a OSM input file as the 'cutter-shape'
and removes the cookie cutter shape from the contents of the 'dough' file. The
resulting geometries are written to 'output'.  You may be able to use the alpha-shape 
command to generate a polygon using alpha shapes (see the alpha-shape command for more details).  
big-cookie-cut is an alternative to
the cookie-cut command that can handle arbitrarily large input files (dough)
by cutting the data using a Four Pass operation.

* +cutter-shape+ - The input Polygons to use as the cutter shape. This must
  reside on the local file system and must easily fit in RAM.
* +dough.osm.pbf+ - The input OSM data to cut from. This is the data that will
  be cut and written out. This must reside on HDFS.
* +output.osm.pbf+ - The output OSM data path. This must reside on HDFS.
* +buffer+ - Optional buffer value, if the buffer value is provided then the
  shape is buffered by this many meters before cutting. The buffer may be
  positive or negative.
* +--local+ - Runs the job locally rather than using Hadoop.
* +--crop+ - Crops based on the polygon rather than doing a cookie cut.

=== Usage

--------------------------------------
big-cookie-cut (cutter-shape) (dough.osm.pbf) (output.osm.pbf) [buffer]
[--local] [--crop]
--------------------------------------

==== Example 1

Simply remove all the data that intersects any polygon in the Shapefile.
Elements are intelligently cut such that only the pieces that intersect the
polygons are removed.

--------------------------------------
hoot big-cookie-cut CapitalHeightsShape.shp DcGisRoads.osm.pbf \
  DcGisRoadsCut.osm.pbf 
--------------------------------------

==== Example 2

Below is a more comprehensive example to remove an approximation of the Capital
Heights region from DC GIS Roads using a number of commands.

--------------------------------------
# Calculate a good cookie cutter using an alpha shape.
hoot cookie-cut CapitalHeightsBuildings.shp 200 0 CapitalHeightsShape.shp

# Create a directory on HDFS to store the DcGisRoad data
hadoop fs -mkdir dc-gis-roads.osm.pbf

# Put the DcGisRoad data in the new directory.
hadoop fs -put DcGisRoad.osm.pbf dc-gis-roads.osm.pbf/Input.osm.pbf

# Remove Capital Heights from the DcGisRoad data and put the result in the
# `no-capital-heights.osm.pbf` directory
hoot big-cookie-cut CapitalHeightsShape.shp dc-gis-roads.osm.pbf \
  no-capital-heights.osm.pbf 

# Concatenate the files in our output directory and put them in a properly
# formatted, but unsorted .osm.pbf.
hadoop fs -cat no-capital-heights.osm.pbf/*.pbf | hoot add-pbf-header - \
  NoCapitalHeights.osm.pbf

# Optionally, sort the .osm.pbf so it can be used by tools like osm2pgsql
osmosis --read-pbf NoCapitalHeights.osm.pbf --sort --write-pbf \
  omitmetadata=true NoCapitalHeightsSorted.osm.pbf
--------------------------------------

