spring.security.oauth2.client.registration.osm.client-name=osm
spring.security.oauth2.client.registration.osm.provider=osm
spring.security.oauth2.client.registration.osm.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.osm.client-id=A45ZzLD_huFbThA5yyXDsw0e8ZGXbUTStwpSFkZ0Aws
spring.security.oauth2.client.registration.osm.client-secret=9XeaAWnRZuNgdPus4EEzZFLia4rPkkxke00_K8-CM3A
spring.security.oauth2.client.registration.osm.redirect-uri=https://localhost:8080/login.html
# spring.security.oauth2.client.registration.osm.redirect-uri=https://localhost:8443/hootenanny-id/login.html
spring.security.oauth2.client.registration.osm.scope=read_prefs
spring.security.oauth2.client.provider.osm.user-info-uri=http://mapedit-osm-web-1/api/0.6/user/details.json
spring.security.oauth2.client.provider.osm.token-uri=http://mapedit-osm-web-1:3000/oauth2/token
spring.security.oauth2.client.provider.osm.authorization-uri=http://localhost:3000/oauth2/authorize
