#!/usr/bin/perl -w

use strict;

if ( scalar(@ARGV) != 1 )
{
  print( "Usage: createSqlUploadPhases <SQL file>\n\n");
  exit;
}

my $sqlFile = shift(@ARGV);

my $grepOutput = `grep -nE \"^\\\\\\\\.\" $sqlFile`;

#print( "Grep output:\n$grepOutput\n" );

my @grepLines = split( /\n/, $grepOutput );

my @sectionPhases = (
  1,    # 1: sequences, users
  2,    # 2: changesets
  3,    # 3: current_nodes
  4,    # 4: current_node_tags
  3,    # 5: nodes
  4,    # 6: node_tags
  3,    # 7: current_ways
  4,    # 8: current_way_nodes
  4,    # 9: current_way_tags
  3,    # 10: ways
  4,    # 11: way_nodes
  4,    # 12: way_tags
  3,    # 13: current_relations
  4,    # 14: current_relation_members
  4,    # 15: current_relation_tags
  3,    # 16: relations
  4,    # 17: relation_members
  4     # 18: relation_tags
);

my @sectionNames = (
  '01_sequences_users',
  '02_changesets',
  '03_current_nodes',
  '04_current_node_tags',
  '05_nodes',
  '06_node_tags',
  '07_current_ways',
  '08_current_way_nodes',
  '09_current_way_tags',
  '10_ways',
  '11_way_nodes',
  '12_way_tags',
  '13_current_relations',
  '14_current_relation_members',
  '15_current_relation_tags',
  '16_relations',
  '17_relation_members',
  '18_relation_tags'
);

my $numberOfPhases = 4;

if ( -d 'sql_phases' )
{
  print("Phase subdirectories already exist. Delete and then re-run script\n\n" );
}

mkdir( 'sql_phases' );

my @sectionEndLines;

for ( my $sectionNum = 0; $sectionNum < scalar( @grepLines ); ++$sectionNum )
{
  ( my $endLine, my $terminator ) = split( /:/, $grepLines[$sectionNum] );

  my $startLine;
  if ( $sectionNum == 0 )
  {
    $startLine = 1;
  }
  else 
  {
    $startLine = $sectionEndLines[$sectionNum - 1] + 1;
  }

  $sectionEndLines[$sectionNum] = $endLine;

  print( sprintf("Section %27s: %12d - %12d (phase %d)\n", $sectionNames[$sectionNum], $startLine, $sectionEndLines[$sectionNum],
    $sectionPhases[$sectionNum] ) );        

  if ( ! -d "sql_phases/$sectionPhases[$sectionNum]" )
  {
    mkdir( "sql_phases/$sectionPhases[$sectionNum]" );
  }

  my $sectionLines = $sectionEndLines[$sectionNum] - $startLine + 1;

  my $createSectionFileCmd = 
    "tail -n+$startLine $sqlFile | head -n+$sectionLines > phases/$sectionPhases[$sectionNum]/$sectionNames[$sectionNum]";

 print( "$createSectionFileCmd\n" );

}



