/*
 * This file is part of Hootenanny.
 *
 * Hootenanny is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * --------------------------------------------------------------------
 *
 * The following copyright notices are generated automatically. If you
 * have a new notice to add, please use the format:
 * " * @copyright Copyright ..."
 * This will properly maintain the copyright information. DigitalGlobe
 * copyrights will be updated automatically.
 *
 * @copyright Copyright (C) 2012, 2013 DigitalGlobe (http://www.digitalglobe.com/)
 */

 ////
 // This file is automatically generated. Please do not modify the file
 // directly.
 ////
 

var _global = (0, eval)('this');
if (!_global.hgis20)
{
  _global.hgis20 = {};
}

hgis20.schema = {
//  Schema built from conf/nfdd/TDSv60.csv.gz and conf/nfdd/TDS_NGAv01.csv.gz
getDbSchema: function()
{

//           geom:"Area",
//           geom:"Line",

    var schema = [
        { name:"Agriculture_POI",
          desc:"Agriculture POI",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"NAME",desc:"NAME",length:"100",type:"String",defValue:""}, // End of NAME
                   { name:"TYPE1",desc:"TYPE1",length:"30",type:"String",defValue:""}, // End of TYPE1
                   { name:"TYPE2",desc:"TYPE2",length:"30",type:"String",defValue:""}, // End of TYPE2
                   { name:"CITY",desc:"CITY",length:"50",type:"String",defValue:""}, // End of CITY
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Agriculture_POI
        { name:"Airfields",
          desc:"Airfields",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"NAME",desc:"NAME",length:"100",type:"String",defValue:""}, // End of NAME
                   { name:"TYPE",desc:"TYPE",length:"30",type:"String",defValue:""}, // End of TYPE
                   { name:"ICAO",desc:"ICAO",length:"6",type:"String",defValue:""}, // End of ICAO
                   { name:"IATA",desc:"IATA",length:"10",type:"String",defValue:""}, // End of IATA
                   { name:"RUNWAY",desc:"RUNWAY",length:"10",type:"String",defValue:""}, // End of RUNWAY
                   { name:"N_RUNWAYS",desc:"N_RUNWAYS",type:"Real",defValue:"0"}, // End of N_RUNWAYS
                   { name:"R1_SURFACE",desc:"R1_SURFACE",length:"15",type:"String",defValue:""}, // End of R1_SURFACE
                   { name:"R2_SURFACE",desc:"R2_SURFACE",length:"15",type:"String",defValue:""}, // End of R2_SURFACE
                   { name:"R_LENGTH",desc:"R_LENGTH",type:"Real",defValue:"0"}, // End of R_LENGTH
                   { name:"R_WIDTH",desc:"R_WIDTH",type:"Real",defValue:"0"}, // End of R_WIDTH
                   { name:"USE",desc:"USE",length:"13",type:"String",defValue:""}, // End of USE
                   { name:"CUSTOMS",desc:"CUSTOMS",length:"6",type:"String",defValue:""}, // End of CUSTOMS
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Airfields
        { name:"Border_Crossings",
          desc:"Border Crossings",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"NAME",desc:"NAME",length:"100",type:"String",defValue:""}, // End of NAME
                   { name:"TYPE1",desc:"TYPE1",length:"30",type:"String",defValue:""}, // End of TYPE1
                   { name:"TYPE2",desc:"TYPE2",length:"30",type:"String",defValue:""}, // End of TYPE2
                   { name:"COUNTRY",desc:"COUNTRY",length:"50",type:"String",defValue:""}, // End of COUNTRY
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Border_Crossings
        { name:"Bridges_Tunnels",
          desc:"Bridges and Tunnels",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"NAME",desc:"NAME",length:"50",type:"String",defValue:""}, // End of NAME
                   { name:"CITY",desc:"CITY",length:"75",type:"String",defValue:""}, // End of CITY
                   { name:"TYPE1",desc:"TYPE1",length:"15",type:"String",defValue:""}, // End of TYPE1
                   { name:"TYPE2",desc:"TYPE2",length:"25",type:"String",defValue:""}, // End of TYPE2
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Bridges_Tunnels
        { name:"Commercial_POI",
          desc:"Commercial POI",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"NAME",desc:"NAME",length:"100",type:"String",defValue:""}, // End of NAME
                   { name:"TYPE1",desc:"TYPE1",length:"30",type:"String",defValue:""}, // End of TYPE1
                   { name:"TYPE2",desc:"TYPE2",length:"25",type:"String",defValue:""}, // End of TYPE2
                   { name:"CITY",desc:"CITY",length:"50",type:"String",defValue:""}, // End of CITY
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Commercial_POI
        { name:"Conflict_Points",
          desc:"Conflict Points",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"LOCATION",desc:"LOCATION",length:"100",type:"String",defValue:""}, // End of LOCATION
                   { name:"ACTOR1",desc:"ACTOR1",length:"50",type:"String",defValue:""}, // End of ACTOR1
                   { name:"ACTOR2",desc:"ACTOR2",length:"50",type:"String",defValue:""}, // End of ACTOR2
                   { name:"EVENT_TYPE",desc:"EVENT_TYPE",length:"75",type:"String",defValue:""}, // End of EVENT_TYPE
                   { name:"DATE",desc:"DATE",length:"20",type:"String",defValue:""}, // End of DATE
                   { name:"YEAR",desc:"YEAR",type:"REAL",defValue:"0"}, // End of YEAR
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"ORG_SOURCE",desc:"ORG_SOURCE",length:"50",type:"String",defValue:""}, // End of ORG_SOURCE
                   { name:"NUM_DTH",desc:"NUM_DTH",type:"REAL",defValue:"0"}, // End of NUM_DTH
                   { name:"NUM_INJ",desc:"NUM_INJ",type:"REAL",defValue:"0"}, // End of NUM_INJ
                   { name:"YEAR",desc:"YEAR",length:"50",type:"REAL"}, // End of YEAR
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Conflict_Points
        { name:"Crime_Data",
          desc:"Crime Data",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"ACTOR",desc:"ACTOR",length:"100",type:"String",defValue:""}, // End of ACTOR
                   { name:"TYPE",desc:"TYPE",length:"50",type:"String",defValue:""}, // End of TYPE
                   { name:"CITY",desc:"CITY",length:"100",type:"String",defValue:""}, // End of CITY
                   { name:"DATE",desc:"DATE",length:"20",type:"String",defValue:""}, // End of DATE
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Crime_Data
        { name:"Cultural_POI",
          desc:"Cultural Points of Interest",
          geom:"Point",
          columns:[ 
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"NAME",desc:"NAME",length:"100",type:"String",defValue:""}, // End of NAME
                   { name:"TYPE",desc:"TYPE",length:"30",type:"String",defValue:""}, // End of TYPE
                   { name:"CITY",desc:"CITY",length:"50",type:"String",defValue:""}, // End of CITY
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Cultural_POI

        { name:"Embassies",
          desc:"Embassies",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"NAME",desc:"NAME",length:"50",type:"String",defValue:""}, // End of NAME
                   { name:"ADDRESS",desc:"ADDRESS",length:"150",type:"String",defValue:""}, // End of ADDRESS
                   { name:"CITY",desc:"CITY",length:"100",type:"String",defValue:""}, // End of CITY
                   { name:"TYPE",desc:"TYPE",length:"30",type:"String",defValue:""}, // End of TYPE
                   { name:"TELEPHONE",desc:"TELEPHONE",length:"30",type:"String",defValue:""}, // End of TELEPHONE
                   { name:"WEBSITE",desc:"WEBSITE",length:"175",type:"String",defValue:""}, // End of WEBSITE
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Embassies

        { name:"Geonames",
          desc:"Geonames",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"FC",desc:"FC",length:"2",type:"String",defValue:""}, // End of FC
                   { name:"DSG",desc:"DSG",length:"5",type:"String",defValue:""}, // End of DSG
                   { name:"SORT_NAME",desc:"SORT_NAME",length:"150",type:"String",defValue:""}, // End of SORT_NAME
                   { name:"FULL_NAME",desc:"FULL_NAME",length:"150",type:"String",defValue:""}, // End of FULL_NAME
                   { name:"ALT_NAME",desc:"ALT_NAME",length:"254",type:"String",defValue:""}, // End of ALT_NAME
                   { name:"MODIFY_DT",desc:"MODIFY_DT",length:"20",type:"String",defValue:"" }, // End of MODIFY_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                  ] // End of Columns
        }, // End of feature Geonames





        { name:"Medical_Facilities",
          desc:"Medical Facilities",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"NAME",desc:"NAME",length:"100",type:"String",defValue:""}, // End of NAME
                   { name:"TYPE1",desc:"TYPE1",length:"30",type:"String",defValue:""}, // End of TYPE
                   { name:"TYPE2",desc:"TYPE2",length:"30",type:"String",defValue:""}, // End of TYPE
                   { name:"CITY",desc:"CITY",length:"50",type:"String",defValue:""}, // End of CITY
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Medical_Facilities


        { name:"Natural_POI",
          desc:"Natural POI",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"NAME",desc:"NAME",length:"100",type:"String",defValue:""}, // End of NAME
                   { name:"TYPE",desc:"TYPE",length:"30",type:"String",defValue:""}, // End of TYPE
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Natural_POI


        { name:"Recreation_POI",
          desc:"Recreation POI",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"NAME",desc:"NAME",length:"100",type:"String",defValue:""}, // End of NAME
                   { name:"TYPE",desc:"TYPE",length:"30",type:"String",defValue:""}, // End of TYPE
                   { name:"CITY",desc:"CITY",length:"50",type:"String",defValue:""}, // End of CITY
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Recreation_POI


        { name:"Religious_Institutions",
          desc:"Religious Institutions",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"NAME",desc:"NAME",length:"50",type:"String",defValue:""}, // End of NAME
                   { name:"TYPE",desc:"TYPE",length:"30",type:"String",defValue:""}, // End of TYPE
                   { name:"CITY",desc:"CITY",length:"50",type:"String",defValue:""}, // End of CITY
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Religious_Institutions


        { name:"Tourist_Locations_POI",
          desc:"Tourist Attractions",
          geom:"Point",
          columns:[
                   { name:"ISO3",desc:"ISO3",length:"3",type:"String",defValue:"" }, // End of ISO3
                   { name:"ADM0_NAME",desc:"ADM0_NAME",length:"50",type:"String",defValue:""}, // End of ADM0_NAME
                   { name:"ADM1_NAME",desc:"ADM1_NAME",length:"50",type:"String",defValue:""}, // End of ADM1_NAME
                   { name:"ADM2_NAME",desc:"ADM2_NAME",length:"50",type:"String",defValue:""}, // End of ADM2_NAME
                   { name:"ADM3_NAME",desc:"ADM3_NAME",length:"50",type:"String",defValue:""}, // End of ADM3_NAME
                   { name:"ADM4_NAME",desc:"ADM4_NAME",length:"50",type:"String",defValue:""}, // End of ADM4_NAME
                   { name:"ADM5_NAME",desc:"ADM5_NAME",length:"50",type:"String",defValue:""}, // End of ADM5_NAME
                   { name:"NAME",desc:"NAME",length:"100",type:"String",defValue:""}, // End of NAME
                   { name:"TYPE",desc:"TYPE",length:"35",type:"String",defValue:""}, // End of TYPE
                   { name:"CITY",desc:"CITY",length:"50",type:"String",defValue:""}, // End of CITY
                   { name:"SPA_ACC",desc:"SPA_ACC",length:"8",type:"String",defValue:""}, // End of SPA_ACC
                   { name:"CONF_IMAGE",desc:"CONF_IMAGE",length:"12",type:"String",defValue:""}, // End of CONF_IMAGE
                   { name:"COMMENTS",desc:"COMMENTS",length:"150",type:"String",defValue:""}, // End of COMMENTS
                   { name:"SOURCE_DT",desc:"SOURCE_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE_DT
                   { name:"SOURCE",desc:"SOURCE",length:"125",type:"String",defValue:"" }, // End of SOURCE
                   { name:"SOURCE2_DT",desc:"SOURCE2_DT",length:"20",type:"String",defValue:"" }, // End of SOURCE2_DT
                   { name:"SOURCE2",desc:"SOURCE2",length:"125",type:"String",defValue:"" }, // End of SOURCE2
                  ] // End of Columns
        }, // End of feature Tourist_Locations_POI


    ]; // End of schema

    return schema;

} // End of getDbSchema

} // End of hgis20.schema


exports.getDbSchema = hgis20.schema.getDbSchema;

