#!/bin/bash
set -e

# This tests that any review relations with references to members missing in the data, either passed into or generated by changeset
# replacement derivation do not crash it. It is specifically being run with conflation enabled.

IN_DIR=test-files/cmd/slow/ChangesetReplacementInvalidReviewRelationTest
OUT_DIR=test-output/cmd/slow/ChangesetReplacementInvalidReviewRelationTest
mkdir -p $OUT_DIR

CONFIG="--warn -C Testing.conf"

hoot changeset-derive-replacement $CONFIG -D writer.include.debug.tags=true -D uuid.helper.repeatable=true -D reader.add.source.datetime=false -D writer.include.circular.error.tags=false $IN_DIR/input1.osm $IN_DIR/input2.osm "-77.091256,39.05405,-77.078484,39.057755" $OUT_DIR/output.osc --stats $OUT_DIR/stats.json
diff $IN_DIR/output.osc $OUT_DIR/output.osc
diff $IN_DIR/stats.json $OUT_DIR/stats.json
