# -------------------------------------------------
# Project created by QtCreator 2011-09-29T12:27:47
# -------------------------------------------------
QT += \
    sql \
    testlib \
    xml \
    network \

TARGET = HootCore
TEMPLATE = lib

DEPENDPATH += \
    ../tbs/src/main/cpp/ \
    ../tgs/src/main/cpp/ \
    src/main/cpp/ \

INCLUDEPATH += \
  $${DEPENDPATH} \
  ../local/include/ \

CONFIG += rtti \
    debug

OTHER_FILES = \
    ../conf/ConfigOptions.asciidoc \
    ../rules/LineStringGeneric.js \
    ../rules/PoiGeneric.js \
    ../rules/lib/HootLib.js \
    ../rules/LinearWaterway.js \
    ../conf/LinearWaterway.conf \
    ../conf/LinearWaterway-match-scoring.conf \
    ../conf/schema/all_weather.json \
    ../conf/schema/highway.json \
    ../conf/schema/natural.json \
    ../conf/schema/public_transport.json \
    ../rules/template/ConflateRules.js \

include(../Configure.pri)

LIBS += -L../lib/ -lTgs -ltbs

UI_DIR = tmp/ui
MOC_DIR = tmp/moc
release:OBJECTS_DIR = tmp/release
else:OBJECTS_DIR = tmp/debug
DESTDIR = ../lib/

PROTOPATH = src/main/cpp/hoot/core/proto/
PROTOS = $${PROTOPATH}/OsmFormat.proto $${PROTOPATH}/FileFormat.proto
PROTO_TMP=src/main/cpp/hoot/core/proto/

include(protobuf.pri)

log4cxx {
  SOURCES += src/main/cpp/hoot/core/util/LogLog4Cxx.cpp
  HEADERS += src/main/cpp/hoot/core/util/LogLog4Cxx.h
} else {
  SOURCES += src/main/cpp/hoot/core/util/LogGeneric.cpp
  HEADERS += src/main/cpp/hoot/core/util/LogGeneric.h
}

SOURCES += \
    src/main/cpp/hoot/core/util/Progress.cpp \
    src/main/cpp/hoot/core/OgrFeatureProvider.cpp \
    src/main/cpp/hoot/core/Conflator.cpp \
    src/main/cpp/hoot/core/VectorFeatureProvider.cpp \
    src/main/cpp/hoot/core/manipulators/Manipulator.cpp \
    src/main/cpp/hoot/core/elements/Node.cpp \
    src/main/cpp/hoot/core/index/OsmMapIndex.cpp \
    src/main/cpp/hoot/core/io/OgrReader.cpp \
    src/main/cpp/hoot/core/io/OsmReader.cpp \
    src/main/cpp/hoot/core/OsmMap.cpp \
    src/main/cpp/hoot/core/elements/Way.cpp \
    src/main/cpp/hoot/core/elements/Element.cpp \
    src/main/cpp/hoot/core/elements/WayData.cpp \
    src/main/cpp/hoot/core/elements/NodeData.cpp \
    src/main/cpp/hoot/core/elements/ElementData.cpp \
    src/main/cpp/hoot/core/MapProjector.cpp \
    src/main/cpp/hoot/core/io/OsmWriter.cpp \
    src/main/cpp/hoot/core/WorkingMap.cpp \
    src/main/cpp/hoot/core/manipulators/WayMerger.cpp \
    src/main/cpp/hoot/core/algorithms/WayDiscretizer.cpp \
    src/main/cpp/hoot/core/algorithms/DirectionFinder.cpp \
    src/main/cpp/hoot/core/algorithms/MaximalNearestSubline.cpp \
    src/main/cpp/hoot/core/algorithms/linearreference/WayLocation.cpp \
    src/main/cpp/hoot/core/algorithms/linearreference/LocationOfPoint.cpp \
    src/main/cpp/hoot/core/util/Assert.cpp \
    src/main/cpp/hoot/core/util/AssertionFailedException.cpp \
    src/main/cpp/hoot/core/util/HootException.cpp \
    src/main/cpp/hoot/core/manipulators/WayMatchSet.cpp \
    src/main/cpp/hoot/core/scoring/RasterComparator.cpp \
    src/main/cpp/hoot/core/scoring/BaseComparator.cpp \
    src/main/cpp/hoot/core/scoring/GraphComparator.cpp \
    src/main/cpp/hoot/core/algorithms/WaySplitter.cpp \
    src/main/cpp/hoot/core/conflate/splitter/IntersectionSplitter.cpp \
    src/main/cpp/hoot/core/scoring/DirectedGraph.cpp \
    src/main/cpp/hoot/core/scoring/ShortestPath.cpp \
    src/main/cpp/hoot/core/manipulators/DividedHighwayMerger.cpp \
    src/main/cpp/hoot/core/manipulators/DividedHighwayManipulation.cpp \
    src/main/cpp/hoot/core/algorithms/WayHeading.cpp \
    src/main/cpp/hoot/core/filters/OneWayFilter.cpp \
    src/main/cpp/hoot/core/filters/NeighborFilter.cpp \
    src/main/cpp/hoot/core/filters/WayFilterChain.cpp \
    src/main/cpp/hoot/core/filters/UnknownFilter.cpp \
    src/main/cpp/hoot/core/filters/WayDirectionFilter.cpp \
    src/main/cpp/hoot/core/algorithms/LineStringAverager.cpp \
    src/main/cpp/hoot/core/filters/ParallelWayFilter.cpp \
    src/main/cpp/hoot/core/ops/SuperfluousNodeRemover.cpp \
    src/main/cpp/hoot/core/filters/WayBufferFilter.cpp \
    src/main/cpp/hoot/core/manipulators/WayMergeManipulation.cpp \
    src/main/cpp/hoot/core/algorithms/WayAverager.cpp \
    src/main/cpp/hoot/core/algorithms/ProbabilityOfMatch.cpp \
    src/main/cpp/hoot/core/conflate/SuperfluousWayRemover.cpp \
    src/main/cpp/hoot/core/conflate/splitter/DualWaySplitter.cpp \
    src/main/cpp/hoot/core/elements/Tags.cpp \
    src/main/cpp/hoot/core/filters/DistanceNodeFilter.cpp \
    src/main/cpp/hoot/core/filters/ChainNodeFilter.cpp \
    src/main/cpp/hoot/core/filters/InWayNodeFilter.cpp \
    src/main/cpp/hoot/core/conflate/UnlikelyIntersectionRemover.cpp \
    src/main/cpp/hoot/core/conflate/NodeToWayMap.cpp \
    src/main/cpp/hoot/core/conflate/ImpliedDividedMarker.cpp \
    src/main/cpp/hoot/core/ops/MapCropper.cpp \
    src/main/cpp/hoot/core/io/ShapefileWriter.cpp \
    src/main/cpp/hoot/core/conflate/DuplicateWayRemover.cpp \
    src/main/cpp/hoot/core/algorithms/LongestCommonNodeString.cpp \
    src/main/cpp/hoot/core/conflate/DuplicateNameRemover.cpp \
    src/main/cpp/hoot/core/index/KnnWayIterator.cpp \
    src/main/cpp/hoot/core/ops/MergeNearbyNodes.cpp \
    src/main/cpp/hoot/core/algorithms/LevenshteinDistance.cpp \
    src/main/cpp/hoot/core/schema/OsmSchema.cpp \
    src/main/cpp/hoot/core/schema/TagComparator.cpp \
    src/main/cpp/hoot/core/scoring/AttributeComparator.cpp \
    src/main/cpp/hoot/core/index/ClosePointHash.cpp \
    src/main/cpp/hoot/core/manipulators/DanglerRemover.cpp \
    src/main/cpp/hoot/core/manipulators/DanglerRemoverManipulation.cpp \
    src/main/cpp/hoot/core/conflate/SmallWayMerger.cpp \
    src/main/cpp/hoot/core/conflate/TileConflator.cpp \
    src/main/cpp/hoot/core/algorithms/Translator.cpp \
    src/main/cpp/hoot/core/conflate/LargeWaySplitter.cpp \
    src/main/cpp/hoot/core/conflate/OutsideBoundsRemover.cpp \
    src/main/cpp/hoot/core/util/NotImplementedException.cpp \
    src/main/cpp/hoot/core/util/FileUtils.cpp \
    src/main/cpp/hoot/core/conflate/NodeReplacements.cpp \
    src/main/cpp/hoot/core/conflate/TileBoundsCalculator.cpp \
    src/main/cpp/hoot/core/io/PbfReader.cpp \
    src/main/cpp/hoot/core/io/PbfWriter.cpp \
    src/main/cpp/hoot/core/io/PbfConstants.cpp \
    src/main/cpp/hoot/core/cmd/Command.cpp \
    src/main/cpp/hoot/core/Factory.cpp \
    src/main/cpp/hoot/core/IdGenerator.cpp \
    src/main/cpp/hoot/core/DefaultIdGenerator.cpp \
    src/main/cpp/hoot/core/conflate/LocalTileWorker.cpp \
    src/main/cpp/hoot/core/util/ConfPath.cpp \
    src/main/cpp/hoot/core/util/GeometryUtils.cpp \
    src/main/cpp/hoot/core/util/SignalCatcher.cpp \
    src/main/cpp/hoot/core/util/Log.cpp \
    src/main/cpp/hoot/core/ml/LogisticRegression.cpp \
    src/main/cpp/hoot/core/cmd/BaseCommand.cpp \
    src/main/cpp/hoot/core/conflate/MapCleaner.cpp \
    src/main/cpp/hoot/core/manipulators/WayTagMergeManipulation.cpp \
    src/main/cpp/hoot/core/manipulators/WayTagMerger.cpp \
    src/main/cpp/hoot/core/conflate/RubberSheet.cpp \
    src/main/cpp/hoot/core/conflate/NodeMatcher.cpp \
    src/main/cpp/hoot/core/cmd/CleanupCmd.cpp \
    src/main/cpp/hoot/core/util/Settings.cpp \
    src/main/cpp/hoot/core/cmd/Ogr2OsmCmd.cpp \
    src/main/cpp/hoot/core/cmd/StatsCmd.cpp \
    src/main/cpp/hoot/core/cmd/AddOsmPbfHeaderCmd.cpp \
    src/main/cpp/hoot/core/Version.cpp \
    src/main/cpp/hoot/core/cmd/VersionCmd.cpp \
    src/main/cpp/hoot/core/cmd/CookieCutterCmd.cpp \
    src/main/cpp/hoot/core/elements/ElementIterator.cpp \
    src/main/cpp/hoot/core/cmd/BigOgr2OsmCmd.cpp \
    src/main/cpp/hoot/core/io/ObjectOutputStream.cpp \
    src/main/cpp/hoot/core/io/ObjectInputStream.cpp \
    src/main/cpp/hoot/core/ops/OpList.cpp \
    src/main/cpp/hoot/core/fourpass/FourPassManager.cpp \
    src/main/cpp/hoot/core/fourpass/LocalTileWorker2.cpp \
    src/main/cpp/hoot/core/ops/ReprojectToPlanarOp.cpp \
    src/main/cpp/hoot/core/ops/ReprojectToGeographicOp.cpp \
    src/main/cpp/hoot/core/elements/Relation.cpp \
    src/main/cpp/hoot/core/elements/RelationData.cpp \
    src/main/cpp/hoot/core/algorithms/AlphaShape.cpp \
    src/main/cpp/hoot/core/cmd/UnionPolygonsCmd.cpp \
    src/main/cpp/hoot/core/cmd/AlphaShapeCmd.cpp \
    src/main/cpp/hoot/core/cmd/ConflateCmd.cpp \
    src/main/cpp/hoot/core/io/PbfElementIterator.cpp \
    src/main/cpp/hoot/core/cmd/BigCatCmd.cpp \
    src/main/cpp/hoot/core/ops/WaySplitterOp.cpp \
    src/main/cpp/hoot/core/cmd/Osm2ShpCmd.cpp \
    src/main/cpp/hoot/core/ops/BuildingPartMergeOp.cpp \
    src/main/cpp/hoot/core/index/ElementToRelationMap.cpp \
    src/main/cpp/hoot/core/ops/BuildingOutlineUpdateOp.cpp \
    src/main/cpp/hoot/core/ops/RemoveDuplicateReviewsOp.cpp \
    src/main/cpp/hoot/core/cmd/ConvertCmd.cpp \
    src/main/cpp/hoot/core/ops/VisitorOp.cpp \
    src/main/cpp/hoot/core/ops/NamedOp.cpp \
    src/main/cpp/hoot/core/visitors/ReportMissingElementsVisitor.cpp \
    src/main/cpp/hoot/core/visitors/KeepBuildingsVisitor.cpp \
    src/main/cpp/hoot/core/visitors/LengthOfWaysVisitor.cpp \
    src/main/cpp/hoot/core/visitors/AddRef1Visitor.cpp \
    src/main/cpp/hoot/core/visitors/AddRef2Visitor.cpp \
    src/main/cpp/hoot/core/conflate/polygon/extractors/CentroidDistanceExtractor.cpp \
    src/main/cpp/hoot/core/util/GeometryConverter.cpp \
    src/main/cpp/hoot/core/algorithms/VertexHausdorffDistance.cpp \
    src/main/cpp/hoot/core/cmd/DeriveRubberSheetCmd.cpp \
    src/main/cpp/hoot/core/cmd/ApplyRubberSheetCmd.cpp \
    src/main/cpp/hoot/core/cmd/RubberSheetCmd.cpp \
    src/main/cpp/hoot/core/conflate/polygon/extractors/HausdorffDistanceExtractor.cpp \
    src/main/cpp/hoot/core/visitors/RemoveElementsVisitor.cpp \
    src/main/cpp/hoot/core/filters/TagElementFilter.cpp \
    src/main/cpp/hoot/core/schema/Building.cpp \
    src/main/cpp/hoot/core/conflate/polygon/extractors/OverlapExtractor.cpp \
    src/main/cpp/hoot/core/conflate/polygon/extractors/CompactnessExtractor.cpp \
    src/main/cpp/hoot/core/conflate/polygon/extractors/AngleHistogramExtractor.cpp \
    src/main/cpp/hoot/core/conflate/polygon/extractors/NameExtractor.cpp \
    src/main/cpp/hoot/core/cmd/PrintNamesCmd.cpp \
    src/main/cpp/hoot/core/algorithms/Soundex.cpp \
    src/main/cpp/hoot/core/algorithms/MeanWordSetDistance.cpp \
    src/main/cpp/hoot/core/schema/ScoreMatrix.cpp \
    src/main/cpp/hoot/core/algorithms/MaxWordSetDistance.cpp \
    src/main/cpp/hoot/core/schema/TranslateStringDistance.cpp \
    src/main/cpp/hoot/core/algorithms/ExactStringDistance.cpp \
    src/main/cpp/hoot/core/conflate/polygon/extractors/BufferedOverlapExtractor.cpp \
    src/main/cpp/hoot/core/cmd/BuildModelCmd.cpp \
    src/main/cpp/hoot/core/conflate/polygon/extractors/SmallerOverlapExtractor.cpp \
    src/main/cpp/hoot/core/visitors/GetElementIdsVisitor.cpp \
    src/main/cpp/hoot/core/visitors/CountNodesVisitor.cpp \
    src/main/cpp/hoot/core/conflate/match-graph/MatchGraph.cpp \
    src/main/cpp/hoot/core/conflate/polygon/BuildingMerger.cpp \
    src/main/cpp/hoot/core/conflate/polygon/BuildingMergerCreator.cpp \
    src/main/cpp/hoot/core/conflate/MergerFactory.cpp \
    src/main/cpp/hoot/core/conflate/Match.cpp \
    src/main/cpp/hoot/core/conflate/UnifyingConflator.cpp \
    src/main/cpp/hoot/core/conflate/MatchFactory.cpp \
    src/main/cpp/hoot/core/conflate/polygon/BuildingMatch.cpp \
    src/main/cpp/hoot/core/conflate/polygon/BuildingMatchCreator.cpp \
    src/main/cpp/hoot/core/cmd/UnifyCmd.cpp \
    src/main/cpp/hoot/core/ops/RecursiveElementRemover.cpp \
    src/main/cpp/hoot/core/visitors/SetVisitor.cpp \
    src/main/cpp/hoot/core/scoring/MatchComparator.cpp \
    src/main/cpp/hoot/core/visitors/AddUuidVisitor.cpp \
    src/main/cpp/hoot/core/visitors/FilteredVisitor.cpp \
    src/main/cpp/hoot/core/cmd/ScoreMatchesCmd.cpp \
    src/main/cpp/hoot/core/filters/TagContainsFilter.cpp \
    src/main/cpp/hoot/core/visitors/SetTagVisitor.cpp \
    src/main/cpp/hoot/core/visitors/ElementOsmMapVisitor.cpp \
    src/main/cpp/hoot/core/visitors/RemoveEmptyRelationsVisitor.cpp \
    src/main/cpp/hoot/core/visitors/RemoveEmptyAreasVisitor.cpp \
    src/main/cpp/hoot/core/visitors/RemoveDuplicateAreaVisitor.cpp \
    src/main/cpp/hoot/core/conflate/MatchThreshold.cpp \
    src/main/cpp/hoot/core/conflate/MarkForReviewMerger.cpp \
    src/main/cpp/hoot/core/conflate/MarkForReviewMergerCreator.cpp \
    src/main/cpp/hoot/core/conflate/polygon/extractors/EdgeDistanceExtractor.cpp \
    src/main/cpp/hoot/core/algorithms/aggregator/QuantileAggregator.cpp \
    src/main/cpp/hoot/core/conflate/highway/HighwayMatch.cpp \
    src/main/cpp/hoot/core/conflate/highway/HighwayMergerCreator.cpp \
    src/main/cpp/hoot/core/conflate/highway/HighwayMatchCreator.cpp \
    src/main/cpp/hoot/core/conflate/highway/HighwayMerger.cpp \
    src/main/cpp/hoot/core/conflate/highway/HighwaySnapMerger.cpp \
    src/main/cpp/hoot/core/conflate/highway/HighwaySnapMergerCreator.cpp \
    src/main/cpp/hoot/core/manipulators/WaySnapMerger.cpp \
    src/main/cpp/hoot/core/manipulators/WaySnapMergeManipulation.cpp \
    src/main/cpp/hoot/core/visitors/MultiLineStringVisitor.cpp \
    src/main/cpp/hoot/core/visitors/IsCompleteVisitor.cpp \
    src/main/cpp/hoot/core/algorithms/MaximalSubline.cpp \
    src/main/cpp/hoot/core/algorithms/Sparse2dMatrix.cpp \
    src/main/cpp/hoot/core/visitors/RemoveUnknown1Visitor.cpp \
    src/main/cpp/hoot/core/visitors/UnionPolygonsVisitor.cpp \
    src/main/cpp/hoot/core/cmd/EvalMoveCmd.cpp \
    src/main/cpp/hoot/core/io/GmlWriter.cpp \
    src/main/cpp/hoot/core/algorithms/ExpectationIntersection.cpp \
    src/main/cpp/hoot/core/algorithms/linearreference/WaySublineMatch.cpp \
    src/main/cpp/hoot/core/algorithms/linearreference/WaySubline.cpp \
    src/main/cpp/hoot/core/filters/IntersectionFilter.cpp \
    src/main/cpp/hoot/core/ops/FindIntersectionsOp.cpp \
    src/main/cpp/hoot/core/cmd/FindIntersectionsCmd.cpp \
    src/main/cpp/hoot/core/visitors/FindIntersectionsVisitor.cpp \
    src/main/cpp/hoot/core/algorithms/optimizer/IntegerProgrammingSolver.cpp \
    src/main/cpp/hoot/core/conflate/match-graph/ConstrainedMatches.cpp \
    src/main/cpp/hoot/core/perty/PertyRemoveRandomElementVisitor.cpp \
    src/main/cpp/hoot/core/perty/PertyNameVisitor.cpp \
    src/main/cpp/hoot/core/io/ScriptTranslator.cpp \
    src/main/cpp/hoot/core/io/PythonTranslator.cpp \
    src/main/cpp/hoot/core/perty/PertyDuplicatePoiOp.cpp \
    src/main/cpp/hoot/core/perty/PertyRemoveTagVisitor.cpp \
    src/main/cpp/hoot/core/io/GeoNamesReader.cpp \
    src/main/cpp/hoot/core/ops/TranslationOp.cpp \
    src/main/cpp/hoot/core/io/ScriptTranslatorFactory.cpp \
    src/main/cpp/hoot/core/cmd/IsMatchCmd.cpp \
    src/main/cpp/hoot/core/scoring/MapComparator.cpp \
    src/main/cpp/hoot/core/io/OsmApiDbReader.cpp \
    src/main/cpp/hoot/core/io/HootApiDbReader.cpp \
    src/main/cpp/hoot/core/io/HootApiDbWriter.cpp \
    src/main/cpp/hoot/core/perty/BigPertyOp.cpp \
    src/main/cpp/hoot/core/io/PartialOsmMapReader.cpp \
    src/main/cpp/hoot/core/io/OsmMapWriter.cpp \
    src/main/cpp/hoot/core/io/OsmMapReader.cpp \
    src/main/cpp/hoot/core/io/ApiDb.cpp \
    src/main/cpp/hoot/core/io/OsmApiDb.cpp \
    src/main/cpp/hoot/core/io/HootApiDb.cpp \
    src/main/cpp/hoot/core/io/OsmMapWriterFactory.cpp \
    src/main/cpp/hoot/core/io/OsmMapReaderFactory.cpp \
    src/main/cpp/hoot/core/io/OgrWriter.cpp \
    src/main/cpp/hoot/core/io/OgrUtilities.cpp \
    src/main/cpp/hoot/core/io/schema/Schema.cpp \
    src/main/cpp/hoot/core/io/schema/Layer.cpp \
    src/main/cpp/hoot/core/io/schema/FeatureDefinition.cpp \
    src/main/cpp/hoot/core/io/schema/Feature.cpp \
    src/main/cpp/hoot/core/io/schema/StringFieldDefinition.cpp \
    src/main/cpp/hoot/core/io/schema/DoubleFieldDefinition.cpp \
    src/main/cpp/hoot/core/io/schema/IntegerFieldDefinition.cpp \
    src/main/cpp/hoot/core/io/schema/FieldDefinition.cpp \
    src/main/cpp/hoot/core/cmd/Osm2OgrCmd.cpp \
    src/main/cpp/hoot/core/index/metric-hybrid/FqTree.cpp \
    src/main/cpp/hoot/core/index/metric-hybrid/RFqHybridTree.cpp \
    src/main/cpp/hoot/core/index/metric-hybrid/RTree.cpp \
    src/main/cpp/hoot/core/schema/AverageTagMerger.cpp \
    src/main/cpp/hoot/core/schema/TagMergerFactory.cpp \
    src/main/cpp/hoot/core/schema/GeneralizeTagMerger.cpp \
    src/main/cpp/hoot/core/visitors/DecomposeBuildingRelationsVisitor.cpp \
    src/main/cpp/hoot/core/ops/BuildingOutlineRemoveOp.cpp \
    src/main/cpp/hoot/core/schema/OverwriteTagMerger.cpp \
    src/main/cpp/hoot/core/visitors/KeepHighwaysVisitor.cpp \
    src/main/cpp/hoot/core/conflate/highway/HighwayExpertClassifier.cpp \
    src/main/cpp/hoot/core/conflate/MatchClassification.cpp \
    src/main/cpp/hoot/core/algorithms/SublineMatcher.cpp \
    src/main/cpp/hoot/core/algorithms/MaximalNearestSublineMatcher.cpp \
    src/main/cpp/hoot/core/util/UuidHelper.cpp \
    src/main/cpp/hoot/core/algorithms/SublineStringMatcher.cpp \
    src/main/cpp/hoot/core/algorithms/MaximalSublineStringMatcher.cpp \
    src/main/cpp/hoot/core/ops/CopySubsetOp.cpp \
    src/main/cpp/hoot/core/visitors/KeepNodesVisitor.cpp \
    src/main/cpp/hoot/core/algorithms/BufferedLineSegmentIntersector.cpp \
    src/main/cpp/hoot/core/conflate/MergerBase.cpp \
    src/main/cpp/hoot/core/algorithms/MaximalSublineMatcher.cpp \
    src/main/cpp/hoot/core/algorithms/linearreference/WaySublineMatchString.cpp \
    src/main/cpp/hoot/core/algorithms/MultiLineStringSplitter.cpp \
    src/main/cpp/hoot/core/visitors/AddGeometryTypeVisitor.cpp \
    src/main/cpp/hoot/core/conflate/match-graph/MatchConflicts.cpp \
    src/main/cpp/hoot/core/conflate/match-graph/GreedyConstrainedMatches.cpp \
    src/main/cpp/hoot/core/conflate/match-graph/OptimalConstrainedMatches.cpp \
    src/main/cpp/hoot/core/visitors/ExtractWaysVisitor.cpp \
    src/main/cpp/hoot/core/scoring/MatchFeatureExtractor.cpp \
    src/main/cpp/hoot/core/conflate/highway/HighwayRfClassifier.cpp \
    src/main/cpp/hoot/core/cmd/DeleteMapCmd.cpp \
    src/main/cpp/hoot/core/io/OgrOptions.cpp \
    src/main/cpp/hoot/core/ops/CalculateStatsOp.cpp \
    src/main/cpp/hoot/core/filters/BaseFilter.cpp \
    src/main/cpp/hoot/core/visitors/CalculateAreaVisitor.cpp \
    src/main/cpp/hoot/core/visitors/CalculateAreaForStatsVisitor.cpp \
    src/main/cpp/hoot/core/io/db/BulkInsert.cpp \
    src/main/cpp/hoot/core/io/db/SqlBulkInsert.cpp \
    src/main/cpp/hoot/core/conflate/extractors/WeightedShapeDistanceExtractor.cpp \
    src/main/cpp/hoot/core/conflate/extractors/WayFeatureExtractor.cpp \
    src/main/cpp/hoot/core/conflate/extractors/DistanceScoreExtractor.cpp \
    src/main/cpp/hoot/core/conflate/extractors/WeightedMetricDistanceExtractor.cpp \
    src/main/cpp/hoot/core/cmd/ScoreCmd.cpp \
    src/main/cpp/hoot/core/io/OsmJsonWriter.cpp \
    src/main/cpp/hoot/core/ops/stats/IoSingleStat.cpp \
    src/main/cpp/hoot/core/Hoot.cpp \
    src/main/cpp/hoot/core/schema/ExactTagDifferencer.cpp \
    src/main/cpp/hoot/core/schema/TagDifferencer.cpp \
    src/main/cpp/hoot/core/schema/TranslatedTagDifferencer.cpp \
    src/main/cpp/hoot/core/conflate/polygon/BuildingRfClassifier.cpp \
    src/main/cpp/hoot/core/conflate/RfExtractorClassifier.cpp \
    src/main/cpp/hoot/core/cmd/CropMapCmd.cpp \
    src/main/cpp/hoot/core/util/MultiPolygonCreator.cpp \
    src/main/cpp/hoot/core/io/db/InternalIdReserver.cpp \
    src/main/cpp/hoot/core/conflate/ReviewMarker.cpp \
    src/main/cpp/hoot/core/cmd/AttributeCoOccuranceCmd.cpp \
    src/main/cpp/hoot/core/scoring/AttributeCoOccurence.cpp \
    src/main/cpp/hoot/core/visitors/TagCountVisitor.cpp \
    src/main/cpp/hoot/core/visitors/TranslatedTagCountVisitor.cpp \
    src/main/cpp/hoot/core/scoring/TextTable.cpp \
    src/main/cpp/hoot/core/algorithms/linearreference/MultiLineStringLocation.cpp \
    src/main/cpp/hoot/core/perty/PertyWaySplitVisitor.cpp \
    src/main/cpp/hoot/core/filters/NotCriterion.cpp \
    src/main/cpp/hoot/core/filters/BuildingCriterion.cpp \
    src/main/cpp/hoot/core/ops/RefRemoveOp.cpp \
    src/main/cpp/hoot/core/filters/NoInformationCriterion.cpp \
    src/main/cpp/hoot/core/filters/OrCriterion.cpp \
    src/main/cpp/hoot/core/filters/PoiCriterion.cpp \
    src/main/cpp/hoot/core/filters/StatusCriterion.cpp \
    src/main/cpp/hoot/core/filters/ElementTypeCriterion.cpp \
    src/main/cpp/hoot/core/filters/TagCriterion.cpp \
    src/main/cpp/hoot/core/perty/PertyWayGeneralizeVisitor.cpp \
    src/main/cpp/hoot/core/util/RandomNumberUtils.cpp \
    src/main/cpp/hoot/core/algorithms/RdpWayGeneralizer.cpp \
    src/main/cpp/hoot/core/visitors/RemoveRef2Visitor.cpp \
    src/main/cpp/hoot/core/util/OsmUtils.cpp \
    src/main/cpp/hoot/core/cmd/PrintOsmDocsCmd.cpp \
    src/main/cpp/hoot/core/visitors/SplitNameVisitor.cpp \
    src/main/cpp/hoot/core/visitors/TagRenameKeyVisitor.cpp \
    src/main/cpp/hoot/core/visitors/TagKeyCountVisitor.cpp \
    src/main/cpp/hoot/core/scoring/MatchScoringMapPreparer.cpp \
    src/main/cpp/hoot/core/scoring/MapMatchScoringUtils.cpp \
    src/main/cpp/hoot/core/perty/PertyTestRunResult.cpp \
    src/main/cpp/hoot/core/io/MapStatsWriter.cpp \
    src/main/cpp/hoot/core/conflate/NoInformationElementRemover.cpp \
    src/main/cpp/hoot/core/GeometryPainter.cpp \
    src/main/cpp/hoot/core/perty/PertyOp.cpp \
    src/main/cpp/hoot/core/perty/PertyMatchScorer.cpp \
    src/main/cpp/hoot/core/cmd/PertyCmd.cpp \
    src/main/cpp/hoot/core/cmd/PertyScoreCmd.cpp \
    src/main/cpp/hoot/core/cmd/PertyTestCmd.cpp \
    src/main/cpp/hoot/core/perty/PertyTestRunner.cpp \
    src/main/cpp/hoot/core/perty/PermuteGridCalculator.cpp \
    src/main/cpp/hoot/core/perty/DirectSequentialSimulation.cpp \
    src/main/cpp/hoot/core/cmd/AccuracyDistributionCmd.cpp \
    src/main/cpp/hoot/core/PositiveIdGenerator.cpp \
    src/main/cpp/hoot/core/util/ElementConverter.cpp \
    src/main/cpp/hoot/core/io/PartialOsmMapWriter.cpp \
    src/main/cpp/hoot/core/cmd/PaintNodesCmd.cpp \
    src/main/cpp/hoot/core/visitors/TransliterateNameVisitor.cpp \
    src/main/cpp/hoot/core/conflate/extractors/LengthScoreExtractor.cpp \
    src/main/cpp/hoot/core/algorithms/optimizer/SingleAssignmentProblemSolver.cpp \
    src/main/cpp/hoot/core/conflate/extractors/Histogram.cpp \
    src/main/cpp/hoot/core/conflate/extractors/SampledAngleHistogramExtractor.cpp \
    src/main/cpp/hoot/core/conflate/point/PoiRfClassifier.cpp \
    src/main/cpp/hoot/core/io/ArffWriter.cpp \
    src/main/cpp/hoot/core/scoring/DataSamples.cpp \
    src/main/cpp/hoot/core/cmd/BuildRfCmd.cpp \
    src/main/cpp/hoot/core/io/ArffReader.cpp \
    src/main/cpp/hoot/core/conflate/WayCleaner.cpp \
    src/main/cpp/hoot/core/scoring/MapScoringStatusAndRefTagValidator.cpp \
    src/main/cpp/hoot/core/conflate/extractors/AttributeDistanceExtractor.cpp \
    src/main/cpp/hoot/core/conflate/extractors/AttributeScoreExtractor.cpp \
    src/main/cpp/hoot/core/algorithms/aggregator/MaxAggregator.cpp \
    src/main/cpp/hoot/core/algorithms/aggregator/MeanAggregator.cpp \
    src/main/cpp/hoot/core/algorithms/aggregator/MinAggregator.cpp \
    src/main/cpp/hoot/core/algorithms/aggregator/RmseAggregator.cpp \
    src/main/cpp/hoot/core/algorithms/aggregator/SigmaAggregator.cpp \
    src/main/cpp/hoot/core/algorithms/zindex/BBox.cpp \
    src/main/cpp/hoot/core/algorithms/zindex/LongBox.cpp \
    src/main/cpp/hoot/core/algorithms/zindex/Range.cpp \
    src/main/cpp/hoot/core/algorithms/zindex/ZCurveRanger.cpp \
    src/main/cpp/hoot/core/algorithms/zindex/ZValue.cpp \
    src/main/cpp/hoot/core/cmd/AttributeCountCmd.cpp \
    src/main/cpp/hoot/core/scoring/AttributeCount.cpp \
    src/main/cpp/hoot/core/conflate/SearchRadiusCalculator.cpp \
    src/main/cpp/hoot/core/io/ElementOutputStream.cpp \
    src/main/cpp/hoot/core/io/ElementInputStream.cpp \
    src/main/cpp/hoot/core/visitors/TranslationVisitor.cpp \
    src/main/cpp/hoot/core/io/ElementVisitorInputStream.cpp \
    src/main/cpp/hoot/core/io/ElementCacheLRU.cpp \
    src/main/cpp/hoot/core/visitors/MatchCandidateCountVisitor.cpp \
    src/main/cpp/hoot/core/algorithms/string/WeightedWordDistance.cpp \
    src/main/cpp/hoot/core/algorithms/string/TextFileWordWeightDictionary.cpp \
    src/main/cpp/hoot/core/algorithms/string/MinSumWordSetDistance.cpp \
    src/main/cpp/hoot/core/io/WordCountReader.cpp \
    src/main/cpp/hoot/core/io/WordCountWriter.cpp \
    src/main/cpp/hoot/core/algorithms/string/SqliteWordWeightDictionary.cpp \
    src/main/cpp/hoot/core/algorithms/string/StringTokenizer.cpp \
    src/main/cpp/hoot/core/conflate/ConflateStatsHelper.cpp \
    src/main/cpp/hoot/core/filters/HighwayCriterion.cpp \
    src/main/cpp/hoot/core/visitors/RemoveTagVisitor.cpp \
    src/main/cpp/hoot/core/visitors/KeepTagsVisitor.cpp \
    src/main/cpp/hoot/core/ops/CookieCutterOp.cpp \
    src/main/cpp/hoot/core/conflate/AlphaShapeGenerator.cpp \
    src/main/cpp/hoot/core/conflate/CookieCutter.cpp \
    src/main/cpp/hoot/core/visitors/SplitLongLinearWaysVisitor.cpp \
    src/main/cpp/hoot/core/io/db/PostgresqlDumpfileWriter.cpp \
    src/main/cpp/hoot/core/ops/ReplaceElementOp.cpp \
    src/main/cpp/hoot/core/filters/NeedsReviewCriterion.cpp \
    src/main/cpp/hoot/core/visitors/CountUniqueReviewsVisitor.cpp \
    src/main/cpp/hoot/core/ops/RemoveReviewsByEidOp.cpp \
    src/main/cpp/hoot/core/conflate/highway/HighwayReviewCleanerOp.cpp \
    src/main/cpp/hoot/core/ops/AddHilbertReviewSortOrderOp.cpp \
    src/main/cpp/hoot/core/schema/SchemaVertex.cpp \
    src/main/cpp/hoot/core/schema/SchemaChecker.cpp \
    src/main/cpp/hoot/core/schema/TagCategoryDifferencer.cpp \
    src/main/cpp/hoot/core/schema/TagAncestorDifferencer.cpp \
    src/main/cpp/hoot/core/schema/TagFilteredDifferencer.cpp \
    src/main/cpp/hoot/core/io/ElementSorter.cpp \
    src/main/cpp/hoot/core/io/ChangesetDeriver.cpp \
    src/main/cpp/hoot/core/io/OsmChangesetXmlFileWriter.cpp \
    src/main/cpp/hoot/core/cmd/DeriveChangesetCmd.cpp \
    src/main/cpp/hoot/core/io/OsmChangesetSqlFileWriter.cpp \
    src/main/cpp/hoot/core/schema/OsmSchemaLoaderFactory.cpp \
    src/main/cpp/hoot/core/schema/OsmSchemaLoader.cpp \
    src/main/cpp/hoot/core/algorithms/string/MostEnglishName.cpp \
    src/main/cpp/hoot/core/visitors/MedianNodeVisitor.cpp \
    src/main/cpp/hoot/core/conflate/polygon/extractors/EuclideanDistanceExtractor.cpp \
    src/main/cpp/hoot/core/visitors/RemoveMissingElementsVisitor.cpp \
    src/main/cpp/hoot/core/visitors/ProjectToGeographicVisitor.cpp \
    src/main/cpp/hoot/core/filters/WaterwayCriterion.cpp \
    src/main/cpp/hoot/core/algorithms/linearreference/WayMapping.cpp \
    src/main/cpp/hoot/core/algorithms/linearreference/WayMatchStringMapping.cpp \
    src/main/cpp/hoot/core/algorithms/WayMatchStringMerger.cpp \
    src/main/cpp/hoot/core/algorithms/linearreference/NaiveWayMatchStringMapping.cpp \
    src/main/cpp/hoot/core/io/ElementComparer.cpp \
    src/main/cpp/hoot/core/cmd/ApplyChangesetCmd.cpp \
    src/main/cpp/hoot/core/filters/IntersectionCriterion.cpp \
    src/main/cpp/hoot/core/algorithms/linearreference/WayString.cpp \
    src/main/cpp/hoot/core/algorithms/linearreference/WaySublineCollection.cpp \
    src/main/cpp/hoot/core/algorithms/linearreference/WayMatchStringMappingConverter.cpp \
    src/main/cpp/hoot/core/io/OsmApiDbAwareHootApiDbWriter.cpp \
    src/main/cpp/hoot/core/io/OsmApiDbSqlChangesetWriter.cpp \
    src/main/cpp/hoot/core/io/OsmApiDbAwareHootApiDbReader.cpp \
    src/main/cpp/hoot/core/io/OsmJsonReader.cpp \
    src/main/cpp/hoot/core/visitors/RemoveInvalidReviewRelationsVisitor.cpp \
    src/main/cpp/hoot/core/filters/BuildingWayNodeCriterion.cpp \
    src/main/cpp/hoot/core/visitors/CalculateBoundsVisitor.cpp \
    src/main/cpp/hoot/core/algorithms/KskipBigramDistance.cpp \
    src/main/cpp/hoot/core/visitors/IndexElementsVisitor.cpp \
    src/main/cpp/hoot/core/algorithms/WayMatchStringSplitter.cpp \
    src/main/cpp/hoot/core/filters/ParallelWayCriterion.cpp \
    src/main/cpp/hoot/core/filters/WayBufferCriterion.cpp \
    src/main/cpp/hoot/core/filters/WayDirectionCriterion.cpp \
    src/main/cpp/hoot/core/visitors/FindWaysVisitor.cpp \
    src/main/cpp/hoot/core/visitors/FindNodesVisitor.cpp \
    src/main/cpp/hoot/core/filters/DistanceNodeCriterion.cpp \
    src/main/cpp/hoot/core/visitors/MapExtentVisitor.cpp \
    src/main/cpp/hoot/core/cmd/MapExtentCmd.cpp \
    src/main/cpp/hoot/core/ops/RemoveElementOp.cpp \
    src/main/cpp/hoot/core/ops/RemoveNodeOp.cpp \
    src/main/cpp/hoot/core/ops/RemoveRelationOp.cpp \
    src/main/cpp/hoot/core/ops/RemoveWayOp.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatchCreator.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatch.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMerger.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMergerCreator.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonRfClassifier.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/filters/PoiPolygonPolyCriterion.cpp \
    src/main/cpp/hoot/core/filters/AreaCriterion.cpp \
    src/main/cpp/hoot/core/filters/WayCriterion.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/filters/PoiPolygonPoiCriterion.cpp \
    src/main/cpp/hoot/core/filters/ChainCriterion.cpp \
    src/main/cpp/hoot/core/filters/NonBuildingAreaCriterion.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonDistance.cpp \
    src/main/cpp/hoot/core/visitors/CountManualMatchesVisitor.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonDistanceTruthRecorder.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonNameScoreExtractor.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonTypeScoreExtractor.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonAddressScoreExtractor.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonDistanceExtractor.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonAlphaShapeDistanceExtractor.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonReviewReducer.cpp \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonAdvancedMatcher.cpp

HEADERS += \
    src/main/cpp/hoot/core/util/Progress.h \
    src/main/cpp/hoot/core/FeatureProvider.h \
    src/main/cpp/hoot/core/OgrFeatureProvider.h \
    src/main/cpp/hoot/core/Conflator.h \
    src/main/cpp/hoot/core/VectorFeatureProvider.h \
    src/main/cpp/hoot/core/Exception.h \
    src/main/cpp/hoot/core/manipulators/Manipulator.h \
    src/main/cpp/hoot/core/SourceMap.h \
    src/main/cpp/hoot/core/SourceFeature.h \
    src/main/cpp/hoot/core/WorkingMap.h \
    src/main/cpp/hoot/core/elements/Node.h \
    src/main/cpp/hoot/core/io/OgrReader.h \
    src/main/cpp/hoot/core/io/OsmReader.h \
    src/main/cpp/hoot/core/OsmMap.h \
    src/main/cpp/hoot/core/elements/Tags.h \
    src/main/cpp/hoot/core/elements/Way.h \
    src/main/cpp/hoot/core/elements/Element.h \
    src/main/cpp/hoot/core/elements/WayData.h \
    src/main/cpp/hoot/core/elements/NodeData.h \
    src/main/cpp/hoot/core/elements/ElementData.h \
    src/main/cpp/hoot/core/MapProjector.h \
    src/main/cpp/hoot/core/io/OsmWriter.h \
    src/main/cpp/hoot/core/Units.h \
    src/main/cpp/hoot/core/manipulators/WayMerger.h \
    src/main/cpp/hoot/core/algorithms/WayDiscretizer.h \
    src/main/cpp/hoot/core/algorithms/Distance.h \
    src/main/cpp/hoot/core/algorithms/DirectionFinder.h \
    src/main/cpp/hoot/core/algorithms/MaximalNearestSubline.h \
    src/main/cpp/hoot/core/algorithms/linearreference/WayLocation.h \
    src/main/cpp/hoot/core/algorithms/linearreference/LocationOfPoint.h \
    src/main/cpp/hoot/core/index/OsmMapIndex.h \
    src/main/cpp/hoot/core/util/Assert.h \
    src/main/cpp/hoot/core/util/AssertionFailedException.h \
    src/main/cpp/hoot/core/util/HootException.h \
    src/main/cpp/hoot/core/manipulators/WayMatchSet.h \
    src/main/cpp/hoot/core/scoring/RasterComparator.h \
    src/main/cpp/hoot/core/scoring/BaseComparator.h \
    src/main/cpp/hoot/core/scoring/GraphComparator.h \
    src/main/cpp/hoot/core/algorithms/WaySplitter.h \
    src/main/cpp/hoot/core/conflate/splitter/IntersectionSplitter.h \
    src/main/cpp/hoot/core/scoring/DirectedGraph.h \
    src/main/cpp/hoot/core/scoring/ShortestPath.h \
    src/main/cpp/hoot/core/manipulators/DividedHighwayMerger.h \
    src/main/cpp/hoot/core/manipulators/Manipulation.h \
    src/main/cpp/hoot/core/manipulators/DividedHighwayManipulation.h \
    src/main/cpp/hoot/core/algorithms/WayHeading.h \
    src/main/cpp/hoot/core/filters/OneWayFilter.h \
    src/main/cpp/hoot/core/filters/WayFilter.h \
    src/main/cpp/hoot/core/filters/NeighborFilter.h \
    src/main/cpp/hoot/core/WayMap.h \
    src/main/cpp/hoot/core/NodeMap.h \
    src/main/cpp/hoot/core/filters/WayFilterChain.h \
    src/main/cpp/hoot/core/filters/UnknownFilter.h \
    src/main/cpp/hoot/core/filters/StatusFilter.h \
    src/main/cpp/hoot/core/filters/WayDirectionFilter.h \
    src/main/cpp/hoot/core/algorithms/LineStringAverager.h \
    src/main/cpp/hoot/core/filters/ParallelWayFilter.h \
    src/main/cpp/hoot/core/ops/SuperfluousNodeRemover.h \
    src/main/cpp/hoot/core/filters/WayBufferFilter.h \
    src/main/cpp/hoot/core/manipulators/WayMergeManipulation.h \
    src/main/cpp/hoot/core/algorithms/WayAverager.h \
    src/main/cpp/hoot/core/algorithms/ProbabilityOfMatch.h \
    src/main/cpp/hoot/core/conflate/SuperfluousWayRemover.h \
    src/main/cpp/hoot/core/conflate/splitter/DualWaySplitter.h \
    src/main/cpp/hoot/core/filters/DistanceNodeFilter.h \
    src/main/cpp/hoot/core/filters/NodeFilter.h \
    src/main/cpp/hoot/core/filters/Filter.h \
    src/main/cpp/hoot/core/filters/ChainNodeFilter.h \
    src/main/cpp/hoot/core/filters/InWayNodeFilter.h \
    src/main/cpp/hoot/core/conflate/UnlikelyIntersectionRemover.h \
    src/main/cpp/hoot/core/conflate/NodeToWayMap.h \
    src/main/cpp/hoot/core/conflate/ImpliedDividedMarker.h \
    src/main/cpp/hoot/core/ops/MapCropper.h \
    src/main/cpp/hoot/core/io/ShapefileWriter.h \
    src/main/cpp/hoot/core/conflate/DuplicateWayRemover.h \
    src/main/cpp/hoot/core/algorithms/LongestCommonNodeString.h \
    src/main/cpp/hoot/core/conflate/DuplicateNameRemover.h \
    src/main/cpp/hoot/core/util/Log.h \
    src/main/cpp/hoot/core/index/KnnWayIterator.h \
    src/main/cpp/hoot/core/elements/ElementListener.h \
    src/main/cpp/hoot/core/util/Validate.h \
    src/main/cpp/hoot/core/ops/MergeNearbyNodes.h \
    src/main/cpp/hoot/core/algorithms/LevenshteinDistance.h \
    src/main/cpp/hoot/core/schema/OsmSchema.h \
    src/main/cpp/hoot/core/schema/TagComparator.h \
    src/main/cpp/hoot/core/scoring/AttributeComparator.h \
    src/main/cpp/hoot/core/index/ClosePointHash.h \
    src/main/cpp/hoot/core/manipulators/DanglerRemover.h \
    src/main/cpp/hoot/core/manipulators/DanglerRemoverManipulation.h \
    src/main/cpp/hoot/core/conflate/SmallWayMerger.h \
    src/main/cpp/hoot/core/conflate/TileConflator.h \
    src/main/cpp/hoot/core/algorithms/Translator.h \
    src/main/cpp/hoot/core/conflate/LargeWaySplitter.h \
    src/main/cpp/hoot/core/conflate/OutsideBoundsRemover.h \
    src/main/cpp/hoot/core/OsmMapListener.h \
    src/main/cpp/hoot/core/util/NotImplementedException.h \
    src/main/cpp/hoot/core/util/FileUtils.h \
    src/main/cpp/hoot/core/conflate/NodeReplacements.h \
    src/main/cpp/hoot/core/conflate/TileBoundsCalculator.h \
    src/main/cpp/hoot/core/io/PbfReader.h \
    src/main/cpp/hoot/core/io/PbfWriter.h \
    src/main/cpp/hoot/core/io/PbfConstants.h \
    src/main/cpp/hoot/core/Version.h \
    src/main/cpp/hoot/core/cmd/Command.h \
    src/main/cpp/hoot/core/Factory.h \
    src/main/cpp/hoot/core/IdGenerator.h \
    src/main/cpp/hoot/core/DefaultIdGenerator.h \
    src/main/cpp/hoot/core/conflate/TileWorker.h \
    src/main/cpp/hoot/core/conflate/LocalTileWorker.h \
    src/main/cpp/hoot/core/util/ConfPath.h \
    src/main/cpp/hoot/core/util/GeometryUtils.h \
    src/main/cpp/hoot/core/util/SignalCatcher.h \
    src/main/cpp/hoot/core/manipulators/ManipulationDetails.h \
    src/main/cpp/hoot/core/ml/LogisticRegression.h \
    src/main/cpp/hoot/core/cmd/BaseCommand.h \
    src/main/cpp/hoot/core/conflate/MapCleaner.h \
    src/main/cpp/hoot/core/manipulators/WayTagMergeManipulation.h \
    src/main/cpp/hoot/core/manipulators/WayTagMerger.h \
    src/main/cpp/hoot/core/conflate/RubberSheet.h \
    src/main/cpp/hoot/core/conflate/NodeMatcher.h \
    src/main/cpp/hoot/core/util/Settings.h \
    src/main/cpp/hoot/core/elements/ElementIterator.h \
    src/main/cpp/hoot/core/io/ObjectOutputStream.h \
    src/main/cpp/hoot/core/io/ObjectInputStream.h \
    src/main/cpp/hoot/core/io/Serializable.h \
    src/main/cpp/hoot/core/ops/OsmMapOperation.h \
    src/main/cpp/hoot/core/ops/OpList.h \
    src/main/cpp/hoot/core/fourpass/FourPassManager.h \
    src/main/cpp/hoot/core/fourpass/LocalTileWorker2.h \
    src/main/cpp/hoot/core/fourpass/TileWorker2.h \
    src/main/cpp/hoot/core/ops/Boundable.h \
    src/main/cpp/hoot/core/ops/ReprojectToPlanarOp.h \
    src/main/cpp/hoot/core/ops/ReprojectToGeographicOp.h \
    src/main/cpp/hoot/core/elements/Relation.h \
    src/main/cpp/hoot/core/elements/RelationData.h \
    src/main/cpp/hoot/core/RelationMap.h \
    src/main/cpp/hoot/core/algorithms/AlphaShape.h \
    src/main/cpp/hoot/core/io/PbfElementIterator.h \
    src/main/cpp/hoot/core/ops/WaySplitterOp.h \
    src/main/cpp/hoot/core/ops/BuildingPartMergeOp.h \
    src/main/cpp/hoot/core/index/ElementToRelationMap.h \
    src/main/cpp/hoot/core/ops/BuildingOutlineUpdateOp.h \
    src/main/cpp/hoot/core/ops/RemoveDuplicateReviewsOp.h \
    src/main/cpp/hoot/core/ops/VisitorOp.h \
    src/main/cpp/hoot/core/OsmMapConsumer.h \
    src/main/cpp/hoot/core/ConstOsmMapConsumer.h \
    src/main/cpp/hoot/core/ops/NamedOp.h \
    src/main/cpp/hoot/core/visitors/ReportMissingElementsVisitor.h \
    src/main/cpp/hoot/core/visitors/KeepBuildingsVisitor.h \
    src/main/cpp/hoot/core/visitors/LengthOfWaysVisitor.h \
    src/main/cpp/hoot/core/visitors/AddRef1Visitor.h \
    src/main/cpp/hoot/core/visitors/AddRef2Visitor.h \
    src/main/cpp/hoot/core/conflate/extractors/FeatureExtractor.h \
    src/main/cpp/hoot/core/conflate/polygon/extractors/CentroidDistanceExtractor.h \
    src/main/cpp/hoot/core/conflate/polygon/extractors/AbstractDistanceExtractor.h \
    src/main/cpp/hoot/core/util/GeometryConverter.h \
    src/main/cpp/hoot/core/algorithms/VertexHausdorffDistance.h \
    src/main/cpp/hoot/core/elements/ElementId.h \
    src/main/cpp/hoot/core/elements/ElementType.h \
    src/main/cpp/hoot/core/manipulators/WayManipulator.h \
    src/main/cpp/hoot/core/conflate/polygon/extractors/HausdorffDistanceExtractor.h \
    src/main/cpp/hoot/core/visitors/RemoveElementsVisitor.h \
    src/main/cpp/hoot/core/filters/TagElementFilter.h \
    src/main/cpp/hoot/core/schema/Building.h \
    src/main/cpp/hoot/core/conflate/polygon/extractors/OverlapExtractor.h \
    src/main/cpp/hoot/core/conflate/polygon/extractors/CompactnessExtractor.h \
    src/main/cpp/hoot/core/conflate/polygon/extractors/AngleHistogramExtractor.h \
    src/main/cpp/hoot/core/conflate/polygon/extractors/NameExtractor.h \
    src/main/cpp/hoot/core/algorithms/Soundex.h \
    src/main/cpp/hoot/core/algorithms/StringDistance.h \
    src/main/cpp/hoot/core/algorithms/MeanWordSetDistance.h \
    src/main/cpp/hoot/core/schema/ScoreMatrix.h \
    src/main/cpp/hoot/core/algorithms/MaxWordSetDistance.h \
    src/main/cpp/hoot/core/schema/TranslateStringDistance.h \
    src/main/cpp/hoot/core/algorithms/ExactStringDistance.h \
    src/main/cpp/hoot/core/conflate/polygon/extractors/BufferedOverlapExtractor.h \
    src/main/cpp/hoot/core/conflate/polygon/extractors/SmallerOverlapExtractor.h \
    src/main/cpp/hoot/core/visitors/GetElementIdsVisitor.h \
    src/main/cpp/hoot/core/visitors/CountNodesVisitor.h \
    src/main/cpp/hoot/core/conflate/match-graph/MatchGraph.h \
    src/main/cpp/hoot/core/conflate/Match.h \
    src/main/cpp/hoot/core/conflate/polygon/BuildingMatch.h \
    src/main/cpp/hoot/core/conflate/polygon/BuildingMatchCreator.h \
    src/main/cpp/hoot/core/conflate/MatchCreator.h \
    src/main/cpp/hoot/core/conflate/Merger.h \
    src/main/cpp/hoot/core/conflate/MergerCreator.h \
    src/main/cpp/hoot/core/conflate/MergerFactory.h \
    src/main/cpp/hoot/core/conflate/polygon/BuildingMergerCreator.h \
    src/main/cpp/hoot/core/conflate/polygon/BuildingMerger.h \
    src/main/cpp/hoot/core/conflate/UnifyingConflator.h \
    src/main/cpp/hoot/core/conflate/MatchFactory.h \
    src/main/cpp/hoot/core/ops/RecursiveElementRemover.h \
    src/main/cpp/hoot/core/visitors/SetVisitor.h \
    src/main/cpp/hoot/core/ops/ConstOsmMapOperation.h \
    src/main/cpp/hoot/core/scoring/MatchComparator.h \
    src/main/cpp/hoot/core/visitors/AddUuidVisitor.h \
    src/main/cpp/hoot/core/visitors/FilteredVisitor.h \
    src/main/cpp/hoot/core/visitors/GetTagValuesVisitor.h \
    src/main/cpp/hoot/core/filters/IsNodeFilter.h \
    src/main/cpp/hoot/core/visitors/RemoveTagVisitor.h \
    src/main/cpp/hoot/core/visitors/ElementConstOsmMapVisitor.h \
    src/main/cpp/hoot/core/visitors/ElementOsmMapVisitor.h \
    src/main/cpp/hoot/core/filters/TagContainsFilter.h \
    src/main/cpp/hoot/core/visitors/SetTagVisitor.h \
    src/main/cpp/hoot/core/visitors/RemoveEmptyRelationsVisitor.h \
    src/main/cpp/hoot/core/visitors/RemoveEmptyAreasVisitor.h \
    src/main/cpp/hoot/core/visitors/RemoveDuplicateAreaVisitor.h \
    src/main/cpp/hoot/core/conflate/MatchType.h \
    src/main/cpp/hoot/core/conflate/MatchThreshold.h \
    src/main/cpp/hoot/core/conflate/MarkForReviewMerger.h \
    src/main/cpp/hoot/core/conflate/MarkForReviewMergerCreator.h \
    src/main/cpp/hoot/core/conflate/polygon/extractors/EdgeDistanceExtractor.h \
    src/main/cpp/hoot/core/algorithms/aggregator/ValueAggregator.h \
    src/main/cpp/hoot/core/algorithms/aggregator/QuantileAggregator.h \
    src/main/cpp/hoot/core/algorithms/aggregator/MeanAggregator.h \
    src/main/cpp/hoot/core/algorithms/aggregator/MinAggregator.h \
    src/main/cpp/hoot/core/algorithms/aggregator/MaxAggregator.h \
    src/main/cpp/hoot/core/algorithms/aggregator/RmseAggregator.h \
    src/main/cpp/hoot/core/algorithms/zindex/BBox.h \
    src/main/cpp/hoot/core/algorithms/zindex/LongBox.h \
    src/main/cpp/hoot/core/algorithms/zindex/Range.h \
    src/main/cpp/hoot/core/algorithms/zindex/ZCurveRanger.h \
    src/main/cpp/hoot/core/algorithms/zindex/ZValue.h \
    src/main/cpp/hoot/core/conflate/highway/HighwayMatch.h \
    src/main/cpp/hoot/core/conflate/highway/HighwayMergerCreator.h \
    src/main/cpp/hoot/core/conflate/highway/HighwayMatchCreator.h \
    src/main/cpp/hoot/core/conflate/highway/HighwayMerger.h \
    src/main/cpp/hoot/core/conflate/highway/HighwaySnapMerger.h \
    src/main/cpp/hoot/core/conflate/highway/HighwaySnapMergerCreator.h \
    src/main/cpp/hoot/core/manipulators/WaySnapMerger.h \
    src/main/cpp/hoot/core/manipulators/WaySnapMergeManipulation.h \
    src/main/cpp/hoot/core/visitors/MultiLineStringVisitor.h \
    src/main/cpp/hoot/core/visitors/IsCompleteVisitor.h \
    src/main/cpp/hoot/core/algorithms/MaximalSubline.h \
    src/main/cpp/hoot/core/algorithms/Sparse2dMatrix.h \
    src/main/cpp/hoot/core/visitors/RemoveUnknown1Visitor.h \
    src/main/cpp/hoot/core/visitors/UnionPolygonsVisitor.h \
    src/main/cpp/hoot/core/cmd/EvalMoveCmd.h \
    src/main/cpp/hoot/core/io/GmlWriter.h \
    src/main/cpp/hoot/core/algorithms/ExpectationIntersection.h \
    src/main/cpp/hoot/core/algorithms/linearreference/WaySublineMatch.h \
    src/main/cpp/hoot/core/algorithms/linearreference/WaySubline.h \
    src/main/cpp/hoot/core/filters/IntersectionFilter.h \
    src/main/cpp/hoot/core/ops/FindIntersectionsOp.h \
    src/main/cpp/hoot/core/cmd/FindIntersectionsCmd.h \
    src/main/cpp/hoot/core/visitors/FindIntersectionsVisitor.h \
    src/main/cpp/hoot/core/algorithms/optimizer/IntegerProgrammingSolver.h \
    src/main/cpp/hoot/core/conflate/match-graph/ConstrainedMatches.h \
    src/main/cpp/hoot/core/util/Configurable.h \
    src/main/cpp/hoot/core/perty/PertyRemoveRandomElementVisitor.h \
    src/main/cpp/hoot/core/perty/RngConsumer.h \
    src/main/cpp/hoot/core/perty/PertyNameVisitor.h \
    src/main/cpp/hoot/core/io/ScriptTranslator.h \
    src/main/cpp/hoot/core/io/PythonTranslator.h \
    src/main/cpp/hoot/core/perty/PertyDuplicatePoiOp.h \
    src/main/cpp/hoot/core/perty/PertyRemoveTagVisitor.h \
    src/main/cpp/hoot/core/io/GeoNamesReader.h \
    src/main/cpp/hoot/core/ops/TranslationOp.h \
    src/main/cpp/hoot/core/io/ScriptTranslatorFactory.h \
    src/main/cpp/hoot/core/scoring/MapComparator.h \
    src/main/cpp/hoot/core/util/Float.h \
    src/main/cpp/hoot/core/io/ApiDbReader.h \
    src/main/cpp/hoot/core/io/OsmApiDbReader.h \
    src/main/cpp/hoot/core/io/HootApiDbReader.h \
    src/main/cpp/hoot/core/io/HootApiDbWriter.h \
    src/main/cpp/hoot/core/perty/BigPertyOp.h \
    src/main/cpp/hoot/core/io/PartialOsmMapReader.h \
    src/main/cpp/hoot/core/io/OsmMapWriter.h \
    src/main/cpp/hoot/core/io/OsmMapReader.h \
    src/main/cpp/hoot/core/io/ApiDb.h \
    src/main/cpp/hoot/core/io/OsmApiDb.h \
    src/main/cpp/hoot/core/io/HootApiDb.h \
    src/main/cpp/hoot/core/io/OsmMapWriterFactory.h \
    src/main/cpp/hoot/core/io/OsmMapReaderFactory.h \
    src/main/cpp/hoot/core/io/OgrWriter.h \
    src/main/cpp/hoot/core/io/OgrUtilities.h \
    src/main/cpp/hoot/core/io/schema/Schema.h \
    src/main/cpp/hoot/core/io/schema/Layer.h \
    src/main/cpp/hoot/core/io/schema/FieldDefinition.h \
    src/main/cpp/hoot/core/io/schema/Feature.h \
    src/main/cpp/hoot/core/io/schema/FeatureDefinition.h \
    src/main/cpp/hoot/core/io/schema/StringFieldDefinition.h \
    src/main/cpp/hoot/core/io/schema/DoubleFieldDefinition.h \
    src/main/cpp/hoot/core/io/schema/IntegerFieldDefinition.h \
    src/main/cpp/hoot/core/index/metric-hybrid/FqTree.h \
    src/main/cpp/hoot/core/index/metric-hybrid/RFqHybridTree.h \
    src/main/cpp/hoot/core/index/metric-hybrid/RTree.h \
    src/main/cpp/hoot/core/index/metric-hybrid/Node.h \
    src/main/cpp/hoot/core/index/metric-hybrid/SubTreeCallback.h \
    src/main/cpp/hoot/core/io/schema/StrictChecking.h \
    src/main/cpp/hoot/core/schema/TagMerger.h \
    src/main/cpp/hoot/core/schema/AverageTagMerger.h \
    src/main/cpp/hoot/core/schema/TagMergerFactory.h \
    src/main/cpp/hoot/core/schema/GeneralizeTagMerger.h \
    src/main/cpp/hoot/core/visitors/DecomposeBuildingRelationsVisitor.h \
    src/main/cpp/hoot/core/ops/BuildingOutlineRemoveOp.h \
    src/main/cpp/hoot/core/schema/OverwriteTagMerger.h \
    src/main/cpp/hoot/core/visitors/KeepHighwaysVisitor.h \
    src/main/cpp/hoot/core/conflate/highway/HighwayClassifier.h \
    src/main/cpp/hoot/core/conflate/highway/HighwayExpertClassifier.h \
    src/main/cpp/hoot/core/conflate/MatchClassification.h \
    src/main/cpp/hoot/core/algorithms/SublineMatcher.h \
    src/main/cpp/hoot/core/algorithms/MaximalNearestSublineMatcher.h \
    src/main/cpp/hoot/core/util/FindNodesInWayFactory.h \
    src/main/cpp/hoot/core/util/UuidHelper.h \
    src/main/cpp/hoot/core/algorithms/SublineStringMatcher.h \
    src/main/cpp/hoot/core/algorithms/MaximalSublineStringMatcher.h \
    src/main/cpp/hoot/core/ops/CopySubsetOp.h \
    src/main/cpp/hoot/core/visitors/KeepNodesVisitor.h \
    src/main/cpp/hoot/core/algorithms/BufferedLineSegmentIntersector.h \
    src/main/cpp/hoot/core/conflate/MergerBase.h \
    src/main/cpp/hoot/core/util/ConfigDefaults.h \
    src/main/cpp/hoot/core/util/ConfigOptions.h \
    src/main/cpp/hoot/core/algorithms/MaximalSublineMatcher.h \
    src/main/cpp/hoot/core/algorithms/linearreference/WaySublineMatchString.h \
    src/main/cpp/hoot/core/algorithms/MultiLineStringSplitter.h \
    src/main/cpp/hoot/core/visitors/AddGeometryTypeVisitor.h \
    src/main/cpp/hoot/core/conflate/match-graph/MatchConflicts.h \
    src/main/cpp/hoot/core/conflate/match-graph/GreedyConstrainedMatches.h \
    src/main/cpp/hoot/core/conflate/match-graph/OptimalConstrainedMatches.h \
    src/main/cpp/hoot/core/visitors/ExtractWaysVisitor.h \
    src/main/cpp/hoot/core/scoring/MatchFeatureExtractor.h \
    src/main/cpp/hoot/core/conflate/MatchDetails.h \
    src/main/cpp/hoot/core/conflate/highway/HighwayRfClassifier.h \
    src/main/cpp/hoot/core/io/OgrOptions.h \
    src/main/cpp/hoot/core/ops/CalculateStatsOp.h \
    src/main/cpp/hoot/core/visitors/SingleStatistic.h \
    src/main/cpp/hoot/core/filters/HighwayFilter.h \
    src/main/cpp/hoot/core/filters/LinearFilter.h \
    src/main/cpp/hoot/core/filters/BaseFilter.h \
    src/main/cpp/hoot/core/filters/AreaFilter.h \
    src/main/cpp/hoot/core/filters/StatsAreaFilter.h \
    src/main/cpp/hoot/core/visitors/CalculateAreaVisitor.h \
    src/main/cpp/hoot/core/visitors/CalculateAreaForStatsVisitor.h \
    src/main/cpp/hoot/core/visitors/CountVisitor.h \
    src/main/cpp/hoot/core/visitors/UniqueNamesVisitor.h \
    src/main/cpp/hoot/core/io/db/BulkInsert.h \
    src/main/cpp/hoot/core/io/db/SqlBulkInsert.h \
    src/main/cpp/hoot/core/conflate/extractors/WeightedShapeDistanceExtractor.h \
    src/main/cpp/hoot/core/conflate/extractors/FeatureExtractorBase.h \
    src/main/cpp/hoot/core/visitors/WayVisitor.h \
    src/main/cpp/hoot/core/conflate/extractors/WayFeatureExtractor.h \
    src/main/cpp/hoot/core/conflate/extractors/WeightedMetricDistanceExtractor.h \
    src/main/cpp/hoot/core/conflate/extractors/AttributeScoreExtractor.h \
    src/main/cpp/hoot/core/conflate/extractors/LengthScoreExtractor.h \
    src/main/cpp/hoot/core/conflate/extractors/DistanceScoreExtractor.h \
    src/main/cpp/hoot/core/algorithms/aggregator/SigmaAggregator.h \
    src/main/cpp/hoot/core/conflate/extractors/AttributeDistanceExtractor.h \
    src/main/cpp/hoot/core/io/OsmJsonWriter.h \
    src/main/cpp/hoot/core/ops/stats/IoSingleStat.h \
    src/main/cpp/hoot/core/ops/stats/SingleStat.h \
    src/main/cpp/hoot/core/Hoot.h \
    src/main/cpp/hoot/core/schema/ExactTagDifferencer.h \
    src/main/cpp/hoot/core/schema/TagDifferencer.h \
    src/main/cpp/hoot/core/schema/ComparatorTagDifferencer.h \
    src/main/cpp/hoot/core/schema/TranslatedTagDifferencer.h \
    src/main/cpp/hoot/core/io/ScriptToOgrTranslator.h \
    src/main/cpp/hoot/core/conflate/polygon/BuildingRfClassifier.h \
    src/main/cpp/hoot/core/conflate/RfExtractorClassifier.h \
    src/main/cpp/hoot/core/util/MultiPolygonCreator.h \
    src/main/cpp/hoot/core/io/db/InternalIdReserver.h \
    src/main/cpp/hoot/core/conflate/ReviewMarker.h \
    src/main/cpp/hoot/core/visitors/LongestTagVisitor.h \
    src/main/cpp/hoot/core/conflate/MatchMembers.h \
    src/main/cpp/hoot/core/scoring/AttributeCoOccurence.h \
    src/main/cpp/hoot/core/visitors/TagCountVisitor.h \
    src/main/cpp/hoot/core/cmd/UnifyCmd.h \
    src/main/cpp/hoot/core/scoring/TextTable.h \
    src/main/cpp/hoot/core/algorithms/linearreference/MultiLineStringLocation.h \
    src/main/cpp/hoot/core/perty/PertyWaySplitVisitor.h \
    src/main/cpp/hoot/core/filters/ElementCriterion.h \
    src/main/cpp/hoot/core/filters/NotCriterion.h \
    src/main/cpp/hoot/core/filters/ElementCriterionConsumer.h \
    src/main/cpp/hoot/core/elements/Status.h \
    src/main/cpp/hoot/core/filters/StatusCriterion.h \
    src/main/cpp/hoot/core/filters/BuildingCriterion.h \
    src/main/cpp/hoot/core/ops/RefRemoveOp.h \
    src/main/cpp/hoot/core/filters/NoInformationCriterion.h \
    src/main/cpp/hoot/core/filters/OrCriterion.h \
    src/main/cpp/hoot/core/filters/ChainCriterion.h \
    src/main/cpp/hoot/core/filters/PoiCriterion.h \
    src/main/cpp/hoot/core/filters/ElementTypeCriterion.h \
    src/main/cpp/hoot/core/filters/TagCriterion.h \
    src/main/cpp/hoot/core/filters/HasTagCriterion.h \
    src/main/cpp/hoot/core/perty/PertyWayGeneralizeVisitor.h \
    src/main/cpp/hoot/core/util/RandomNumberUtils.h \
    src/main/cpp/hoot/core/algorithms/RdpWayGeneralizer.h \
    src/main/cpp/hoot/core/visitors/RemoveRef2Visitor.h \
    src/main/cpp/hoot/core/visitors/ElementVisitorConsumer.h \
    src/main/cpp/hoot/core/util/OsmUtils.h \
    src/main/cpp/hoot/core/visitors/SplitNameVisitor.h \
    src/main/cpp/hoot/core/visitors/TagRenameKeyVisitor.h \
    src/main/cpp/hoot/core/visitors/TagKeyCountVisitor.h \
    src/main/cpp/hoot/core/scoring/MatchScoringMapPreparer.h \
    src/main/cpp/hoot/core/scoring/MapMatchScoringUtils.h \
    src/main/cpp/hoot/core/visitors/TranslatedTagCountVisitor.h \
    src/main/cpp/hoot/core/conflate/MatchSet.h \
    src/main/cpp/hoot/core/perty/PertyTestRunResult.h \
    src/main/cpp/hoot/core/io/MapStatsWriter.h \
    src/main/cpp/hoot/core/conflate/NoInformationElementRemover.h \
    src/main/cpp/hoot/core/GeometryPainter.h \
    src/main/cpp/hoot/core/perty/PertyOp.h \
    src/main/cpp/hoot/core/perty/PertyMatchScorer.h \
    src/main/cpp/hoot/core/perty/PertyTestRunner.h \
    src/main/cpp/hoot/core/perty/PermuteGridCalculator.h \
    src/main/cpp/hoot/core/perty/DirectSequentialSimulation.h \
    src/main/cpp/hoot/core/elements/ElementConsumer.h \
    src/main/cpp/hoot/core/elements/ConstElementConsumer.h \
    src/main/cpp/hoot/core/PositiveIdGenerator.h \
    src/main/cpp/hoot/core/util/ElementConverter.h \
    src/main/cpp/hoot/core/io/PartialOsmMapWriter.h \
    src/main/cpp/hoot/core/elements/ElementProvider.h \
    src/main/cpp/hoot/core/io/EnvelopeProvider.h \
    src/main/cpp/hoot/core/visitors/TransliterateNameVisitor.h \
    src/main/cpp/hoot/core/algorithms/optimizer/SingleAssignmentProblemSolver.h \
    src/main/cpp/hoot/core/conflate/extractors/Histogram.h \
    src/main/cpp/hoot/core/conflate/extractors/SampledAngleHistogramExtractor.h \
    src/main/cpp/hoot/core/algorithms/StringDistanceConsumer.h \
    src/main/cpp/hoot/core/conflate/point/PoiRfClassifier.h \
    src/main/cpp/hoot/core/io/ArffWriter.h \
    src/main/cpp/hoot/core/scoring/DataSamples.h \
    src/main/cpp/hoot/core/io/ArffReader.h \
    src/main/cpp/hoot/core/conflate/StatsComposer.h \
    src/main/cpp/hoot/core/visitors/MinIdVisitor.h \
    src/main/cpp/hoot/core/visitors/MaxIdVisitor.h \
    src/main/cpp/hoot/core/conflate/WayCleaner.h \
    src/main/cpp/hoot/core/scoring/MapScoringStatusAndRefTagValidator.h \
    src/main/cpp/hoot/core/algorithms/aggregator/ValueAggregatorConsumer.h \
    src/main/cpp/hoot/core/scoring/AttributeCount.h \
    src/main/cpp/hoot/core/visitors/FeatureCountVisitor.h \
    src/main/cpp/hoot/core/conflate/SearchRadiusCalculator.h \
    src/main/cpp/hoot/core/elements/ElementVisitor.h \
    src/main/cpp/hoot/core/io/ElementInputStream.h \
    src/main/cpp/hoot/core/io/ElementOutputStream.h \
    src/main/cpp/hoot/core/visitors/TranslationVisitor.h \
    src/main/cpp/hoot/core/io/ElementVisitorInputStream.h \
    src/main/cpp/hoot/core/io/ElementCache.h \
    src/main/cpp/hoot/core/io/ElementCacheLRU.h \
    src/main/cpp/hoot/core/visitors/MatchCandidateCountVisitor.h \
    src/main/cpp/hoot/core/util/DataProducer.h \
    src/main/cpp/hoot/core/algorithms/string/WeightedWordDistance.h \
    src/main/cpp/hoot/core/algorithms/string/WordWeightDictionary.h \
    src/main/cpp/hoot/core/algorithms/string/TextFileWordWeightDictionary.h \
    src/main/cpp/hoot/core/algorithms/string/MinSumWordSetDistance.h \
    src/main/cpp/hoot/core/io/WordCountReader.h \
    src/main/cpp/hoot/core/io/WordCountWriter.h \
    src/main/cpp/hoot/core/io/WordCount.h \
    src/main/cpp/hoot/core/algorithms/string/SqliteWordWeightDictionary.h \
    src/main/cpp/hoot/core/algorithms/string/StringTokenizer.h \
    src/main/cpp/hoot/core/conflate/ConflateStatsHelper.h \
    src/main/cpp/hoot/core/util/DataProducer.h \
    src/main/cpp/hoot/core/filters/HighwayCriterion.h \
    src/main/cpp/hoot/core/visitors/KeepTagsVisitor.h \
    src/main/cpp/hoot/core/cmd/ConflateCmd.h \
    src/main/cpp/hoot/core/ops/CookieCutterOp.h \
    src/main/cpp/hoot/core/conflate/AlphaShapeGenerator.h \
    src/main/cpp/hoot/core/conflate/CookieCutter.h \
    src/main/cpp/hoot/core/visitors/SplitLongLinearWaysVisitor.h \
    src/main/cpp/hoot/core/ops/ReplaceElementOp.h \
    src/main/cpp/hoot/core/filters/NeedsReviewCriterion.h \
    src/main/cpp/hoot/core/visitors/CountUniqueReviewsVisitor.h \
    src/main/cpp/hoot/core/ops/RemoveReviewsByEidOp.h \
    src/main/cpp/hoot/core/conflate/highway/HighwayReviewCleanerOp.h \
    src/main/cpp/hoot/core/ops/AddHilbertReviewSortOrderOp.h \
    src/main/cpp/hoot/core/schema/SchemaVertex.h \
    src/main/cpp/hoot/core/schema/SchemaChecker.h \
    src/main/cpp/hoot/core/schema/KeyValuePair.h \
    src/main/cpp/hoot/core/schema/TagCategoryDifferencer.h \
    src/main/cpp/hoot/core/schema/TagAncestorDifferencer.h \
    src/main/cpp/hoot/core/schema/TagFilteredDifferencer.h \
    src/main/cpp/hoot/core/io/ElementSorter.h \
    src/main/cpp/hoot/core/io/ChangesetDeriver.h \
    src/main/cpp/hoot/core/io/ChangesetProvider.h \
    src/main/cpp/hoot/core/io/OsmChangesetXmlFileWriter.h \
    src/main/cpp/hoot/core/schema/OsmSchemaLoader.h \
    src/main/cpp/hoot/core/schema/OsmSchemaLoaderFactory.h \
    src/main/cpp/hoot/core/algorithms/string/MostEnglishName.h \
    src/main/cpp/hoot/core/visitors/MedianNodeVisitor.h \
    src/main/cpp/hoot/core/conflate/polygon/extractors/EuclideanDistanceExtractor.h \
    src/main/cpp/hoot/core/visitors/RemoveMissingElementsVisitor.h \
    src/main/cpp/hoot/core/visitors/ProjectToGeographicVisitor.h \
    src/main/cpp/hoot/core/filters/WaterwayCriterion.h \
    src/main/cpp/hoot/core/algorithms/linearreference/WayMapping.h \
    src/main/cpp/hoot/core/algorithms/linearreference/WayMatchStringMapping.h \
    src/main/cpp/hoot/core/algorithms/WayMatchStringMerger.h \
    src/main/cpp/hoot/core/algorithms/linearreference/NaiveWayMatchStringMapping.h \
    src/main/cpp/hoot/core/io/ElementComparer.h \
    src/main/cpp/hoot/core/io/OsmChangesetSqlFileWriter.h \
    src/main/cpp/hoot/core/ops/FindIntersectionsOp.h \
    src/main/cpp/hoot/core/filters/IntersectionCriterion.h \
    src/main/cpp/hoot/core/algorithms/linearreference/WayString.h \
    src/main/cpp/hoot/core/algorithms/linearreference/WaySublineCollection.h \
    src/main/cpp/hoot/core/visitors/ExtractNodesVisitor.h \
    src/main/cpp/hoot/core/algorithms/linearreference/WayMatchStringMappingConverter.h \
    src/main/cpp/hoot/core/io/OsmApiDbAwareHootApiDbWriter.h \
    src/main/cpp/hoot/core/io/OsmApiDbSqlChangesetWriter.h \
    src/main/cpp/hoot/core/io/OsmApiDbAwareHootApiDbReader.h \
    src/main/cpp/hoot/core/io/OsmJsonReader.h \
    src/main/cpp/hoot/core/visitors/RemoveInvalidReviewRelationsVisitor.h \
    src/main/cpp/hoot/core/filters/BuildingWayNodeCriterion.h \
    src/main/cpp/hoot/core/visitors/WorstCircularErrorVisitor.h \
    src/main/cpp/hoot/core/visitors/CalculateBoundsVisitor.h \
    src/main/cpp/hoot/core/algorithms/KskipBigramDistance.h \
    src/main/cpp/hoot/core/filters/ArbitraryCriterion.h \
    src/main/cpp/hoot/core/visitors/IndexElementsVisitor.h \
    src/main/cpp/hoot/core/visitors/FindWaysVisitor.h \
    src/main/cpp/hoot/core/filters/ContainsNodeCriterion.h \
    src/main/cpp/hoot/core/visitors/FindNodesVisitor.h \
    src/main/cpp/hoot/core/algorithms/WayMatchStringSplitter.h \
    src/main/cpp/hoot/core/filters/UnknownCriterion.h \
    src/main/cpp/hoot/core/filters/OneWayCriterion.h \
    src/main/cpp/hoot/core/filters/ParallelWayCriterion.h \
    src/main/cpp/hoot/core/filters/WayBufferCriterion.h \
    src/main/cpp/hoot/core/filters/WayDirectionCriterion.h \
    src/main/cpp/hoot/core/filters/DistanceNodeCriterion.h \
    src/main/cpp/hoot/core/io/db/PostgresqlDumpfileWriter.h \
    src/main/cpp/hoot/core/visitors/MapExtentVisitor.h \
    src/main/cpp/hoot/core/ops/RemoveElementOp.h \
    src/main/cpp/hoot/core/ops/RemoveNodeOp.h \
    src/main/cpp/hoot/core/ops/RemoveRelationOp.h \
    src/main/cpp/hoot/core/ops/RemoveWayOp.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatchCreator.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMatch.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMerger.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonMergerCreator.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonRfClassifier.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/filters/PoiPolygonPolyCriterion.h \
    src/main/cpp/hoot/core/filters/AreaCriterion.h \
    src/main/cpp/hoot/core/filters/WayCriterion.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/filters/PoiPolygonPoiCriterion.h \
    src/main/cpp/hoot/core/filters/NonBuildingAreaCriterion.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonDistance.h \
    src/main/cpp/hoot/core/visitors/CountManualMatchesVisitor.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonDistanceTruthRecorder.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonNameScoreExtractor.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonTypeScoreExtractor.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonAddressScoreExtractor.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonDistanceExtractor.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonAlphaShapeDistanceExtractor.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonReviewReducer.h \
    src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonAdvancedMatcher.h

